// Code generated by ent, DO NOT EDIT.

package rest

import (
	"context"
	"time"

	"github.com/dotwaffle/peeringdb-plus/ent"
	"github.com/dotwaffle/peeringdb-plus/ent/campus"
	"github.com/dotwaffle/peeringdb-plus/ent/carrier"
	"github.com/dotwaffle/peeringdb-plus/ent/carrierfacility"
	"github.com/dotwaffle/peeringdb-plus/ent/facility"
	"github.com/dotwaffle/peeringdb-plus/ent/internetexchange"
	"github.com/dotwaffle/peeringdb-plus/ent/ixfacility"
	"github.com/dotwaffle/peeringdb-plus/ent/ixlan"
	"github.com/dotwaffle/peeringdb-plus/ent/ixprefix"
	"github.com/dotwaffle/peeringdb-plus/ent/network"
	"github.com/dotwaffle/peeringdb-plus/ent/networkfacility"
	"github.com/dotwaffle/peeringdb-plus/ent/networkixlan"
	"github.com/dotwaffle/peeringdb-plus/ent/organization"
	"github.com/dotwaffle/peeringdb-plus/ent/poc"
	schema "github.com/dotwaffle/peeringdb-plus/ent/schema"
)

// CreateCampuParams defines parameters for creating a Campu via a POST request.
type CreateCampuParams struct {
	// FK to organization
	OrgID *int `json:"org_id,omitempty"`
	// Organization name (computed)
	OrgName *string `json:"org_name,omitempty"`
	// Campus name
	Name string `json:"name"`
	// Long name
	NameLong *string `json:"name_long,omitempty"`
	// Also known as
	Aka *string `json:"aka,omitempty"`
	// Campus website URL
	Website *string `json:"website,omitempty"`
	// Social media links
	SocialMedia []schema.SocialMedia `json:"social_media,omitempty"`
	// Notes
	Notes *string `json:"notes,omitempty"`
	// Country code
	Country *string `json:"country,omitempty"`
	// City
	City *string `json:"city,omitempty"`
	// Postal / ZIP code
	Zipcode *string `json:"zipcode,omitempty"`
	// State or province
	State *string `json:"state,omitempty"`
	// Logo URL
	Logo *string `json:"logo,omitempty"`
	// PeeringDB creation timestamp
	Created time.Time `json:"created"`
	// PeeringDB last update timestamp
	Updated time.Time `json:"updated"`
	// Record status
	Status *string `json:"status"`
}

func (c *CreateCampuParams) ApplyInputs(builder *ent.CampusCreate) *ent.CampusCreate {
	if c.OrgID != nil {
		builder.SetOrgID(*c.OrgID)
	}
	if c.OrgName != nil {
		builder.SetOrgName(*c.OrgName)
	}
	builder.SetName(c.Name)
	if c.NameLong != nil {
		builder.SetNameLong(*c.NameLong)
	}
	if c.Aka != nil {
		builder.SetAka(*c.Aka)
	}
	if c.Website != nil {
		builder.SetWebsite(*c.Website)
	}
	if c.SocialMedia != nil {
		builder.SetSocialMedia(c.SocialMedia)
	}
	if c.Notes != nil {
		builder.SetNotes(*c.Notes)
	}
	if c.Country != nil {
		builder.SetCountry(*c.Country)
	}
	if c.City != nil {
		builder.SetCity(*c.City)
	}
	if c.Zipcode != nil {
		builder.SetZipcode(*c.Zipcode)
	}
	if c.State != nil {
		builder.SetState(*c.State)
	}
	if c.Logo != nil {
		builder.SetLogo(*c.Logo)
	}
	builder.SetCreated(c.Created)
	builder.SetUpdated(c.Updated)
	if c.Status != nil {
		builder.SetStatus(*c.Status)
	}
	return builder
}

// Exec wraps all logic (mapping all provided values to the builder), creates the entity,
// and does another query (using provided query as base) to get the entity, with all eager
// loaded edges.
func (c *CreateCampuParams) Exec(ctx context.Context, builder *ent.CampusCreate, query *ent.CampusQuery) (*ent.Campus, error) {
	result, err := c.ApplyInputs(builder).Save(ctx)
	if err != nil {
		return nil, err
	}
	return EagerLoadCampu(query.Where(campus.ID(result.ID))).Only(ctx)
}

// CreateCarrierParams defines parameters for creating a Carrier via a POST request.
type CreateCarrierParams struct {
	// FK to organization
	OrgID *int `json:"org_id,omitempty"`
	// Organization name (computed)
	OrgName *string `json:"org_name,omitempty"`
	// Carrier name
	Name string `json:"name"`
	// Also known as
	Aka *string `json:"aka,omitempty"`
	// Long name
	NameLong *string `json:"name_long,omitempty"`
	// Carrier website URL
	Website *string `json:"website,omitempty"`
	// Social media links
	SocialMedia []schema.SocialMedia `json:"social_media,omitempty"`
	// Notes
	Notes *string `json:"notes,omitempty"`
	// Facility count (computed)
	FacCount *int `json:"fac_count,omitempty"`
	// Logo URL
	Logo *string `json:"logo,omitempty"`
	// PeeringDB creation timestamp
	Created time.Time `json:"created"`
	// PeeringDB last update timestamp
	Updated time.Time `json:"updated"`
	// Record status
	Status *string `json:"status"`
}

func (c *CreateCarrierParams) ApplyInputs(builder *ent.CarrierCreate) *ent.CarrierCreate {
	if c.OrgID != nil {
		builder.SetOrgID(*c.OrgID)
	}
	if c.OrgName != nil {
		builder.SetOrgName(*c.OrgName)
	}
	builder.SetName(c.Name)
	if c.Aka != nil {
		builder.SetAka(*c.Aka)
	}
	if c.NameLong != nil {
		builder.SetNameLong(*c.NameLong)
	}
	if c.Website != nil {
		builder.SetWebsite(*c.Website)
	}
	if c.SocialMedia != nil {
		builder.SetSocialMedia(c.SocialMedia)
	}
	if c.Notes != nil {
		builder.SetNotes(*c.Notes)
	}
	if c.FacCount != nil {
		builder.SetFacCount(*c.FacCount)
	}
	if c.Logo != nil {
		builder.SetLogo(*c.Logo)
	}
	builder.SetCreated(c.Created)
	builder.SetUpdated(c.Updated)
	if c.Status != nil {
		builder.SetStatus(*c.Status)
	}
	return builder
}

// Exec wraps all logic (mapping all provided values to the builder), creates the entity,
// and does another query (using provided query as base) to get the entity, with all eager
// loaded edges.
func (c *CreateCarrierParams) Exec(ctx context.Context, builder *ent.CarrierCreate, query *ent.CarrierQuery) (*ent.Carrier, error) {
	result, err := c.ApplyInputs(builder).Save(ctx)
	if err != nil {
		return nil, err
	}
	return EagerLoadCarrier(query.Where(carrier.ID(result.ID))).Only(ctx)
}

// CreateCarrierFacilityParams defines parameters for creating a CarrierFacility via a POST request.
type CreateCarrierFacilityParams struct {
	// FK to carrier
	CarrierID *int `json:"carrier_id,omitempty"`
	// FK to facility
	FacID *int `json:"fac_id,omitempty"`
	// Facility name (computed)
	Name *string `json:"name,omitempty"`
	// PeeringDB creation timestamp
	Created time.Time `json:"created"`
	// PeeringDB last update timestamp
	Updated time.Time `json:"updated"`
	// Record status
	Status *string `json:"status"`
}

func (c *CreateCarrierFacilityParams) ApplyInputs(builder *ent.CarrierFacilityCreate) *ent.CarrierFacilityCreate {
	if c.CarrierID != nil {
		builder.SetCarrierID(*c.CarrierID)
	}
	if c.FacID != nil {
		builder.SetFacID(*c.FacID)
	}
	if c.Name != nil {
		builder.SetName(*c.Name)
	}
	builder.SetCreated(c.Created)
	builder.SetUpdated(c.Updated)
	if c.Status != nil {
		builder.SetStatus(*c.Status)
	}
	return builder
}

// Exec wraps all logic (mapping all provided values to the builder), creates the entity,
// and does another query (using provided query as base) to get the entity, with all eager
// loaded edges.
func (c *CreateCarrierFacilityParams) Exec(ctx context.Context, builder *ent.CarrierFacilityCreate, query *ent.CarrierFacilityQuery) (*ent.CarrierFacility, error) {
	result, err := c.ApplyInputs(builder).Save(ctx)
	if err != nil {
		return nil, err
	}
	return EagerLoadCarrierFacility(query.Where(carrierfacility.ID(result.ID))).Only(ctx)
}

// CreateFacilityParams defines parameters for creating a Facility via a POST request.
type CreateFacilityParams struct {
	// FK to organization
	OrgID *int `json:"org_id,omitempty"`
	// Organization name (computed)
	OrgName *string `json:"org_name,omitempty"`
	// FK to campus
	CampusID *int `json:"campus_id,omitempty"`
	// Facility name
	Name string `json:"name"`
	// Also known as
	Aka *string `json:"aka,omitempty"`
	// Long name
	NameLong *string `json:"name_long,omitempty"`
	// Facility website URL
	Website *string `json:"website,omitempty"`
	// Social media links
	SocialMedia []schema.SocialMedia `json:"social_media,omitempty"`
	// CLLI code
	Clli *string `json:"clli,omitempty"`
	// Rencode
	Rencode *string `json:"rencode,omitempty"`
	// NPANXX
	Npanxx *string `json:"npanxx,omitempty"`
	// Technical contact email
	TechEmail *string `json:"tech_email,omitempty"`
	// Technical contact phone
	TechPhone *string `json:"tech_phone,omitempty"`
	// Sales contact email
	SalesEmail *string `json:"sales_email,omitempty"`
	// Sales contact phone
	SalesPhone *string `json:"sales_phone,omitempty"`
	// Property type
	Property *string `json:"property,omitempty"`
	// Has diverse serving substations
	DiverseServingSubstations *bool `json:"diverse_serving_substations,omitempty"`
	// Available voltage services
	AvailableVoltageServices []string `json:"available_voltage_services,omitempty"`
	// Notes
	Notes *string `json:"notes,omitempty"`
	// Region / continent
	RegionContinent *string `json:"region_continent,omitempty"`
	// Status dashboard URL
	StatusDashboard *string `json:"status_dashboard,omitempty"`
	// Logo URL
	Logo *string `json:"logo,omitempty"`
	// Network count (computed)
	NetCount *int `json:"net_count,omitempty"`
	// Internet exchange count (computed)
	IxCount *int `json:"ix_count,omitempty"`
	// Carrier count (computed)
	CarrierCount *int `json:"carrier_count,omitempty"`
	// Address line 1
	Address1 *string `json:"address1,omitempty"`
	// Address line 2
	Address2 *string `json:"address2,omitempty"`
	// City
	City *string `json:"city,omitempty"`
	// State or province
	State *string `json:"state,omitempty"`
	// Country code
	Country *string `json:"country,omitempty"`
	// Postal / ZIP code
	Zipcode *string `json:"zipcode,omitempty"`
	// Suite number
	Suite *string `json:"suite,omitempty"`
	// Floor
	Floor *string `json:"floor,omitempty"`
	// Latitude
	Latitude *float64 `json:"latitude,omitempty"`
	// Longitude
	Longitude *float64 `json:"longitude,omitempty"`
	// PeeringDB creation timestamp
	Created time.Time `json:"created"`
	// PeeringDB last update timestamp
	Updated time.Time `json:"updated"`
	// Record status
	Status *string `json:"status"`
}

func (c *CreateFacilityParams) ApplyInputs(builder *ent.FacilityCreate) *ent.FacilityCreate {
	if c.OrgID != nil {
		builder.SetOrgID(*c.OrgID)
	}
	if c.OrgName != nil {
		builder.SetOrgName(*c.OrgName)
	}
	if c.CampusID != nil {
		builder.SetCampusID(*c.CampusID)
	}
	builder.SetName(c.Name)
	if c.Aka != nil {
		builder.SetAka(*c.Aka)
	}
	if c.NameLong != nil {
		builder.SetNameLong(*c.NameLong)
	}
	if c.Website != nil {
		builder.SetWebsite(*c.Website)
	}
	if c.SocialMedia != nil {
		builder.SetSocialMedia(c.SocialMedia)
	}
	if c.Clli != nil {
		builder.SetClli(*c.Clli)
	}
	if c.Rencode != nil {
		builder.SetRencode(*c.Rencode)
	}
	if c.Npanxx != nil {
		builder.SetNpanxx(*c.Npanxx)
	}
	if c.TechEmail != nil {
		builder.SetTechEmail(*c.TechEmail)
	}
	if c.TechPhone != nil {
		builder.SetTechPhone(*c.TechPhone)
	}
	if c.SalesEmail != nil {
		builder.SetSalesEmail(*c.SalesEmail)
	}
	if c.SalesPhone != nil {
		builder.SetSalesPhone(*c.SalesPhone)
	}
	if c.Property != nil {
		builder.SetProperty(*c.Property)
	}
	if c.DiverseServingSubstations != nil {
		builder.SetDiverseServingSubstations(*c.DiverseServingSubstations)
	}
	if c.AvailableVoltageServices != nil {
		builder.SetAvailableVoltageServices(c.AvailableVoltageServices)
	}
	if c.Notes != nil {
		builder.SetNotes(*c.Notes)
	}
	if c.RegionContinent != nil {
		builder.SetRegionContinent(*c.RegionContinent)
	}
	if c.StatusDashboard != nil {
		builder.SetStatusDashboard(*c.StatusDashboard)
	}
	if c.Logo != nil {
		builder.SetLogo(*c.Logo)
	}
	if c.NetCount != nil {
		builder.SetNetCount(*c.NetCount)
	}
	if c.IxCount != nil {
		builder.SetIxCount(*c.IxCount)
	}
	if c.CarrierCount != nil {
		builder.SetCarrierCount(*c.CarrierCount)
	}
	if c.Address1 != nil {
		builder.SetAddress1(*c.Address1)
	}
	if c.Address2 != nil {
		builder.SetAddress2(*c.Address2)
	}
	if c.City != nil {
		builder.SetCity(*c.City)
	}
	if c.State != nil {
		builder.SetState(*c.State)
	}
	if c.Country != nil {
		builder.SetCountry(*c.Country)
	}
	if c.Zipcode != nil {
		builder.SetZipcode(*c.Zipcode)
	}
	if c.Suite != nil {
		builder.SetSuite(*c.Suite)
	}
	if c.Floor != nil {
		builder.SetFloor(*c.Floor)
	}
	if c.Latitude != nil {
		builder.SetLatitude(*c.Latitude)
	}
	if c.Longitude != nil {
		builder.SetLongitude(*c.Longitude)
	}
	builder.SetCreated(c.Created)
	builder.SetUpdated(c.Updated)
	if c.Status != nil {
		builder.SetStatus(*c.Status)
	}
	return builder
}

// Exec wraps all logic (mapping all provided values to the builder), creates the entity,
// and does another query (using provided query as base) to get the entity, with all eager
// loaded edges.
func (c *CreateFacilityParams) Exec(ctx context.Context, builder *ent.FacilityCreate, query *ent.FacilityQuery) (*ent.Facility, error) {
	result, err := c.ApplyInputs(builder).Save(ctx)
	if err != nil {
		return nil, err
	}
	return EagerLoadFacility(query.Where(facility.ID(result.ID))).Only(ctx)
}

// CreateInternetExchangeParams defines parameters for creating a InternetExchange via a POST request.
type CreateInternetExchangeParams struct {
	// FK to organization
	OrgID *int `json:"org_id,omitempty"`
	// Internet exchange name
	Name string `json:"name"`
	// Also known as
	Aka *string `json:"aka,omitempty"`
	// Long name
	NameLong *string `json:"name_long,omitempty"`
	// City
	City *string `json:"city"`
	// Country code
	Country *string `json:"country"`
	// Region / continent
	RegionContinent *string `json:"region_continent"`
	// Media type
	Media *string `json:"media"`
	// Notes
	Notes *string `json:"notes,omitempty"`
	// Supports unicast
	ProtoUnicast *bool `json:"proto_unicast"`
	// Supports multicast
	ProtoMulticast *bool `json:"proto_multicast"`
	// Supports IPv6
	ProtoIpv6 *bool `json:"proto_ipv6"`
	// Internet exchange website URL
	Website *string `json:"website,omitempty"`
	// Social media links
	SocialMedia []schema.SocialMedia `json:"social_media,omitempty"`
	// Statistics URL
	URLStats *string `json:"url_stats,omitempty"`
	// Technical contact email
	TechEmail *string `json:"tech_email,omitempty"`
	// Technical contact phone
	TechPhone *string `json:"tech_phone,omitempty"`
	// Policy contact email
	PolicyEmail *string `json:"policy_email,omitempty"`
	// Policy contact phone
	PolicyPhone *string `json:"policy_phone,omitempty"`
	// Sales contact email
	SalesEmail *string `json:"sales_email,omitempty"`
	// Sales contact phone
	SalesPhone *string `json:"sales_phone,omitempty"`
	// Network count (computed)
	NetCount *int `json:"net_count,omitempty"`
	// Facility count (computed)
	FacCount *int `json:"fac_count,omitempty"`
	// IXF net count
	IxfNetCount *int `json:"ixf_net_count"`
	// Last IXF import timestamp
	IxfLastImport *time.Time `json:"ixf_last_import,omitempty"`
	// IXF import request
	IxfImportRequest *string `json:"ixf_import_request,omitempty"`
	// IXF import request status
	IxfImportRequestStatus *string `json:"ixf_import_request_status,omitempty"`
	// Service level
	ServiceLevel *string `json:"service_level,omitempty"`
	// Terms
	Terms *string `json:"terms,omitempty"`
	// Status dashboard URL
	StatusDashboard *string `json:"status_dashboard,omitempty"`
	// Logo URL
	Logo *string `json:"logo,omitempty"`
	// PeeringDB creation timestamp
	Created time.Time `json:"created"`
	// PeeringDB last update timestamp
	Updated time.Time `json:"updated"`
	// Record status
	Status *string `json:"status"`
}

func (c *CreateInternetExchangeParams) ApplyInputs(builder *ent.InternetExchangeCreate) *ent.InternetExchangeCreate {
	if c.OrgID != nil {
		builder.SetOrgID(*c.OrgID)
	}
	builder.SetName(c.Name)
	if c.Aka != nil {
		builder.SetAka(*c.Aka)
	}
	if c.NameLong != nil {
		builder.SetNameLong(*c.NameLong)
	}
	if c.City != nil {
		builder.SetCity(*c.City)
	}
	if c.Country != nil {
		builder.SetCountry(*c.Country)
	}
	if c.RegionContinent != nil {
		builder.SetRegionContinent(*c.RegionContinent)
	}
	if c.Media != nil {
		builder.SetMedia(*c.Media)
	}
	if c.Notes != nil {
		builder.SetNotes(*c.Notes)
	}
	if c.ProtoUnicast != nil {
		builder.SetProtoUnicast(*c.ProtoUnicast)
	}
	if c.ProtoMulticast != nil {
		builder.SetProtoMulticast(*c.ProtoMulticast)
	}
	if c.ProtoIpv6 != nil {
		builder.SetProtoIpv6(*c.ProtoIpv6)
	}
	if c.Website != nil {
		builder.SetWebsite(*c.Website)
	}
	if c.SocialMedia != nil {
		builder.SetSocialMedia(c.SocialMedia)
	}
	if c.URLStats != nil {
		builder.SetURLStats(*c.URLStats)
	}
	if c.TechEmail != nil {
		builder.SetTechEmail(*c.TechEmail)
	}
	if c.TechPhone != nil {
		builder.SetTechPhone(*c.TechPhone)
	}
	if c.PolicyEmail != nil {
		builder.SetPolicyEmail(*c.PolicyEmail)
	}
	if c.PolicyPhone != nil {
		builder.SetPolicyPhone(*c.PolicyPhone)
	}
	if c.SalesEmail != nil {
		builder.SetSalesEmail(*c.SalesEmail)
	}
	if c.SalesPhone != nil {
		builder.SetSalesPhone(*c.SalesPhone)
	}
	if c.NetCount != nil {
		builder.SetNetCount(*c.NetCount)
	}
	if c.FacCount != nil {
		builder.SetFacCount(*c.FacCount)
	}
	if c.IxfNetCount != nil {
		builder.SetIxfNetCount(*c.IxfNetCount)
	}
	if c.IxfLastImport != nil {
		builder.SetIxfLastImport(*c.IxfLastImport)
	}
	if c.IxfImportRequest != nil {
		builder.SetIxfImportRequest(*c.IxfImportRequest)
	}
	if c.IxfImportRequestStatus != nil {
		builder.SetIxfImportRequestStatus(*c.IxfImportRequestStatus)
	}
	if c.ServiceLevel != nil {
		builder.SetServiceLevel(*c.ServiceLevel)
	}
	if c.Terms != nil {
		builder.SetTerms(*c.Terms)
	}
	if c.StatusDashboard != nil {
		builder.SetStatusDashboard(*c.StatusDashboard)
	}
	if c.Logo != nil {
		builder.SetLogo(*c.Logo)
	}
	builder.SetCreated(c.Created)
	builder.SetUpdated(c.Updated)
	if c.Status != nil {
		builder.SetStatus(*c.Status)
	}
	return builder
}

// Exec wraps all logic (mapping all provided values to the builder), creates the entity,
// and does another query (using provided query as base) to get the entity, with all eager
// loaded edges.
func (c *CreateInternetExchangeParams) Exec(ctx context.Context, builder *ent.InternetExchangeCreate, query *ent.InternetExchangeQuery) (*ent.InternetExchange, error) {
	result, err := c.ApplyInputs(builder).Save(ctx)
	if err != nil {
		return nil, err
	}
	return EagerLoadInternetExchange(query.Where(internetexchange.ID(result.ID))).Only(ctx)
}

// CreateIxFacilityParams defines parameters for creating a IxFacility via a POST request.
type CreateIxFacilityParams struct {
	// FK to internet exchange
	IxID *int `json:"ix_id,omitempty"`
	// FK to facility
	FacID *int `json:"fac_id,omitempty"`
	// Facility name (computed)
	Name *string `json:"name,omitempty"`
	// City (computed)
	City *string `json:"city,omitempty"`
	// Country (computed)
	Country *string `json:"country,omitempty"`
	// PeeringDB creation timestamp
	Created time.Time `json:"created"`
	// PeeringDB last update timestamp
	Updated time.Time `json:"updated"`
	// Record status
	Status *string `json:"status"`
}

func (c *CreateIxFacilityParams) ApplyInputs(builder *ent.IxFacilityCreate) *ent.IxFacilityCreate {
	if c.IxID != nil {
		builder.SetIxID(*c.IxID)
	}
	if c.FacID != nil {
		builder.SetFacID(*c.FacID)
	}
	if c.Name != nil {
		builder.SetName(*c.Name)
	}
	if c.City != nil {
		builder.SetCity(*c.City)
	}
	if c.Country != nil {
		builder.SetCountry(*c.Country)
	}
	builder.SetCreated(c.Created)
	builder.SetUpdated(c.Updated)
	if c.Status != nil {
		builder.SetStatus(*c.Status)
	}
	return builder
}

// Exec wraps all logic (mapping all provided values to the builder), creates the entity,
// and does another query (using provided query as base) to get the entity, with all eager
// loaded edges.
func (c *CreateIxFacilityParams) Exec(ctx context.Context, builder *ent.IxFacilityCreate, query *ent.IxFacilityQuery) (*ent.IxFacility, error) {
	result, err := c.ApplyInputs(builder).Save(ctx)
	if err != nil {
		return nil, err
	}
	return EagerLoadIxFacility(query.Where(ixfacility.ID(result.ID))).Only(ctx)
}

// CreateIxLanParams defines parameters for creating a IxLan via a POST request.
type CreateIxLanParams struct {
	// FK to internet exchange
	IxID *int `json:"ix_id,omitempty"`
	// IXLan name
	Name *string `json:"name,omitempty"`
	// Description
	Descr *string `json:"descr,omitempty"`
	// MTU
	Mtu *int `json:"mtu"`
	// 802.1Q support
	Dot1qSupport *bool `json:"dot1q_support"`
	// Route server ASN
	RsAsn *int `json:"rs_asn,omitempty"`
	// ARP sponge MAC address
	ArpSponge *string `json:"arp_sponge,omitempty"`
	// IXF member list URL visibility
	IxfIxpMemberListURLVisible *string `json:"ixf_ixp_member_list_url_visible"`
	// IXF import enabled
	IxfIxpImportEnabled *bool `json:"ixf_ixp_import_enabled"`
	// PeeringDB creation timestamp
	Created time.Time `json:"created"`
	// PeeringDB last update timestamp
	Updated time.Time `json:"updated"`
	// Record status
	Status *string `json:"status"`
}

func (c *CreateIxLanParams) ApplyInputs(builder *ent.IxLanCreate) *ent.IxLanCreate {
	if c.IxID != nil {
		builder.SetIxID(*c.IxID)
	}
	if c.Name != nil {
		builder.SetName(*c.Name)
	}
	if c.Descr != nil {
		builder.SetDescr(*c.Descr)
	}
	if c.Mtu != nil {
		builder.SetMtu(*c.Mtu)
	}
	if c.Dot1qSupport != nil {
		builder.SetDot1qSupport(*c.Dot1qSupport)
	}
	if c.RsAsn != nil {
		builder.SetRsAsn(*c.RsAsn)
	}
	if c.ArpSponge != nil {
		builder.SetArpSponge(*c.ArpSponge)
	}
	if c.IxfIxpMemberListURLVisible != nil {
		builder.SetIxfIxpMemberListURLVisible(*c.IxfIxpMemberListURLVisible)
	}
	if c.IxfIxpImportEnabled != nil {
		builder.SetIxfIxpImportEnabled(*c.IxfIxpImportEnabled)
	}
	builder.SetCreated(c.Created)
	builder.SetUpdated(c.Updated)
	if c.Status != nil {
		builder.SetStatus(*c.Status)
	}
	return builder
}

// Exec wraps all logic (mapping all provided values to the builder), creates the entity,
// and does another query (using provided query as base) to get the entity, with all eager
// loaded edges.
func (c *CreateIxLanParams) Exec(ctx context.Context, builder *ent.IxLanCreate, query *ent.IxLanQuery) (*ent.IxLan, error) {
	result, err := c.ApplyInputs(builder).Save(ctx)
	if err != nil {
		return nil, err
	}
	return EagerLoadIxLan(query.Where(ixlan.ID(result.ID))).Only(ctx)
}

// CreateIxPrefixParams defines parameters for creating a IxPrefix via a POST request.
type CreateIxPrefixParams struct {
	// FK to IXLan
	IxlanID *int `json:"ixlan_id,omitempty"`
	// Protocol (IPv4 or IPv6)
	Protocol string `json:"protocol"`
	// IP prefix
	Prefix string `json:"prefix"`
	// In default-free zone
	InDfz *bool `json:"in_dfz"`
	// Notes
	Notes *string `json:"notes,omitempty"`
	// PeeringDB creation timestamp
	Created time.Time `json:"created"`
	// PeeringDB last update timestamp
	Updated time.Time `json:"updated"`
	// Record status
	Status *string `json:"status"`
}

func (c *CreateIxPrefixParams) ApplyInputs(builder *ent.IxPrefixCreate) *ent.IxPrefixCreate {
	if c.IxlanID != nil {
		builder.SetIxlanID(*c.IxlanID)
	}
	builder.SetProtocol(c.Protocol)
	builder.SetPrefix(c.Prefix)
	if c.InDfz != nil {
		builder.SetInDfz(*c.InDfz)
	}
	if c.Notes != nil {
		builder.SetNotes(*c.Notes)
	}
	builder.SetCreated(c.Created)
	builder.SetUpdated(c.Updated)
	if c.Status != nil {
		builder.SetStatus(*c.Status)
	}
	return builder
}

// Exec wraps all logic (mapping all provided values to the builder), creates the entity,
// and does another query (using provided query as base) to get the entity, with all eager
// loaded edges.
func (c *CreateIxPrefixParams) Exec(ctx context.Context, builder *ent.IxPrefixCreate, query *ent.IxPrefixQuery) (*ent.IxPrefix, error) {
	result, err := c.ApplyInputs(builder).Save(ctx)
	if err != nil {
		return nil, err
	}
	return EagerLoadIxPrefix(query.Where(ixprefix.ID(result.ID))).Only(ctx)
}

// CreateNetworkParams defines parameters for creating a Network via a POST request.
type CreateNetworkParams struct {
	// FK to organization
	OrgID *int `json:"org_id,omitempty"`
	// Network name
	Name string `json:"name"`
	// Also known as
	Aka *string `json:"aka,omitempty"`
	// Long name
	NameLong *string `json:"name_long,omitempty"`
	// Network website URL
	Website *string `json:"website,omitempty"`
	// Social media links
	SocialMedia []schema.SocialMedia `json:"social_media,omitempty"`
	// Autonomous System Number
	Asn int `json:"asn"`
	// Looking glass URL
	LookingGlass *string `json:"looking_glass,omitempty"`
	// Route server URL
	RouteServer *string `json:"route_server,omitempty"`
	// IRR AS-SET
	IrrAsSet *string `json:"irr_as_set,omitempty"`
	// Network type
	InfoType *string `json:"info_type,omitempty"`
	// Network types (multi-choice)
	InfoTypes []string `json:"info_types,omitempty"`
	// IPv4 prefix count
	InfoPrefixes4 *int `json:"info_prefixes4,omitempty"`
	// IPv6 prefix count
	InfoPrefixes6 *int `json:"info_prefixes6,omitempty"`
	// Traffic level
	InfoTraffic *string `json:"info_traffic,omitempty"`
	// Traffic ratio
	InfoRatio *string `json:"info_ratio,omitempty"`
	// Geographic scope
	InfoScope *string `json:"info_scope,omitempty"`
	// Supports unicast
	InfoUnicast *bool `json:"info_unicast"`
	// Supports multicast
	InfoMulticast *bool `json:"info_multicast"`
	// Supports IPv6
	InfoIpv6 *bool `json:"info_ipv6"`
	// Never via route servers
	InfoNeverViaRouteServers *bool `json:"info_never_via_route_servers"`
	// Notes
	Notes *string `json:"notes,omitempty"`
	// Peering policy URL
	PolicyURL *string `json:"policy_url,omitempty"`
	// General peering policy
	PolicyGeneral *string `json:"policy_general,omitempty"`
	// Peering policy locations
	PolicyLocations *string `json:"policy_locations,omitempty"`
	// Peering policy ratio requirement
	PolicyRatio *bool `json:"policy_ratio"`
	// Peering policy contracts
	PolicyContracts *string `json:"policy_contracts,omitempty"`
	// Allow IXP update
	AllowIxpUpdate *bool `json:"allow_ixp_update"`
	// Status dashboard URL
	StatusDashboard *string `json:"status_dashboard,omitempty"`
	// RIR status
	RirStatus *string `json:"rir_status,omitempty"`
	// RIR status last updated
	RirStatusUpdated *time.Time `json:"rir_status_updated,omitempty"`
	// Logo URL
	Logo *string `json:"logo,omitempty"`
	// Internet exchange count (computed)
	IxCount *int `json:"ix_count,omitempty"`
	// Facility count (computed)
	FacCount *int `json:"fac_count,omitempty"`
	// Last netixlan update (computed)
	NetixlanUpdated *time.Time `json:"netixlan_updated,omitempty"`
	// Last netfac update (computed)
	NetfacUpdated *time.Time `json:"netfac_updated,omitempty"`
	// Last POC update (computed)
	PocUpdated *time.Time `json:"poc_updated,omitempty"`
	// PeeringDB creation timestamp
	Created time.Time `json:"created"`
	// PeeringDB last update timestamp
	Updated time.Time `json:"updated"`
	// Record status
	Status *string `json:"status"`
}

func (c *CreateNetworkParams) ApplyInputs(builder *ent.NetworkCreate) *ent.NetworkCreate {
	if c.OrgID != nil {
		builder.SetOrgID(*c.OrgID)
	}
	builder.SetName(c.Name)
	if c.Aka != nil {
		builder.SetAka(*c.Aka)
	}
	if c.NameLong != nil {
		builder.SetNameLong(*c.NameLong)
	}
	if c.Website != nil {
		builder.SetWebsite(*c.Website)
	}
	if c.SocialMedia != nil {
		builder.SetSocialMedia(c.SocialMedia)
	}
	builder.SetAsn(c.Asn)
	if c.LookingGlass != nil {
		builder.SetLookingGlass(*c.LookingGlass)
	}
	if c.RouteServer != nil {
		builder.SetRouteServer(*c.RouteServer)
	}
	if c.IrrAsSet != nil {
		builder.SetIrrAsSet(*c.IrrAsSet)
	}
	if c.InfoType != nil {
		builder.SetInfoType(*c.InfoType)
	}
	if c.InfoTypes != nil {
		builder.SetInfoTypes(c.InfoTypes)
	}
	if c.InfoPrefixes4 != nil {
		builder.SetInfoPrefixes4(*c.InfoPrefixes4)
	}
	if c.InfoPrefixes6 != nil {
		builder.SetInfoPrefixes6(*c.InfoPrefixes6)
	}
	if c.InfoTraffic != nil {
		builder.SetInfoTraffic(*c.InfoTraffic)
	}
	if c.InfoRatio != nil {
		builder.SetInfoRatio(*c.InfoRatio)
	}
	if c.InfoScope != nil {
		builder.SetInfoScope(*c.InfoScope)
	}
	if c.InfoUnicast != nil {
		builder.SetInfoUnicast(*c.InfoUnicast)
	}
	if c.InfoMulticast != nil {
		builder.SetInfoMulticast(*c.InfoMulticast)
	}
	if c.InfoIpv6 != nil {
		builder.SetInfoIpv6(*c.InfoIpv6)
	}
	if c.InfoNeverViaRouteServers != nil {
		builder.SetInfoNeverViaRouteServers(*c.InfoNeverViaRouteServers)
	}
	if c.Notes != nil {
		builder.SetNotes(*c.Notes)
	}
	if c.PolicyURL != nil {
		builder.SetPolicyURL(*c.PolicyURL)
	}
	if c.PolicyGeneral != nil {
		builder.SetPolicyGeneral(*c.PolicyGeneral)
	}
	if c.PolicyLocations != nil {
		builder.SetPolicyLocations(*c.PolicyLocations)
	}
	if c.PolicyRatio != nil {
		builder.SetPolicyRatio(*c.PolicyRatio)
	}
	if c.PolicyContracts != nil {
		builder.SetPolicyContracts(*c.PolicyContracts)
	}
	if c.AllowIxpUpdate != nil {
		builder.SetAllowIxpUpdate(*c.AllowIxpUpdate)
	}
	if c.StatusDashboard != nil {
		builder.SetStatusDashboard(*c.StatusDashboard)
	}
	if c.RirStatus != nil {
		builder.SetRirStatus(*c.RirStatus)
	}
	if c.RirStatusUpdated != nil {
		builder.SetRirStatusUpdated(*c.RirStatusUpdated)
	}
	if c.Logo != nil {
		builder.SetLogo(*c.Logo)
	}
	if c.IxCount != nil {
		builder.SetIxCount(*c.IxCount)
	}
	if c.FacCount != nil {
		builder.SetFacCount(*c.FacCount)
	}
	if c.NetixlanUpdated != nil {
		builder.SetNetixlanUpdated(*c.NetixlanUpdated)
	}
	if c.NetfacUpdated != nil {
		builder.SetNetfacUpdated(*c.NetfacUpdated)
	}
	if c.PocUpdated != nil {
		builder.SetPocUpdated(*c.PocUpdated)
	}
	builder.SetCreated(c.Created)
	builder.SetUpdated(c.Updated)
	if c.Status != nil {
		builder.SetStatus(*c.Status)
	}
	return builder
}

// Exec wraps all logic (mapping all provided values to the builder), creates the entity,
// and does another query (using provided query as base) to get the entity, with all eager
// loaded edges.
func (c *CreateNetworkParams) Exec(ctx context.Context, builder *ent.NetworkCreate, query *ent.NetworkQuery) (*ent.Network, error) {
	result, err := c.ApplyInputs(builder).Save(ctx)
	if err != nil {
		return nil, err
	}
	return EagerLoadNetwork(query.Where(network.ID(result.ID))).Only(ctx)
}

// CreateNetworkFacilityParams defines parameters for creating a NetworkFacility via a POST request.
type CreateNetworkFacilityParams struct {
	// FK to network
	NetID *int `json:"net_id,omitempty"`
	// FK to facility
	FacID *int `json:"fac_id,omitempty"`
	// Facility name (computed)
	Name *string `json:"name,omitempty"`
	// City (computed)
	City *string `json:"city,omitempty"`
	// Country (computed)
	Country *string `json:"country,omitempty"`
	// Local ASN at this facility
	LocalAsn int `json:"local_asn"`
	// PeeringDB creation timestamp
	Created time.Time `json:"created"`
	// PeeringDB last update timestamp
	Updated time.Time `json:"updated"`
	// Record status
	Status *string `json:"status"`
}

func (c *CreateNetworkFacilityParams) ApplyInputs(builder *ent.NetworkFacilityCreate) *ent.NetworkFacilityCreate {
	if c.NetID != nil {
		builder.SetNetID(*c.NetID)
	}
	if c.FacID != nil {
		builder.SetFacID(*c.FacID)
	}
	if c.Name != nil {
		builder.SetName(*c.Name)
	}
	if c.City != nil {
		builder.SetCity(*c.City)
	}
	if c.Country != nil {
		builder.SetCountry(*c.Country)
	}
	builder.SetLocalAsn(c.LocalAsn)
	builder.SetCreated(c.Created)
	builder.SetUpdated(c.Updated)
	if c.Status != nil {
		builder.SetStatus(*c.Status)
	}
	return builder
}

// Exec wraps all logic (mapping all provided values to the builder), creates the entity,
// and does another query (using provided query as base) to get the entity, with all eager
// loaded edges.
func (c *CreateNetworkFacilityParams) Exec(ctx context.Context, builder *ent.NetworkFacilityCreate, query *ent.NetworkFacilityQuery) (*ent.NetworkFacility, error) {
	result, err := c.ApplyInputs(builder).Save(ctx)
	if err != nil {
		return nil, err
	}
	return EagerLoadNetworkFacility(query.Where(networkfacility.ID(result.ID))).Only(ctx)
}

// CreateNetworkIxLanParams defines parameters for creating a NetworkIxLan via a POST request.
type CreateNetworkIxLanParams struct {
	// FK to network
	NetID *int `json:"net_id,omitempty"`
	// Internet exchange ID (computed, not an edge)
	IxID *int `json:"ix_id,omitempty"`
	// FK to IXLan
	IxlanID *int `json:"ixlan_id,omitempty"`
	// Exchange name (computed)
	Name *string `json:"name,omitempty"`
	// Notes
	Notes *string `json:"notes,omitempty"`
	// Port speed in Mbps
	Speed int `json:"speed"`
	// Autonomous System Number
	Asn int `json:"asn"`
	// IPv4 address
	Ipaddr4 *string `json:"ipaddr4,omitempty"`
	// IPv6 address
	Ipaddr6 *string `json:"ipaddr6,omitempty"`
	// Is route server peer
	IsRsPeer *bool `json:"is_rs_peer"`
	// BFD support
	BfdSupport *bool `json:"bfd_support"`
	// Operational status
	Operational *bool `json:"operational"`
	// Network-side facility ID
	NetSideID *int `json:"net_side_id,omitempty"`
	// IX-side facility ID
	IxSideID *int `json:"ix_side_id,omitempty"`
	// PeeringDB creation timestamp
	Created time.Time `json:"created"`
	// PeeringDB last update timestamp
	Updated time.Time `json:"updated"`
	// Record status
	Status *string `json:"status"`
}

func (c *CreateNetworkIxLanParams) ApplyInputs(builder *ent.NetworkIxLanCreate) *ent.NetworkIxLanCreate {
	if c.NetID != nil {
		builder.SetNetID(*c.NetID)
	}
	if c.IxID != nil {
		builder.SetIxID(*c.IxID)
	}
	if c.IxlanID != nil {
		builder.SetIxlanID(*c.IxlanID)
	}
	if c.Name != nil {
		builder.SetName(*c.Name)
	}
	if c.Notes != nil {
		builder.SetNotes(*c.Notes)
	}
	builder.SetSpeed(c.Speed)
	builder.SetAsn(c.Asn)
	if c.Ipaddr4 != nil {
		builder.SetIpaddr4(*c.Ipaddr4)
	}
	if c.Ipaddr6 != nil {
		builder.SetIpaddr6(*c.Ipaddr6)
	}
	if c.IsRsPeer != nil {
		builder.SetIsRsPeer(*c.IsRsPeer)
	}
	if c.BfdSupport != nil {
		builder.SetBfdSupport(*c.BfdSupport)
	}
	if c.Operational != nil {
		builder.SetOperational(*c.Operational)
	}
	if c.NetSideID != nil {
		builder.SetNetSideID(*c.NetSideID)
	}
	if c.IxSideID != nil {
		builder.SetIxSideID(*c.IxSideID)
	}
	builder.SetCreated(c.Created)
	builder.SetUpdated(c.Updated)
	if c.Status != nil {
		builder.SetStatus(*c.Status)
	}
	return builder
}

// Exec wraps all logic (mapping all provided values to the builder), creates the entity,
// and does another query (using provided query as base) to get the entity, with all eager
// loaded edges.
func (c *CreateNetworkIxLanParams) Exec(ctx context.Context, builder *ent.NetworkIxLanCreate, query *ent.NetworkIxLanQuery) (*ent.NetworkIxLan, error) {
	result, err := c.ApplyInputs(builder).Save(ctx)
	if err != nil {
		return nil, err
	}
	return EagerLoadNetworkIxLan(query.Where(networkixlan.ID(result.ID))).Only(ctx)
}

// CreateOrganizationParams defines parameters for creating a Organization via a POST request.
type CreateOrganizationParams struct {
	// Organization name
	Name string `json:"name"`
	// Also known as
	Aka *string `json:"aka,omitempty"`
	// Long name
	NameLong *string `json:"name_long,omitempty"`
	// Organization website URL
	Website *string `json:"website,omitempty"`
	// Social media links
	SocialMedia []schema.SocialMedia `json:"social_media,omitempty"`
	// Notes
	Notes *string `json:"notes,omitempty"`
	// Logo URL
	Logo *string `json:"logo,omitempty"`
	// Address line 1
	Address1 *string `json:"address1,omitempty"`
	// Address line 2
	Address2 *string `json:"address2,omitempty"`
	// City
	City *string `json:"city,omitempty"`
	// State or province
	State *string `json:"state,omitempty"`
	// Country code
	Country *string `json:"country,omitempty"`
	// Postal / ZIP code
	Zipcode *string `json:"zipcode,omitempty"`
	// Suite number
	Suite *string `json:"suite,omitempty"`
	// Floor
	Floor *string `json:"floor,omitempty"`
	// Latitude
	Latitude *float64 `json:"latitude,omitempty"`
	// Longitude
	Longitude *float64 `json:"longitude,omitempty"`
	// PeeringDB creation timestamp
	Created time.Time `json:"created"`
	// PeeringDB last update timestamp
	Updated time.Time `json:"updated"`
	// Record status
	Status *string `json:"status"`
}

func (c *CreateOrganizationParams) ApplyInputs(builder *ent.OrganizationCreate) *ent.OrganizationCreate {
	builder.SetName(c.Name)
	if c.Aka != nil {
		builder.SetAka(*c.Aka)
	}
	if c.NameLong != nil {
		builder.SetNameLong(*c.NameLong)
	}
	if c.Website != nil {
		builder.SetWebsite(*c.Website)
	}
	if c.SocialMedia != nil {
		builder.SetSocialMedia(c.SocialMedia)
	}
	if c.Notes != nil {
		builder.SetNotes(*c.Notes)
	}
	if c.Logo != nil {
		builder.SetLogo(*c.Logo)
	}
	if c.Address1 != nil {
		builder.SetAddress1(*c.Address1)
	}
	if c.Address2 != nil {
		builder.SetAddress2(*c.Address2)
	}
	if c.City != nil {
		builder.SetCity(*c.City)
	}
	if c.State != nil {
		builder.SetState(*c.State)
	}
	if c.Country != nil {
		builder.SetCountry(*c.Country)
	}
	if c.Zipcode != nil {
		builder.SetZipcode(*c.Zipcode)
	}
	if c.Suite != nil {
		builder.SetSuite(*c.Suite)
	}
	if c.Floor != nil {
		builder.SetFloor(*c.Floor)
	}
	if c.Latitude != nil {
		builder.SetLatitude(*c.Latitude)
	}
	if c.Longitude != nil {
		builder.SetLongitude(*c.Longitude)
	}
	builder.SetCreated(c.Created)
	builder.SetUpdated(c.Updated)
	if c.Status != nil {
		builder.SetStatus(*c.Status)
	}
	return builder
}

// Exec wraps all logic (mapping all provided values to the builder), creates the entity,
// and does another query (using provided query as base) to get the entity, with all eager
// loaded edges.
func (c *CreateOrganizationParams) Exec(ctx context.Context, builder *ent.OrganizationCreate, query *ent.OrganizationQuery) (*ent.Organization, error) {
	result, err := c.ApplyInputs(builder).Save(ctx)
	if err != nil {
		return nil, err
	}
	return EagerLoadOrganization(query.Where(organization.ID(result.ID))).Only(ctx)
}

// CreatePocParams defines parameters for creating a Poc via a POST request.
type CreatePocParams struct {
	// FK to network
	NetID *int `json:"net_id,omitempty"`
	// Contact role
	Role string `json:"role"`
	// Visibility level
	Visible *string `json:"visible"`
	// Contact name
	Name *string `json:"name,omitempty"`
	// Contact phone
	Phone *string `json:"phone,omitempty"`
	// Contact email
	Email *string `json:"email,omitempty"`
	// Contact URL
	URL *string `json:"url,omitempty"`
	// PeeringDB creation timestamp
	Created time.Time `json:"created"`
	// PeeringDB last update timestamp
	Updated time.Time `json:"updated"`
	// Record status
	Status *string `json:"status"`
}

func (c *CreatePocParams) ApplyInputs(builder *ent.PocCreate) *ent.PocCreate {
	if c.NetID != nil {
		builder.SetNetID(*c.NetID)
	}
	builder.SetRole(c.Role)
	if c.Visible != nil {
		builder.SetVisible(*c.Visible)
	}
	if c.Name != nil {
		builder.SetName(*c.Name)
	}
	if c.Phone != nil {
		builder.SetPhone(*c.Phone)
	}
	if c.Email != nil {
		builder.SetEmail(*c.Email)
	}
	if c.URL != nil {
		builder.SetURL(*c.URL)
	}
	builder.SetCreated(c.Created)
	builder.SetUpdated(c.Updated)
	if c.Status != nil {
		builder.SetStatus(*c.Status)
	}
	return builder
}

// Exec wraps all logic (mapping all provided values to the builder), creates the entity,
// and does another query (using provided query as base) to get the entity, with all eager
// loaded edges.
func (c *CreatePocParams) Exec(ctx context.Context, builder *ent.PocCreate, query *ent.PocQuery) (*ent.Poc, error) {
	result, err := c.ApplyInputs(builder).Save(ctx)
	if err != nil {
		return nil, err
	}
	return EagerLoadPoc(query.Where(poc.ID(result.ID))).Only(ctx)
}
