// Code generated by ent, DO NOT EDIT.

package rest

import (
	"fmt"
	"slices"
	"strings"

	"entgo.io/ent/dialect/sql"
	__ent "github.com/dotwaffle/peeringdb-plus/ent"
	__campus "github.com/dotwaffle/peeringdb-plus/ent/campus"
	__carrier "github.com/dotwaffle/peeringdb-plus/ent/carrier"
	__carrierfacility "github.com/dotwaffle/peeringdb-plus/ent/carrierfacility"
	__facility "github.com/dotwaffle/peeringdb-plus/ent/facility"
	__internetexchange "github.com/dotwaffle/peeringdb-plus/ent/internetexchange"
	__ixfacility "github.com/dotwaffle/peeringdb-plus/ent/ixfacility"
	__ixlan "github.com/dotwaffle/peeringdb-plus/ent/ixlan"
	__ixprefix "github.com/dotwaffle/peeringdb-plus/ent/ixprefix"
	__network "github.com/dotwaffle/peeringdb-plus/ent/network"
	__networkfacility "github.com/dotwaffle/peeringdb-plus/ent/networkfacility"
	__networkixlan "github.com/dotwaffle/peeringdb-plus/ent/networkixlan"
	__organization "github.com/dotwaffle/peeringdb-plus/ent/organization"
	__poc "github.com/dotwaffle/peeringdb-plus/ent/poc"
)

type Sorted struct {
	// Field is the field to sort by. Can be a standard field name (e.g. "name"), or a custom field
	// name (e.g. "pets.age.sum"). If no field is provided, the default field will be used.
	Field *string `json:"sort" form:"sort,omitempty"`

	// Order is the order to sort by. Can be either "asc" or "desc". If no order is provided, the
	// default order will be used.
	Order *orderDirection `json:"order" form:"order,omitempty"`
}

// Validate validates the sorting fields and applies any necessary defaults.
func (s *Sorted) Validate(_cfg *SortConfig) error {
	if s.Field == nil {
		if _cfg.DefaultField == "" {
			return nil
		}
		s.Field = &_cfg.DefaultField
	}
	if s.Order == nil {
		s.Order = &_cfg.DefaultOrder
	}

	if !slices.Contains(_cfg.Fields, *s.Field) {
		return &ErrBadRequest{Err: fmt.Errorf("invalid sort field: %s", *s.Field)}
	}

	if !slices.Contains(OrderDirections, *s.Order) {
		return &ErrBadRequest{Err: fmt.Errorf("invalid order: %s", *s.Order)}
	}

	return nil
}

// withOrderTerm returns the OrderTermOption (asc/desc) based on the provided order string.
func withOrderTerm(_order orderDirection) sql.OrderTermOption {
	if _order == orderAsc {
		return sql.OrderAsc()
	}
	return sql.OrderDesc()
}

func withFieldSelector(_field string, _order orderDirection) func(*sql.Selector) {
	if _order == orderAsc {
		return __ent.Asc(_field)
	}
	return __ent.Desc(_field)
}

type SortConfig struct {
	Fields       []string
	DefaultField string
	DefaultOrder orderDirection
}

type orderDirection string

var (
	orderAsc  orderDirection = "asc"
	orderDesc orderDirection = "desc"

	// OrderDirections are the allowed order directions that can be provided.
	OrderDirections = []orderDirection{orderAsc, orderDesc}
	// CampusSortConfig defines the default sort configuration for Campus.
	CampusSortConfig = &SortConfig{
		Fields: []string{
			"facilities.count",
			"id",
			"organization.updated",
			"random",
			"updated",
		},
		DefaultField: "updated",
		DefaultOrder: "desc",
	}
	// CarrierSortConfig defines the default sort configuration for Carrier.
	CarrierSortConfig = &SortConfig{
		Fields: []string{
			"carrier_facilities.count",
			"id",
			"organization.updated",
			"random",
			"updated",
		},
		DefaultField: "updated",
		DefaultOrder: "desc",
	}
	// CarrierFacilitySortConfig defines the default sort configuration for CarrierFacility.
	CarrierFacilitySortConfig = &SortConfig{
		Fields: []string{
			"carrier.updated",
			"facility.updated",
			"id",
			"random",
			"updated",
		},
		DefaultField: "updated",
		DefaultOrder: "desc",
	}
	// FacilitySortConfig defines the default sort configuration for Facility.
	FacilitySortConfig = &SortConfig{
		Fields: []string{
			"campus.updated",
			"carrier_facilities.count",
			"id",
			"ix_facilities.count",
			"network_facilities.count",
			"organization.updated",
			"random",
			"updated",
		},
		DefaultField: "updated",
		DefaultOrder: "desc",
	}
	// InternetExchangeSortConfig defines the default sort configuration for InternetExchange.
	InternetExchangeSortConfig = &SortConfig{
		Fields: []string{
			"id",
			"ix_facilities.count",
			"ix_lans.count",
			"organization.updated",
			"random",
			"updated",
		},
		DefaultField: "updated",
		DefaultOrder: "desc",
	}
	// IxFacilitySortConfig defines the default sort configuration for IxFacility.
	IxFacilitySortConfig = &SortConfig{
		Fields: []string{
			"facility.updated",
			"id",
			"internet_exchange.updated",
			"random",
			"updated",
		},
		DefaultField: "updated",
		DefaultOrder: "desc",
	}
	// IxLanSortConfig defines the default sort configuration for IxLan.
	IxLanSortConfig = &SortConfig{
		Fields: []string{
			"id",
			"internet_exchange.updated",
			"ix_prefixes.count",
			"network_ix_lans.count",
			"random",
			"updated",
		},
		DefaultField: "updated",
		DefaultOrder: "desc",
	}
	// IxPrefixSortConfig defines the default sort configuration for IxPrefix.
	IxPrefixSortConfig = &SortConfig{
		Fields: []string{
			"id",
			"ix_lan.updated",
			"random",
			"updated",
		},
		DefaultField: "updated",
		DefaultOrder: "desc",
	}
	// NetworkSortConfig defines the default sort configuration for Network.
	NetworkSortConfig = &SortConfig{
		Fields: []string{
			"id",
			"network_facilities.count",
			"network_ix_lans.count",
			"organization.updated",
			"random",
			"updated",
		},
		DefaultField: "updated",
		DefaultOrder: "desc",
	}
	// NetworkFacilitySortConfig defines the default sort configuration for NetworkFacility.
	NetworkFacilitySortConfig = &SortConfig{
		Fields: []string{
			"facility.updated",
			"id",
			"network.updated",
			"random",
			"updated",
		},
		DefaultField: "updated",
		DefaultOrder: "desc",
	}
	// NetworkIxLanSortConfig defines the default sort configuration for NetworkIxLan.
	NetworkIxLanSortConfig = &SortConfig{
		Fields: []string{
			"id",
			"ix_lan.updated",
			"network.updated",
			"random",
			"updated",
		},
		DefaultField: "updated",
		DefaultOrder: "desc",
	}
	// OrganizationSortConfig defines the default sort configuration for Organization.
	OrganizationSortConfig = &SortConfig{
		Fields: []string{
			"campuses.count",
			"carriers.count",
			"facilities.count",
			"id",
			"internet_exchanges.count",
			"networks.count",
			"random",
			"updated",
		},
		DefaultField: "updated",
		DefaultOrder: "desc",
	}
	// PocSortConfig defines the default sort configuration for Poc.
	PocSortConfig = &SortConfig{
		Fields: []string{
			"id",
			"network.updated",
			"random",
			"updated",
		},
		DefaultField: "updated",
		DefaultOrder: "desc",
	}
)

// isSpecializedSort checks if the sort field is a specialized sort field.
func isSpecializedSort(_parts []string) (isCount, isSum bool) {
	switch {
	case len(_parts) == 3:
		switch _parts[2] {
		case "count":
			isCount = true
		case "sum":
			isSum = true
		}
	case len(_parts) == 2:
		switch _parts[1] {
		case "count":
			isCount = true
		case "sum":
			isSum = true
		}
	}
	return isCount, isSum
}

// applySortingCampus applies sorting to the query based on the provided sort and
// order fields. Note that all inputs provided MUST ALREADY BE VALIDATED.
func applySortingCampus(_query *__ent.CampusQuery, _field string, _order orderDirection) *__ent.CampusQuery {
	if _parts := strings.Split(_field, "."); len(_parts) > 1 {
		_dir := withOrderTerm(_order)

		isCount, isSum := isSpecializedSort(_parts)

		switch _parts[0] {
		case __campus.EdgeFacilities:
			switch {
			case isCount:
				return _query.Order(__campus.ByFacilitiesCount(_dir))
			case isSum:
				return _query.Order(__campus.ByFacilities(sql.OrderBySum(_parts[1], _dir)))
			default:
				return _query.Order(__campus.ByFacilities(sql.OrderByField(_parts[1], _dir)))
			}
		case __campus.EdgeOrganization:
			return _query.Order(__campus.ByOrganizationField(_parts[1], _dir))
		}
	}
	if _field == "random" {
		return _query.Order(sql.OrderByRand())
	}
	// Compound-default tie-break: when the requested sort field is the
	// entity's declared default, append (FieldCreated, FieldID) tie-breakers in the
	// same order direction for parity with pdbcompat and grpcserver.
	if _field == "updated" {
		return _query.Order(
			withFieldSelector(_field, _order),
			withFieldSelector(__campus.FieldCreated, _order),
			withFieldSelector(__campus.FieldID, _order),
		)
	}
	return _query.Order(withFieldSelector(_field, _order))
}

// applySortingCarrier applies sorting to the query based on the provided sort and
// order fields. Note that all inputs provided MUST ALREADY BE VALIDATED.
func applySortingCarrier(_query *__ent.CarrierQuery, _field string, _order orderDirection) *__ent.CarrierQuery {
	if _parts := strings.Split(_field, "."); len(_parts) > 1 {
		_dir := withOrderTerm(_order)

		isCount, isSum := isSpecializedSort(_parts)

		switch _parts[0] {
		case __carrier.EdgeCarrierFacilities:
			switch {
			case isCount:
				return _query.Order(__carrier.ByCarrierFacilitiesCount(_dir))
			case isSum:
				return _query.Order(__carrier.ByCarrierFacilities(sql.OrderBySum(_parts[1], _dir)))
			default:
				return _query.Order(__carrier.ByCarrierFacilities(sql.OrderByField(_parts[1], _dir)))
			}
		case __carrier.EdgeOrganization:
			return _query.Order(__carrier.ByOrganizationField(_parts[1], _dir))
		}
	}
	if _field == "random" {
		return _query.Order(sql.OrderByRand())
	}
	// Compound-default tie-break: when the requested sort field is the
	// entity's declared default, append (FieldCreated, FieldID) tie-breakers in the
	// same order direction for parity with pdbcompat and grpcserver.
	if _field == "updated" {
		return _query.Order(
			withFieldSelector(_field, _order),
			withFieldSelector(__carrier.FieldCreated, _order),
			withFieldSelector(__carrier.FieldID, _order),
		)
	}
	return _query.Order(withFieldSelector(_field, _order))
}

// applySortingCarrierFacility applies sorting to the query based on the provided sort and
// order fields. Note that all inputs provided MUST ALREADY BE VALIDATED.
func applySortingCarrierFacility(_query *__ent.CarrierFacilityQuery, _field string, _order orderDirection) *__ent.CarrierFacilityQuery {
	if _parts := strings.Split(_field, "."); len(_parts) > 1 {
		_dir := withOrderTerm(_order)

		switch _parts[0] {
		case __carrierfacility.EdgeCarrier:
			return _query.Order(__carrierfacility.ByCarrierField(_parts[1], _dir))
		case __carrierfacility.EdgeFacility:
			return _query.Order(__carrierfacility.ByFacilityField(_parts[1], _dir))
		}
	}
	if _field == "random" {
		return _query.Order(sql.OrderByRand())
	}
	// Compound-default tie-break: when the requested sort field is the
	// entity's declared default, append (FieldCreated, FieldID) tie-breakers in the
	// same order direction for parity with pdbcompat and grpcserver.
	if _field == "updated" {
		return _query.Order(
			withFieldSelector(_field, _order),
			withFieldSelector(__carrierfacility.FieldCreated, _order),
			withFieldSelector(__carrierfacility.FieldID, _order),
		)
	}
	return _query.Order(withFieldSelector(_field, _order))
}

// applySortingFacility applies sorting to the query based on the provided sort and
// order fields. Note that all inputs provided MUST ALREADY BE VALIDATED.
func applySortingFacility(_query *__ent.FacilityQuery, _field string, _order orderDirection) *__ent.FacilityQuery {
	if _parts := strings.Split(_field, "."); len(_parts) > 1 {
		_dir := withOrderTerm(_order)

		isCount, isSum := isSpecializedSort(_parts)

		switch _parts[0] {
		case __facility.EdgeCampus:
			return _query.Order(__facility.ByCampusField(_parts[1], _dir))
		case __facility.EdgeCarrierFacilities:
			switch {
			case isCount:
				return _query.Order(__facility.ByCarrierFacilitiesCount(_dir))
			case isSum:
				return _query.Order(__facility.ByCarrierFacilities(sql.OrderBySum(_parts[1], _dir)))
			default:
				return _query.Order(__facility.ByCarrierFacilities(sql.OrderByField(_parts[1], _dir)))
			}
		case __facility.EdgeIxFacilities:
			switch {
			case isCount:
				return _query.Order(__facility.ByIxFacilitiesCount(_dir))
			case isSum:
				return _query.Order(__facility.ByIxFacilities(sql.OrderBySum(_parts[1], _dir)))
			default:
				return _query.Order(__facility.ByIxFacilities(sql.OrderByField(_parts[1], _dir)))
			}
		case __facility.EdgeNetworkFacilities:
			switch {
			case isCount:
				return _query.Order(__facility.ByNetworkFacilitiesCount(_dir))
			case isSum:
				return _query.Order(__facility.ByNetworkFacilities(sql.OrderBySum(_parts[1], _dir)))
			default:
				return _query.Order(__facility.ByNetworkFacilities(sql.OrderByField(_parts[1], _dir)))
			}
		case __facility.EdgeOrganization:
			return _query.Order(__facility.ByOrganizationField(_parts[1], _dir))
		}
	}
	if _field == "random" {
		return _query.Order(sql.OrderByRand())
	}
	// Compound-default tie-break: when the requested sort field is the
	// entity's declared default, append (FieldCreated, FieldID) tie-breakers in the
	// same order direction for parity with pdbcompat and grpcserver.
	if _field == "updated" {
		return _query.Order(
			withFieldSelector(_field, _order),
			withFieldSelector(__facility.FieldCreated, _order),
			withFieldSelector(__facility.FieldID, _order),
		)
	}
	return _query.Order(withFieldSelector(_field, _order))
}

// applySortingInternetExchange applies sorting to the query based on the provided sort and
// order fields. Note that all inputs provided MUST ALREADY BE VALIDATED.
func applySortingInternetExchange(_query *__ent.InternetExchangeQuery, _field string, _order orderDirection) *__ent.InternetExchangeQuery {
	if _parts := strings.Split(_field, "."); len(_parts) > 1 {
		_dir := withOrderTerm(_order)

		isCount, isSum := isSpecializedSort(_parts)

		switch _parts[0] {
		case __internetexchange.EdgeIxFacilities:
			switch {
			case isCount:
				return _query.Order(__internetexchange.ByIxFacilitiesCount(_dir))
			case isSum:
				return _query.Order(__internetexchange.ByIxFacilities(sql.OrderBySum(_parts[1], _dir)))
			default:
				return _query.Order(__internetexchange.ByIxFacilities(sql.OrderByField(_parts[1], _dir)))
			}
		case __internetexchange.EdgeIxLans:
			switch {
			case isCount:
				return _query.Order(__internetexchange.ByIxLansCount(_dir))
			case isSum:
				return _query.Order(__internetexchange.ByIxLans(sql.OrderBySum(_parts[1], _dir)))
			default:
				return _query.Order(__internetexchange.ByIxLans(sql.OrderByField(_parts[1], _dir)))
			}
		case __internetexchange.EdgeOrganization:
			return _query.Order(__internetexchange.ByOrganizationField(_parts[1], _dir))
		}
	}
	if _field == "random" {
		return _query.Order(sql.OrderByRand())
	}
	// Compound-default tie-break: when the requested sort field is the
	// entity's declared default, append (FieldCreated, FieldID) tie-breakers in the
	// same order direction for parity with pdbcompat and grpcserver.
	if _field == "updated" {
		return _query.Order(
			withFieldSelector(_field, _order),
			withFieldSelector(__internetexchange.FieldCreated, _order),
			withFieldSelector(__internetexchange.FieldID, _order),
		)
	}
	return _query.Order(withFieldSelector(_field, _order))
}

// applySortingIxFacility applies sorting to the query based on the provided sort and
// order fields. Note that all inputs provided MUST ALREADY BE VALIDATED.
func applySortingIxFacility(_query *__ent.IxFacilityQuery, _field string, _order orderDirection) *__ent.IxFacilityQuery {
	if _parts := strings.Split(_field, "."); len(_parts) > 1 {
		_dir := withOrderTerm(_order)

		switch _parts[0] {
		case __ixfacility.EdgeFacility:
			return _query.Order(__ixfacility.ByFacilityField(_parts[1], _dir))
		case __ixfacility.EdgeInternetExchange:
			return _query.Order(__ixfacility.ByInternetExchangeField(_parts[1], _dir))
		}
	}
	if _field == "random" {
		return _query.Order(sql.OrderByRand())
	}
	// Compound-default tie-break: when the requested sort field is the
	// entity's declared default, append (FieldCreated, FieldID) tie-breakers in the
	// same order direction for parity with pdbcompat and grpcserver.
	if _field == "updated" {
		return _query.Order(
			withFieldSelector(_field, _order),
			withFieldSelector(__ixfacility.FieldCreated, _order),
			withFieldSelector(__ixfacility.FieldID, _order),
		)
	}
	return _query.Order(withFieldSelector(_field, _order))
}

// applySortingIxLan applies sorting to the query based on the provided sort and
// order fields. Note that all inputs provided MUST ALREADY BE VALIDATED.
func applySortingIxLan(_query *__ent.IxLanQuery, _field string, _order orderDirection) *__ent.IxLanQuery {
	if _parts := strings.Split(_field, "."); len(_parts) > 1 {
		_dir := withOrderTerm(_order)

		isCount, isSum := isSpecializedSort(_parts)

		switch _parts[0] {
		case __ixlan.EdgeInternetExchange:
			return _query.Order(__ixlan.ByInternetExchangeField(_parts[1], _dir))
		case __ixlan.EdgeIxPrefixes:
			switch {
			case isCount:
				return _query.Order(__ixlan.ByIxPrefixesCount(_dir))
			case isSum:
				return _query.Order(__ixlan.ByIxPrefixes(sql.OrderBySum(_parts[1], _dir)))
			default:
				return _query.Order(__ixlan.ByIxPrefixes(sql.OrderByField(_parts[1], _dir)))
			}
		case __ixlan.EdgeNetworkIxLans:
			switch {
			case isCount:
				return _query.Order(__ixlan.ByNetworkIxLansCount(_dir))
			case isSum:
				return _query.Order(__ixlan.ByNetworkIxLans(sql.OrderBySum(_parts[1], _dir)))
			default:
				return _query.Order(__ixlan.ByNetworkIxLans(sql.OrderByField(_parts[1], _dir)))
			}
		}
	}
	if _field == "random" {
		return _query.Order(sql.OrderByRand())
	}
	// Compound-default tie-break: when the requested sort field is the
	// entity's declared default, append (FieldCreated, FieldID) tie-breakers in the
	// same order direction for parity with pdbcompat and grpcserver.
	if _field == "updated" {
		return _query.Order(
			withFieldSelector(_field, _order),
			withFieldSelector(__ixlan.FieldCreated, _order),
			withFieldSelector(__ixlan.FieldID, _order),
		)
	}
	return _query.Order(withFieldSelector(_field, _order))
}

// applySortingIxPrefix applies sorting to the query based on the provided sort and
// order fields. Note that all inputs provided MUST ALREADY BE VALIDATED.
func applySortingIxPrefix(_query *__ent.IxPrefixQuery, _field string, _order orderDirection) *__ent.IxPrefixQuery {
	if _parts := strings.Split(_field, "."); len(_parts) > 1 {
		_dir := withOrderTerm(_order)

		switch _parts[0] {
		case __ixprefix.EdgeIxLan:
			return _query.Order(__ixprefix.ByIxLanField(_parts[1], _dir))
		}
	}
	if _field == "random" {
		return _query.Order(sql.OrderByRand())
	}
	// Compound-default tie-break: when the requested sort field is the
	// entity's declared default, append (FieldCreated, FieldID) tie-breakers in the
	// same order direction for parity with pdbcompat and grpcserver.
	if _field == "updated" {
		return _query.Order(
			withFieldSelector(_field, _order),
			withFieldSelector(__ixprefix.FieldCreated, _order),
			withFieldSelector(__ixprefix.FieldID, _order),
		)
	}
	return _query.Order(withFieldSelector(_field, _order))
}

// applySortingNetwork applies sorting to the query based on the provided sort and
// order fields. Note that all inputs provided MUST ALREADY BE VALIDATED.
func applySortingNetwork(_query *__ent.NetworkQuery, _field string, _order orderDirection) *__ent.NetworkQuery {
	if _parts := strings.Split(_field, "."); len(_parts) > 1 {
		_dir := withOrderTerm(_order)

		isCount, isSum := isSpecializedSort(_parts)

		switch _parts[0] {
		case __network.EdgeNetworkFacilities:
			switch {
			case isCount:
				return _query.Order(__network.ByNetworkFacilitiesCount(_dir))
			case isSum:
				return _query.Order(__network.ByNetworkFacilities(sql.OrderBySum(_parts[1], _dir)))
			default:
				return _query.Order(__network.ByNetworkFacilities(sql.OrderByField(_parts[1], _dir)))
			}
		case __network.EdgeNetworkIxLans:
			switch {
			case isCount:
				return _query.Order(__network.ByNetworkIxLansCount(_dir))
			case isSum:
				return _query.Order(__network.ByNetworkIxLans(sql.OrderBySum(_parts[1], _dir)))
			default:
				return _query.Order(__network.ByNetworkIxLans(sql.OrderByField(_parts[1], _dir)))
			}
		case __network.EdgeOrganization:
			return _query.Order(__network.ByOrganizationField(_parts[1], _dir))
		case __network.EdgePocs:
			switch {
			case isCount:
				return _query.Order(__network.ByPocsCount(_dir))
			case isSum:
				return _query.Order(__network.ByPocs(sql.OrderBySum(_parts[1], _dir)))
			default:
				return _query.Order(__network.ByPocs(sql.OrderByField(_parts[1], _dir)))
			}
		}
	}
	if _field == "random" {
		return _query.Order(sql.OrderByRand())
	}
	// Compound-default tie-break: when the requested sort field is the
	// entity's declared default, append (FieldCreated, FieldID) tie-breakers in the
	// same order direction for parity with pdbcompat and grpcserver.
	if _field == "updated" {
		return _query.Order(
			withFieldSelector(_field, _order),
			withFieldSelector(__network.FieldCreated, _order),
			withFieldSelector(__network.FieldID, _order),
		)
	}
	return _query.Order(withFieldSelector(_field, _order))
}

// applySortingNetworkFacility applies sorting to the query based on the provided sort and
// order fields. Note that all inputs provided MUST ALREADY BE VALIDATED.
func applySortingNetworkFacility(_query *__ent.NetworkFacilityQuery, _field string, _order orderDirection) *__ent.NetworkFacilityQuery {
	if _parts := strings.Split(_field, "."); len(_parts) > 1 {
		_dir := withOrderTerm(_order)

		switch _parts[0] {
		case __networkfacility.EdgeFacility:
			return _query.Order(__networkfacility.ByFacilityField(_parts[1], _dir))
		case __networkfacility.EdgeNetwork:
			return _query.Order(__networkfacility.ByNetworkField(_parts[1], _dir))
		}
	}
	if _field == "random" {
		return _query.Order(sql.OrderByRand())
	}
	// Compound-default tie-break: when the requested sort field is the
	// entity's declared default, append (FieldCreated, FieldID) tie-breakers in the
	// same order direction for parity with pdbcompat and grpcserver.
	if _field == "updated" {
		return _query.Order(
			withFieldSelector(_field, _order),
			withFieldSelector(__networkfacility.FieldCreated, _order),
			withFieldSelector(__networkfacility.FieldID, _order),
		)
	}
	return _query.Order(withFieldSelector(_field, _order))
}

// applySortingNetworkIxLan applies sorting to the query based on the provided sort and
// order fields. Note that all inputs provided MUST ALREADY BE VALIDATED.
func applySortingNetworkIxLan(_query *__ent.NetworkIxLanQuery, _field string, _order orderDirection) *__ent.NetworkIxLanQuery {
	if _parts := strings.Split(_field, "."); len(_parts) > 1 {
		_dir := withOrderTerm(_order)

		switch _parts[0] {
		case __networkixlan.EdgeIxLan:
			return _query.Order(__networkixlan.ByIxLanField(_parts[1], _dir))
		case __networkixlan.EdgeNetwork:
			return _query.Order(__networkixlan.ByNetworkField(_parts[1], _dir))
		}
	}
	if _field == "random" {
		return _query.Order(sql.OrderByRand())
	}
	// Compound-default tie-break: when the requested sort field is the
	// entity's declared default, append (FieldCreated, FieldID) tie-breakers in the
	// same order direction for parity with pdbcompat and grpcserver.
	if _field == "updated" {
		return _query.Order(
			withFieldSelector(_field, _order),
			withFieldSelector(__networkixlan.FieldCreated, _order),
			withFieldSelector(__networkixlan.FieldID, _order),
		)
	}
	return _query.Order(withFieldSelector(_field, _order))
}

// applySortingOrganization applies sorting to the query based on the provided sort and
// order fields. Note that all inputs provided MUST ALREADY BE VALIDATED.
func applySortingOrganization(_query *__ent.OrganizationQuery, _field string, _order orderDirection) *__ent.OrganizationQuery {
	if _parts := strings.Split(_field, "."); len(_parts) > 1 {
		_dir := withOrderTerm(_order)

		isCount, isSum := isSpecializedSort(_parts)

		switch _parts[0] {
		case __organization.EdgeCampuses:
			switch {
			case isCount:
				return _query.Order(__organization.ByCampusesCount(_dir))
			case isSum:
				return _query.Order(__organization.ByCampuses(sql.OrderBySum(_parts[1], _dir)))
			default:
				return _query.Order(__organization.ByCampuses(sql.OrderByField(_parts[1], _dir)))
			}
		case __organization.EdgeCarriers:
			switch {
			case isCount:
				return _query.Order(__organization.ByCarriersCount(_dir))
			case isSum:
				return _query.Order(__organization.ByCarriers(sql.OrderBySum(_parts[1], _dir)))
			default:
				return _query.Order(__organization.ByCarriers(sql.OrderByField(_parts[1], _dir)))
			}
		case __organization.EdgeFacilities:
			switch {
			case isCount:
				return _query.Order(__organization.ByFacilitiesCount(_dir))
			case isSum:
				return _query.Order(__organization.ByFacilities(sql.OrderBySum(_parts[1], _dir)))
			default:
				return _query.Order(__organization.ByFacilities(sql.OrderByField(_parts[1], _dir)))
			}
		case __organization.EdgeInternetExchanges:
			switch {
			case isCount:
				return _query.Order(__organization.ByInternetExchangesCount(_dir))
			case isSum:
				return _query.Order(__organization.ByInternetExchanges(sql.OrderBySum(_parts[1], _dir)))
			default:
				return _query.Order(__organization.ByInternetExchanges(sql.OrderByField(_parts[1], _dir)))
			}
		case __organization.EdgeNetworks:
			switch {
			case isCount:
				return _query.Order(__organization.ByNetworksCount(_dir))
			case isSum:
				return _query.Order(__organization.ByNetworks(sql.OrderBySum(_parts[1], _dir)))
			default:
				return _query.Order(__organization.ByNetworks(sql.OrderByField(_parts[1], _dir)))
			}
		}
	}
	if _field == "random" {
		return _query.Order(sql.OrderByRand())
	}
	// Compound-default tie-break: when the requested sort field is the
	// entity's declared default, append (FieldCreated, FieldID) tie-breakers in the
	// same order direction for parity with pdbcompat and grpcserver.
	if _field == "updated" {
		return _query.Order(
			withFieldSelector(_field, _order),
			withFieldSelector(__organization.FieldCreated, _order),
			withFieldSelector(__organization.FieldID, _order),
		)
	}
	return _query.Order(withFieldSelector(_field, _order))
}

// applySortingPoc applies sorting to the query based on the provided sort and
// order fields. Note that all inputs provided MUST ALREADY BE VALIDATED.
func applySortingPoc(_query *__ent.PocQuery, _field string, _order orderDirection) *__ent.PocQuery {
	if _parts := strings.Split(_field, "."); len(_parts) > 1 {
		_dir := withOrderTerm(_order)

		switch _parts[0] {
		case __poc.EdgeNetwork:
			return _query.Order(__poc.ByNetworkField(_parts[1], _dir))
		}
	}
	if _field == "random" {
		return _query.Order(sql.OrderByRand())
	}
	// Compound-default tie-break: when the requested sort field is the
	// entity's declared default, append (FieldCreated, FieldID) tie-breakers in the
	// same order direction for parity with pdbcompat and grpcserver.
	if _field == "updated" {
		return _query.Order(
			withFieldSelector(_field, _order),
			withFieldSelector(__poc.FieldCreated, _order),
			withFieldSelector(__poc.FieldID, _order),
		)
	}
	return _query.Order(withFieldSelector(_field, _order))
}
