// Code generated by ent, DO NOT EDIT.

package campus

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the campus type in the database.
	Label = "campus"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldNameFold holds the string denoting the name_fold field in the database.
	FieldNameFold = "name_fold"
	// FieldOrgID holds the string denoting the org_id field in the database.
	FieldOrgID = "org_id"
	// FieldAka holds the string denoting the aka field in the database.
	FieldAka = "aka"
	// FieldCity holds the string denoting the city field in the database.
	FieldCity = "city"
	// FieldCountry holds the string denoting the country field in the database.
	FieldCountry = "country"
	// FieldLogo holds the string denoting the logo field in the database.
	FieldLogo = "logo"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldNameLong holds the string denoting the name_long field in the database.
	FieldNameLong = "name_long"
	// FieldNotes holds the string denoting the notes field in the database.
	FieldNotes = "notes"
	// FieldSocialMedia holds the string denoting the social_media field in the database.
	FieldSocialMedia = "social_media"
	// FieldState holds the string denoting the state field in the database.
	FieldState = "state"
	// FieldWebsite holds the string denoting the website field in the database.
	FieldWebsite = "website"
	// FieldZipcode holds the string denoting the zipcode field in the database.
	FieldZipcode = "zipcode"
	// FieldOrgName holds the string denoting the org_name field in the database.
	FieldOrgName = "org_name"
	// FieldCreated holds the string denoting the created field in the database.
	FieldCreated = "created"
	// FieldUpdated holds the string denoting the updated field in the database.
	FieldUpdated = "updated"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// EdgeFacilities holds the string denoting the facilities edge name in mutations.
	EdgeFacilities = "facilities"
	// EdgeOrganization holds the string denoting the organization edge name in mutations.
	EdgeOrganization = "organization"
	// Table holds the table name of the campus in the database.
	Table = "campuses"
	// FacilitiesTable is the table that holds the facilities relation/edge.
	FacilitiesTable = "facilities"
	// FacilitiesInverseTable is the table name for the Facility entity.
	// It exists in this package in order to avoid circular dependency with the "facility" package.
	FacilitiesInverseTable = "facilities"
	// FacilitiesColumn is the table column denoting the facilities relation/edge.
	FacilitiesColumn = "campus_id"
	// OrganizationTable is the table that holds the organization relation/edge.
	OrganizationTable = "campuses"
	// OrganizationInverseTable is the table name for the Organization entity.
	// It exists in this package in order to avoid circular dependency with the "organization" package.
	OrganizationInverseTable = "organizations"
	// OrganizationColumn is the table column denoting the organization relation/edge.
	OrganizationColumn = "org_id"
)

// Columns holds all SQL columns for campus fields.
var Columns = []string{
	FieldID,
	FieldNameFold,
	FieldOrgID,
	FieldAka,
	FieldCity,
	FieldCountry,
	FieldLogo,
	FieldName,
	FieldNameLong,
	FieldNotes,
	FieldSocialMedia,
	FieldState,
	FieldWebsite,
	FieldZipcode,
	FieldOrgName,
	FieldCreated,
	FieldUpdated,
	FieldStatus,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultNameFold holds the default value on creation for the "name_fold" field.
	DefaultNameFold string
	// DefaultCity holds the default value on creation for the "city" field.
	DefaultCity string
	// DefaultCountry holds the default value on creation for the "country" field.
	DefaultCountry string
	// DefaultNotes holds the default value on creation for the "notes" field.
	DefaultNotes string
	// DefaultState holds the default value on creation for the "state" field.
	DefaultState string
	// DefaultWebsite holds the default value on creation for the "website" field.
	DefaultWebsite string
	// DefaultZipcode holds the default value on creation for the "zipcode" field.
	DefaultZipcode string
	// DefaultOrgName holds the default value on creation for the "org_name" field.
	DefaultOrgName string
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(int) error
)

// OrderOption defines the ordering options for the Campus queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByNameFold orders the results by the name_fold field.
func ByNameFold(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNameFold, opts...).ToFunc()
}

// ByOrgID orders the results by the org_id field.
func ByOrgID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOrgID, opts...).ToFunc()
}

// ByAka orders the results by the aka field.
func ByAka(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAka, opts...).ToFunc()
}

// ByCity orders the results by the city field.
func ByCity(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCity, opts...).ToFunc()
}

// ByCountry orders the results by the country field.
func ByCountry(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCountry, opts...).ToFunc()
}

// ByLogo orders the results by the logo field.
func ByLogo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLogo, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByNameLong orders the results by the name_long field.
func ByNameLong(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNameLong, opts...).ToFunc()
}

// ByNotes orders the results by the notes field.
func ByNotes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNotes, opts...).ToFunc()
}

// ByState orders the results by the state field.
func ByState(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldState, opts...).ToFunc()
}

// ByWebsite orders the results by the website field.
func ByWebsite(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWebsite, opts...).ToFunc()
}

// ByZipcode orders the results by the zipcode field.
func ByZipcode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldZipcode, opts...).ToFunc()
}

// ByOrgName orders the results by the org_name field.
func ByOrgName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOrgName, opts...).ToFunc()
}

// ByCreated orders the results by the created field.
func ByCreated(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreated, opts...).ToFunc()
}

// ByUpdated orders the results by the updated field.
func ByUpdated(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdated, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByFacilitiesCount orders the results by facilities count.
func ByFacilitiesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newFacilitiesStep(), opts...)
	}
}

// ByFacilities orders the results by facilities terms.
func ByFacilities(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newFacilitiesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByOrganizationField orders the results by organization field.
func ByOrganizationField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newOrganizationStep(), sql.OrderByField(field, opts...))
	}
}
func newFacilitiesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(FacilitiesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, FacilitiesTable, FacilitiesColumn),
	)
}
func newOrganizationStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(OrganizationInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, OrganizationTable, OrganizationColumn),
	)
}
