package pdbcompat

// PrepareQueryAllowAnnotation is the ent schema.Annotation form of
// upstream PeeringDB's per-serializer prepare_query allowlist (Phase 70 D-01).
// Attached to a schema (node-level), its Fields slice enumerates the
// filter keys that the pdbcompat parser will resolve via Path A. The
// codegen tool cmd/pdb-compat-allowlist reads this annotation at
// gen.Graph walk time and emits internal/pdbcompat/allowlist_gen.go.
//
// Fields are stored verbatim (e.g. "org__name", "ixlan__ix__fac_count")
// — the codegen tool splits on "__" when populating AllowlistEntry.Via.
type PrepareQueryAllowAnnotation struct {
	Fields []string
}

// Name returns the stable annotation name consulted by the codegen tool
// when walking gen.Graph. Do NOT rename — grep-ability across ent
// schema files, cmd/pdb-compat-allowlist, and generated output is
// load-bearing.
func (PrepareQueryAllowAnnotation) Name() string { return "PrepareQueryAllow" }

// WithPrepareQueryAllow is the ent-schema-facing constructor. Use in
// schema Annotations() slices, e.g.
//
//	func (Network) Annotations() []schema.Annotation {
//	    return []schema.Annotation{
//	        pdbcompat.WithPrepareQueryAllow(
//	            "org__name",       // upstream serializers.py:2732
//	            "ixlan__ix__fac_count",
//	        ),
//	        // ...existing annotations...
//	    }
//	}
func WithPrepareQueryAllow(fields ...string) PrepareQueryAllowAnnotation {
	// Copy to avoid aliasing the caller's slice.
	out := make([]string, len(fields))
	copy(out, fields)
	return PrepareQueryAllowAnnotation{Fields: out}
}

// FilterExcludeFromTraversalAnnotation is the ent-edge-level form of
// upstream serializers.py:128-157's FILTER_EXCLUDE list (Phase 70 D-03).
// Attached to an edge (e.g. network.social_media), it signals the
// codegen tool to mark the edge as un-traversable — Path B
// introspection will skip it regardless of whether it matches the
// <fk>__<field> shape.
//
// No fields: presence is the signal.
type FilterExcludeFromTraversalAnnotation struct{}

// Name returns the stable annotation name. Do NOT rename.
func (FilterExcludeFromTraversalAnnotation) Name() string {
	return "FilterExcludeFromTraversal"
}

// WithFilterExcludeFromTraversal is the ent-schema-facing constructor.
// Attach to an edge to exclude it from Path B traversal, e.g.
//
//	edge.To("pocs", Poc.Type).
//	    Annotations(pdbcompat.WithFilterExcludeFromTraversal()),
//
// Initial expected call sites (Plan 70-03):
//   - Any edge that materialises as a JSON field (none today — placeholder)
//   - Relay id-alias edges generated by entgql (covered via codegen
//     introspection rather than explicit annotation; the tool detects
//     them by name).
func WithFilterExcludeFromTraversal() FilterExcludeFromTraversalAnnotation {
	return FilterExcludeFromTraversalAnnotation{}
}

// AllowlistEntry is the per-entity allowlist shape emitted into
// internal/pdbcompat/allowlist_gen.go by cmd/pdb-compat-allowlist.
// Consumed at request time by ParseFilters to decide whether a
// <fk>__<field> key is a valid Path A traversal.
//
//   - Direct: single-hop filter keys (e.g. "org__name"). Codegen
//     populates this from WithPrepareQueryAllow fields that contain
//     exactly one "__" separator AND whose first segment matches a
//     schema edge name.
//   - Via: 2-hop filter keys grouped by first hop. For
//     "ixlan__ix__fac_count" the map entry is
//     {"ixlan": {"ix__fac_count"}}. Codegen populates from fields that
//     contain exactly two "__" separators.
//
// Fields with zero or >2 "__" separators are either direct local
// fields (0 separators — live in TypeConfig.Fields instead) or too
// deep per D-04 (>2 separators — codegen drops them with a
// build-time warning).
type AllowlistEntry struct {
	Direct []string
	Via    map[string][]string
}
