package pdbcompat

import (
	"github.com/dotwaffle/peeringdb-plus/internal/pdbcompat/schemaannot"
)

// The ent schema annotation types live in the leaf sub-package
// internal/pdbcompat/schemaannot to avoid an import cycle:
//
//	pdbcompat → ent (registry.go)
//	ent/runtime → ent/schema (generated)
//	ent/schema → pdbcompat  ← this edge, if added, closes the cycle at
//	                          test-compile time via ent/enttest.
//
// ent/schema imports the sub-package directly; this file re-exports the
// types and constructors so existing in-package callers (allowlist_gen.go,
// annotations_test.go, Plan 70-05 parser) keep compiling unchanged.

// PrepareQueryAllowAnnotation aliases schemaannot.PrepareQueryAllowAnnotation.
// See the schemaannot package for full docs.
type PrepareQueryAllowAnnotation = schemaannot.PrepareQueryAllowAnnotation

// FilterExcludeFromTraversalAnnotation aliases
// schemaannot.FilterExcludeFromTraversalAnnotation.
type FilterExcludeFromTraversalAnnotation = schemaannot.FilterExcludeFromTraversalAnnotation

// WithPrepareQueryAllow is the pdbcompat-package-level constructor for
// Path A allowlist annotations (Phase 70 D-01). Re-exports
// schemaannot.WithPrepareQueryAllow so pdbcompat's existing API surface is
// unchanged. New ent/schema call sites should import the schemaannot
// sub-package directly to avoid the import cycle documented above.
func WithPrepareQueryAllow(fields ...string) PrepareQueryAllowAnnotation {
	return schemaannot.WithPrepareQueryAllow(fields...)
}

// WithFilterExcludeFromTraversal is the pdbcompat-package-level
// constructor for FILTER_EXCLUDE annotations (Phase 70 D-03). Re-exports
// schemaannot.WithFilterExcludeFromTraversal.
//
// Initial expected call sites (Plan 70-03):
//   - Any edge that materialises as a JSON field (none today — placeholder)
//   - Relay id-alias edges generated by entgql (covered via codegen
//     introspection rather than explicit annotation; the tool detects
//     them by name).
func WithFilterExcludeFromTraversal() FilterExcludeFromTraversalAnnotation {
	return schemaannot.WithFilterExcludeFromTraversal()
}

// AllowlistEntry is the per-entity allowlist shape emitted into
// internal/pdbcompat/allowlist_gen.go by cmd/pdb-compat-allowlist.
// Consumed at request time by ParseFilters to decide whether a
// <fk>__<field> key is a valid Path A traversal.
//
//   - Direct: single-hop filter keys (e.g. "org__name"). Codegen
//     populates this from WithPrepareQueryAllow fields that contain
//     exactly one "__" separator AND whose first segment matches a
//     schema edge name.
//   - Via: 2-hop filter keys grouped by first hop. For
//     "ixlan__ix__fac_count" the map entry is
//     {"ixlan": {"ix__fac_count"}}. Codegen populates from fields that
//     contain exactly two "__" separators.
//
// Fields with zero or >2 "__" separators are either direct local
// fields (0 separators — live in TypeConfig.Fields instead) or too
// deep per D-04 (>2 separators — codegen drops them with a
// build-time warning).
type AllowlistEntry struct {
	Direct []string
	Via    map[string][]string
}
