package schema

import "entgo.io/ent"

// Mixin wires Phase 69 UNICODE-01 fold shadow columns onto Network. Lives
// in this sibling file because network.go is regenerated by
// cmd/pdb-schema-generate from schema/peeringdb.json; the generator only
// touches files named after the model type (network.go) so this file is
// invisible to it. ent's codegen discovers the method via reflection on
// the Network schema type, so the file split is transparent to ent.
func (Network) Mixin() []ent.Mixin {
	return []ent.Mixin{
		foldMixin{fields: []string{"name", "aka", "name_long"}},
	}
}
