package schema

import (
	"context"

	"entgo.io/ent"

	pdbent "github.com/dotwaffle/peeringdb-plus/ent"
	"github.com/dotwaffle/peeringdb-plus/ent/poc"
	"github.com/dotwaffle/peeringdb-plus/ent/privacy"
	"github.com/dotwaffle/peeringdb-plus/internal/privctx"
)

// Policy returns the privacy policy for the Poc entity.
//
// Lives in this separate file because `poc.go` is regenerated by
// `cmd/pdb-schema-generate` from `schema/peeringdb.json`, which would
// strip hand-added methods. The generator only touches files named after
// the generated type (`poc.go`), so `poc_policy.go` is invisible to it.
// ent's codegen still picks this method up via reflection on the Poc
// schema type — the Go file split is transparent to ent.
//
// Query rule: a row is admitted when its visible value is in
// privctx.TierFrom(ctx).AdmittedVisibilities(), or when it is NULL (see
// the NULL-safety note below). TierPublic sees Public rows. TierUsers
// (env-override PDBPLUS_PUBLIC_TIER=users, or a future OAuth session)
// sees Public and Users rows. No tier sees Private rows: upstream shows
// them only to members of the owning organization (2.83.0
// permissions.py:336-339, signals.py:343-347), and the mirror has no
// organization membership. Sync workers bypass the policy via
// privacy.DecisionContext(ctx, privacy.Allow) set at worker entry
// (internal/sync/worker.go), so ingest is unaffected.
//
// No Mutation rule: sync writes travel the bypass; no other
// writers exist on this read-only mirror.
//
// NULL-safety: SQL three-valued logic makes
// `visible = 'Public'` FALSE for NULL, so we OR with VisibleIsNil for
// defence-in-depth against any future migration that leaves rows with
// unset visibility. The schema's Default("Public") also backstops this
// on inserts — two independent safeguards.
func (Poc) Policy() ent.Policy {
	return privacy.Policy{
		Query: privacy.QueryPolicy{
			privacy.PocQueryRuleFunc(func(ctx context.Context, q *pdbent.PocQuery) error {
				q.Where(poc.Or(
					poc.VisibleIn(privctx.TierFrom(ctx).AdmittedVisibilities()...),
					poc.VisibleIsNil(),
				))
				return privacy.Skip
			}),
		},
	}
}
