package main

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// testDataMinPy is the canonical stub used across tests. Lives under
// testdata/ so `go test ./cmd/pdb-fixture-port/` picks it up via the
// testdata-exclude convention.
const testDataMinPy = "testdata/pdb_api_test_min.py"

// TestFixturePort_HelpExitsZero asserts `--help` is a no-op success
// (flag.ContinueOnError + ErrHelp path). Guards against regressions
// where flag.Parse returns a non-help error on `--help`.
func TestFixturePort_HelpExitsZero(t *testing.T) {
	t.Parallel()
	var stdout, stderr bytes.Buffer
	code := run([]string{"--help"}, &stdout, &stderr)
	if code != exitOK {
		t.Fatalf("run --help = %d, want %d (stderr=%q)", code, exitOK, stderr.String())
	}
	combined := stderr.String() + stdout.String()
	if !strings.Contains(combined, "pdb-fixture-port") {
		t.Errorf("--help output missing tool name; got %q", combined)
	}
	if !strings.Contains(combined, "--check") {
		t.Errorf("--help output missing --check flag; got %q", combined)
	}
}

// TestFixturePort_EmitsSHAHeader locks the header contract the
// runtime consumers rely on (DO NOT EDIT marker, upstream git SHA,
// sha256 hash). Matches must_haves truth #3 in 72-01-PLAN.md.
func TestFixturePort_EmitsSHAHeader(t *testing.T) {
	t.Parallel()
	tmp := filepath.Join(t.TempDir(), "fixtures.go")
	args := []string{
		"--upstream-file", testDataMinPy,
		"--out", tmp,
		"--category", "ordering",
		"--date", "2026-04-19",
	}
	var out, errb bytes.Buffer
	code := run(args, &out, &errb)
	if code != exitOK {
		t.Fatalf("run() = %d, want %d; stderr=%q", code, exitOK, errb.String())
	}
	body, err := os.ReadFile(tmp) // #nosec G304 — test-controlled tempdir path.
	if err != nil {
		t.Fatalf("read output: %v", err)
	}
	// Assemble the expected sha256 from the input file so this test
	// continues to pass after testdata updates.
	in, err := os.ReadFile(testDataMinPy) // #nosec G304 — static testdata path.
	if err != nil {
		t.Fatalf("read testdata: %v", err)
	}
	want := sha256.Sum256(in)
	wantHex := hex.EncodeToString(want[:])

	mustContain := []string{
		"Code generated by cmd/pdb-fixture-port",
		"DO NOT EDIT",
		"Upstream:     peeringdb/peeringdb@",
		"UpstreamHash: sha256:" + wantHex,
		"Source:       " + upstreamPath,
		"Category:     ordering",
		"Ported:       2026-04-19",
		"package parity",
	}
	for _, needle := range mustContain {
		if !strings.Contains(string(body), needle) {
			t.Errorf("output missing %q", needle)
		}
	}
}

// TestFixturePort_DeterministicRender runs the tool twice against the
// same inputs and asserts byte-identical output. Guards against
// accidental non-determinism (map iteration order, time.Now() calls
// in the body, unsorted slices). Matches must_haves truth #5.
func TestFixturePort_DeterministicRender(t *testing.T) {
	t.Parallel()
	tmpDir := t.TempDir()
	pathA := filepath.Join(tmpDir, "a.go")
	pathB := filepath.Join(tmpDir, "b.go")
	baseArgs := []string{
		"--upstream-file", testDataMinPy,
		"--category", "ordering",
		"--date", "2026-04-19",
	}

	var outA, errA bytes.Buffer
	argsA := append([]string{}, baseArgs...)
	argsA = append(argsA, "--out", pathA)
	if code := run(argsA, &outA, &errA); code != exitOK {
		t.Fatalf("run #1 = %d; stderr=%q", code, errA.String())
	}
	var outB, errB bytes.Buffer
	argsB := append([]string{}, baseArgs...)
	argsB = append(argsB, "--out", pathB)
	if code := run(argsB, &outB, &errB); code != exitOK {
		t.Fatalf("run #2 = %d; stderr=%q", code, errB.String())
	}
	a, err := os.ReadFile(pathA) // #nosec G304 — tempdir.
	if err != nil {
		t.Fatalf("read A: %v", err)
	}
	b, err := os.ReadFile(pathB) // #nosec G304 — tempdir.
	if err != nil {
		t.Fatalf("read B: %v", err)
	}
	hashA := sha256.Sum256(a)
	hashB := sha256.Sum256(b)
	if hashA != hashB {
		t.Fatalf("two runs produced different output:\n A sha256=%x (%d bytes)\n B sha256=%x (%d bytes)", hashA, len(a), hashB, len(b))
	}
}

// TestFixturePort_CheckMatch covers the --check happy path: observed
// hash matches --pinned, tool exits 0 with a reassuring stdout
// message.
func TestFixturePort_CheckMatch(t *testing.T) {
	t.Parallel()
	in, err := os.ReadFile(testDataMinPy) // #nosec G304 — static testdata path.
	if err != nil {
		t.Fatalf("read testdata: %v", err)
	}
	want := sha256.Sum256(in)
	wantHex := hex.EncodeToString(want[:])

	var out, errb bytes.Buffer
	code := run([]string{
		"--upstream-file", testDataMinPy,
		"--check",
		"--pinned", wantHex,
	}, &out, &errb)
	if code != exitOK {
		t.Fatalf("--check matching = %d, want %d; stderr=%q", code, exitOK, errb.String())
	}
	if !strings.Contains(out.String(), "matches pinned sha256") {
		t.Errorf("expected stdout to announce match; got %q", out.String())
	}
}

// TestFixturePort_CheckMismatch covers the drift-alarm path: observed
// hash differs from --pinned, tool exits non-zero with a stderr
// message mentioning "drift".
func TestFixturePort_CheckMismatch(t *testing.T) {
	t.Parallel()
	// A clearly-wrong sha256 so the mismatch is unambiguous.
	wrong := strings.Repeat("0", 64)
	var out, errb bytes.Buffer
	code := run([]string{
		"--upstream-file", testDataMinPy,
		"--check",
		"--pinned", wrong,
	}, &out, &errb)
	if code != exitDrift {
		t.Fatalf("--check mismatch = %d, want %d (exitDrift); stderr=%q", code, exitDrift, errb.String())
	}
	if !strings.Contains(errb.String(), "drift") {
		t.Errorf("expected stderr to mention drift; got %q", errb.String())
	}
}

// TestParenDelta exercises the paren-depth scanner's string-awareness
// directly. Strings in Python fixture bodies may legitimately contain
// parens; the scanner must ignore them.
func TestParenDelta(t *testing.T) {
	t.Parallel()
	cases := []struct {
		name string
		in   string
		want int
	}{
		{name: "balanced", in: "foo(bar)", want: 0},
		{name: "open", in: "foo(", want: 1},
		{name: "close", in: ")", want: -1},
		{name: "string_quote_hides_paren", in: `"abc(def"`, want: 0},
		{name: "single_quote_hides_paren", in: `'abc(def'`, want: 0},
		{name: "nested_call", in: `foo(bar(baz))`, want: 0},
		{name: "escaped_quote_inside_string", in: `"a\"b("`, want: 0},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			if got := parenDelta(tc.in); got != tc.want {
				t.Errorf("parenDelta(%q) = %d, want %d", tc.in, got, tc.want)
			}
		})
	}
}

// TestExtractFields exercises the kwargs parser against the common
// shapes seen in upstream pdb_api_test.py.
func TestExtractFields(t *testing.T) {
	t.Parallel()
	block := "Network.objects.create(\n" +
		"    status=\"ok\",\n" +
		"    name=\"OrderNet-A\",\n" +
		"    asn=65001,\n" +
		"    # comment line — ignored\n" +
		"    **self.make_data_net(),\n" +
		")\n"
	got := extractFields(block)
	want := map[string]string{
		"status": "\"ok\"",
		"name":   "\"OrderNet-A\"",
		"asn":    "65001",
	}
	for k, v := range want {
		if got[k] != v {
			t.Errorf("field %q = %q, want %q", k, got[k], v)
		}
	}
	// `**self.make_data_net()` must be skipped.
	if _, ok := got["**self"]; ok {
		t.Errorf("kwargs-splat should be skipped; fields=%v", got)
	}
}

// TestOrderingTimestampsMonotonic locks the synthesised-timestamp
// contract the parity tests consume: later-line rows MUST carry
// later `created` timestamps (orderingCreatedAt is strictly increasing
// in line). Guards against future refactors that might accidentally
// introduce clock-skew or non-deterministic seeding.
func TestOrderingTimestampsMonotonic(t *testing.T) {
	t.Parallel()
	earlier := orderingCreatedAt(100)
	later := orderingCreatedAt(200)
	if !earlier.Before(later) {
		t.Errorf("created(100)=%v should be before created(200)=%v", earlier, later)
	}
	// `updated` offset from `created` by +24h per line.
	updated := orderingUpdatedAt(100)
	if !earlier.Before(updated) {
		t.Errorf("created(100)=%v should be before updated(100)=%v", earlier, updated)
	}
}

// TestSynthIDStability locks the ID-derivation contract: same inputs
// produce same ID on every call. A parity consumer should never see
// an ID shift between tool runs with identical upstream bytes.
func TestSynthIDStability(t *testing.T) {
	t.Parallel()
	fields := map[string]string{"name": "OrderNet-A", "asn": "65001"}
	a := synthID("net", 100, fields)
	b := synthID("net", 100, fields)
	if a != b {
		t.Errorf("synthID not stable: %d vs %d", a, b)
	}
	// Different line = different ID (high-probability collision check).
	c := synthID("net", 101, fields)
	if a == c {
		t.Errorf("synthID collided across lines 100/101 for %v: both %d", fields, a)
	}
}

// TestEntityGoNameCovers13 locks the invariant that the tool
// recognises all 13 PeeringDB entity types. Matches the same check
// cmd/pdb-compat-allowlist enforces via TestPdbTypeFor_AllThirteen.
func TestEntityGoNameCovers13(t *testing.T) {
	t.Parallel()
	want := map[string]string{
		"Network":                  "net",
		"Organization":             "org",
		"InternetExchange":         "ix",
		"IXLan":                    "ixlan",
		"IXLanPrefix":              "ixpfx",
		"Facility":                 "fac",
		"NetworkIXLan":             "netixlan",
		"NetworkFacility":          "netfac",
		"NetworkContact":           "poc",
		"Carrier":                  "carrier",
		"CarrierFacility":          "carrierfac",
		"Campus":                   "campus",
		"InternetExchangeFacility": "ixfac",
	}
	if len(entityGoName) != len(want) {
		t.Fatalf("entityGoName has %d entries, want %d", len(entityGoName), len(want))
	}
	for k, v := range want {
		if entityGoName[k] != v {
			t.Errorf("entityGoName[%q] = %q, want %q", k, entityGoName[k], v)
		}
	}
}
