// Code generated by ent, DO NOT EDIT.

package internetexchange

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the internetexchange type in the database.
	Label = "internet_exchange"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldNameFold holds the string denoting the name_fold field in the database.
	FieldNameFold = "name_fold"
	// FieldAkaFold holds the string denoting the aka_fold field in the database.
	FieldAkaFold = "aka_fold"
	// FieldNameLongFold holds the string denoting the name_long_fold field in the database.
	FieldNameLongFold = "name_long_fold"
	// FieldCityFold holds the string denoting the city_fold field in the database.
	FieldCityFold = "city_fold"
	// FieldOrgID holds the string denoting the org_id field in the database.
	FieldOrgID = "org_id"
	// FieldAka holds the string denoting the aka field in the database.
	FieldAka = "aka"
	// FieldCity holds the string denoting the city field in the database.
	FieldCity = "city"
	// FieldCountry holds the string denoting the country field in the database.
	FieldCountry = "country"
	// FieldIxfLastImport holds the string denoting the ixf_last_import field in the database.
	FieldIxfLastImport = "ixf_last_import"
	// FieldIxfNetCount holds the string denoting the ixf_net_count field in the database.
	FieldIxfNetCount = "ixf_net_count"
	// FieldLogo holds the string denoting the logo field in the database.
	FieldLogo = "logo"
	// FieldMedia holds the string denoting the media field in the database.
	FieldMedia = "media"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldNameLong holds the string denoting the name_long field in the database.
	FieldNameLong = "name_long"
	// FieldNotes holds the string denoting the notes field in the database.
	FieldNotes = "notes"
	// FieldPolicyEmail holds the string denoting the policy_email field in the database.
	FieldPolicyEmail = "policy_email"
	// FieldPolicyPhone holds the string denoting the policy_phone field in the database.
	FieldPolicyPhone = "policy_phone"
	// FieldProtoIpv6 holds the string denoting the proto_ipv6 field in the database.
	FieldProtoIpv6 = "proto_ipv6"
	// FieldProtoMulticast holds the string denoting the proto_multicast field in the database.
	FieldProtoMulticast = "proto_multicast"
	// FieldProtoUnicast holds the string denoting the proto_unicast field in the database.
	FieldProtoUnicast = "proto_unicast"
	// FieldRegionContinent holds the string denoting the region_continent field in the database.
	FieldRegionContinent = "region_continent"
	// FieldSalesEmail holds the string denoting the sales_email field in the database.
	FieldSalesEmail = "sales_email"
	// FieldSalesPhone holds the string denoting the sales_phone field in the database.
	FieldSalesPhone = "sales_phone"
	// FieldServiceLevel holds the string denoting the service_level field in the database.
	FieldServiceLevel = "service_level"
	// FieldSocialMedia holds the string denoting the social_media field in the database.
	FieldSocialMedia = "social_media"
	// FieldStatusDashboard holds the string denoting the status_dashboard field in the database.
	FieldStatusDashboard = "status_dashboard"
	// FieldTechEmail holds the string denoting the tech_email field in the database.
	FieldTechEmail = "tech_email"
	// FieldTechPhone holds the string denoting the tech_phone field in the database.
	FieldTechPhone = "tech_phone"
	// FieldTerms holds the string denoting the terms field in the database.
	FieldTerms = "terms"
	// FieldURLStats holds the string denoting the url_stats field in the database.
	FieldURLStats = "url_stats"
	// FieldWebsite holds the string denoting the website field in the database.
	FieldWebsite = "website"
	// FieldNetCount holds the string denoting the net_count field in the database.
	FieldNetCount = "net_count"
	// FieldFacCount holds the string denoting the fac_count field in the database.
	FieldFacCount = "fac_count"
	// FieldIxfImportRequest holds the string denoting the ixf_import_request field in the database.
	FieldIxfImportRequest = "ixf_import_request"
	// FieldIxfImportRequestStatus holds the string denoting the ixf_import_request_status field in the database.
	FieldIxfImportRequestStatus = "ixf_import_request_status"
	// FieldCreated holds the string denoting the created field in the database.
	FieldCreated = "created"
	// FieldUpdated holds the string denoting the updated field in the database.
	FieldUpdated = "updated"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// EdgeIxFacilities holds the string denoting the ix_facilities edge name in mutations.
	EdgeIxFacilities = "ix_facilities"
	// EdgeIxLans holds the string denoting the ix_lans edge name in mutations.
	EdgeIxLans = "ix_lans"
	// EdgeOrganization holds the string denoting the organization edge name in mutations.
	EdgeOrganization = "organization"
	// Table holds the table name of the internetexchange in the database.
	Table = "internet_exchanges"
	// IxFacilitiesTable is the table that holds the ix_facilities relation/edge.
	IxFacilitiesTable = "ix_facilities"
	// IxFacilitiesInverseTable is the table name for the IxFacility entity.
	// It exists in this package in order to avoid circular dependency with the "ixfacility" package.
	IxFacilitiesInverseTable = "ix_facilities"
	// IxFacilitiesColumn is the table column denoting the ix_facilities relation/edge.
	IxFacilitiesColumn = "ix_id"
	// IxLansTable is the table that holds the ix_lans relation/edge.
	IxLansTable = "ix_lans"
	// IxLansInverseTable is the table name for the IxLan entity.
	// It exists in this package in order to avoid circular dependency with the "ixlan" package.
	IxLansInverseTable = "ix_lans"
	// IxLansColumn is the table column denoting the ix_lans relation/edge.
	IxLansColumn = "ix_id"
	// OrganizationTable is the table that holds the organization relation/edge.
	OrganizationTable = "internet_exchanges"
	// OrganizationInverseTable is the table name for the Organization entity.
	// It exists in this package in order to avoid circular dependency with the "organization" package.
	OrganizationInverseTable = "organizations"
	// OrganizationColumn is the table column denoting the organization relation/edge.
	OrganizationColumn = "org_id"
)

// Columns holds all SQL columns for internetexchange fields.
var Columns = []string{
	FieldID,
	FieldNameFold,
	FieldAkaFold,
	FieldNameLongFold,
	FieldCityFold,
	FieldOrgID,
	FieldAka,
	FieldCity,
	FieldCountry,
	FieldIxfLastImport,
	FieldIxfNetCount,
	FieldLogo,
	FieldMedia,
	FieldName,
	FieldNameLong,
	FieldNotes,
	FieldPolicyEmail,
	FieldPolicyPhone,
	FieldProtoIpv6,
	FieldProtoMulticast,
	FieldProtoUnicast,
	FieldRegionContinent,
	FieldSalesEmail,
	FieldSalesPhone,
	FieldServiceLevel,
	FieldSocialMedia,
	FieldStatusDashboard,
	FieldTechEmail,
	FieldTechPhone,
	FieldTerms,
	FieldURLStats,
	FieldWebsite,
	FieldNetCount,
	FieldFacCount,
	FieldIxfImportRequest,
	FieldIxfImportRequestStatus,
	FieldCreated,
	FieldUpdated,
	FieldStatus,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultNameFold holds the default value on creation for the "name_fold" field.
	DefaultNameFold string
	// DefaultAkaFold holds the default value on creation for the "aka_fold" field.
	DefaultAkaFold string
	// DefaultNameLongFold holds the default value on creation for the "name_long_fold" field.
	DefaultNameLongFold string
	// DefaultCityFold holds the default value on creation for the "city_fold" field.
	DefaultCityFold string
	// DefaultAka holds the default value on creation for the "aka" field.
	DefaultAka string
	// DefaultCity holds the default value on creation for the "city" field.
	DefaultCity string
	// DefaultCountry holds the default value on creation for the "country" field.
	DefaultCountry string
	// DefaultIxfNetCount holds the default value on creation for the "ixf_net_count" field.
	DefaultIxfNetCount int
	// DefaultMedia holds the default value on creation for the "media" field.
	DefaultMedia string
	// DefaultNameLong holds the default value on creation for the "name_long" field.
	DefaultNameLong string
	// DefaultNotes holds the default value on creation for the "notes" field.
	DefaultNotes string
	// DefaultPolicyEmail holds the default value on creation for the "policy_email" field.
	DefaultPolicyEmail string
	// DefaultPolicyPhone holds the default value on creation for the "policy_phone" field.
	DefaultPolicyPhone string
	// DefaultProtoIpv6 holds the default value on creation for the "proto_ipv6" field.
	DefaultProtoIpv6 bool
	// DefaultProtoMulticast holds the default value on creation for the "proto_multicast" field.
	DefaultProtoMulticast bool
	// DefaultProtoUnicast holds the default value on creation for the "proto_unicast" field.
	DefaultProtoUnicast bool
	// DefaultRegionContinent holds the default value on creation for the "region_continent" field.
	DefaultRegionContinent string
	// DefaultSalesEmail holds the default value on creation for the "sales_email" field.
	DefaultSalesEmail string
	// DefaultSalesPhone holds the default value on creation for the "sales_phone" field.
	DefaultSalesPhone string
	// DefaultServiceLevel holds the default value on creation for the "service_level" field.
	DefaultServiceLevel string
	// DefaultTechEmail holds the default value on creation for the "tech_email" field.
	DefaultTechEmail string
	// DefaultTechPhone holds the default value on creation for the "tech_phone" field.
	DefaultTechPhone string
	// DefaultTerms holds the default value on creation for the "terms" field.
	DefaultTerms string
	// DefaultURLStats holds the default value on creation for the "url_stats" field.
	DefaultURLStats string
	// DefaultWebsite holds the default value on creation for the "website" field.
	DefaultWebsite string
	// DefaultNetCount holds the default value on creation for the "net_count" field.
	DefaultNetCount int
	// DefaultFacCount holds the default value on creation for the "fac_count" field.
	DefaultFacCount int
	// DefaultIxfImportRequestStatus holds the default value on creation for the "ixf_import_request_status" field.
	DefaultIxfImportRequestStatus string
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(int) error
)

// OrderOption defines the ordering options for the InternetExchange queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByNameFold orders the results by the name_fold field.
func ByNameFold(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNameFold, opts...).ToFunc()
}

// ByAkaFold orders the results by the aka_fold field.
func ByAkaFold(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAkaFold, opts...).ToFunc()
}

// ByNameLongFold orders the results by the name_long_fold field.
func ByNameLongFold(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNameLongFold, opts...).ToFunc()
}

// ByCityFold orders the results by the city_fold field.
func ByCityFold(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCityFold, opts...).ToFunc()
}

// ByOrgID orders the results by the org_id field.
func ByOrgID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOrgID, opts...).ToFunc()
}

// ByAka orders the results by the aka field.
func ByAka(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAka, opts...).ToFunc()
}

// ByCity orders the results by the city field.
func ByCity(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCity, opts...).ToFunc()
}

// ByCountry orders the results by the country field.
func ByCountry(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCountry, opts...).ToFunc()
}

// ByIxfLastImport orders the results by the ixf_last_import field.
func ByIxfLastImport(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIxfLastImport, opts...).ToFunc()
}

// ByIxfNetCount orders the results by the ixf_net_count field.
func ByIxfNetCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIxfNetCount, opts...).ToFunc()
}

// ByLogo orders the results by the logo field.
func ByLogo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLogo, opts...).ToFunc()
}

// ByMedia orders the results by the media field.
func ByMedia(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMedia, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByNameLong orders the results by the name_long field.
func ByNameLong(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNameLong, opts...).ToFunc()
}

// ByNotes orders the results by the notes field.
func ByNotes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNotes, opts...).ToFunc()
}

// ByPolicyEmail orders the results by the policy_email field.
func ByPolicyEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPolicyEmail, opts...).ToFunc()
}

// ByPolicyPhone orders the results by the policy_phone field.
func ByPolicyPhone(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPolicyPhone, opts...).ToFunc()
}

// ByProtoIpv6 orders the results by the proto_ipv6 field.
func ByProtoIpv6(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProtoIpv6, opts...).ToFunc()
}

// ByProtoMulticast orders the results by the proto_multicast field.
func ByProtoMulticast(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProtoMulticast, opts...).ToFunc()
}

// ByProtoUnicast orders the results by the proto_unicast field.
func ByProtoUnicast(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProtoUnicast, opts...).ToFunc()
}

// ByRegionContinent orders the results by the region_continent field.
func ByRegionContinent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRegionContinent, opts...).ToFunc()
}

// BySalesEmail orders the results by the sales_email field.
func BySalesEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSalesEmail, opts...).ToFunc()
}

// BySalesPhone orders the results by the sales_phone field.
func BySalesPhone(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSalesPhone, opts...).ToFunc()
}

// ByServiceLevel orders the results by the service_level field.
func ByServiceLevel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldServiceLevel, opts...).ToFunc()
}

// ByStatusDashboard orders the results by the status_dashboard field.
func ByStatusDashboard(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatusDashboard, opts...).ToFunc()
}

// ByTechEmail orders the results by the tech_email field.
func ByTechEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTechEmail, opts...).ToFunc()
}

// ByTechPhone orders the results by the tech_phone field.
func ByTechPhone(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTechPhone, opts...).ToFunc()
}

// ByTerms orders the results by the terms field.
func ByTerms(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTerms, opts...).ToFunc()
}

// ByURLStats orders the results by the url_stats field.
func ByURLStats(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldURLStats, opts...).ToFunc()
}

// ByWebsite orders the results by the website field.
func ByWebsite(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWebsite, opts...).ToFunc()
}

// ByNetCount orders the results by the net_count field.
func ByNetCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNetCount, opts...).ToFunc()
}

// ByFacCount orders the results by the fac_count field.
func ByFacCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFacCount, opts...).ToFunc()
}

// ByIxfImportRequest orders the results by the ixf_import_request field.
func ByIxfImportRequest(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIxfImportRequest, opts...).ToFunc()
}

// ByIxfImportRequestStatus orders the results by the ixf_import_request_status field.
func ByIxfImportRequestStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIxfImportRequestStatus, opts...).ToFunc()
}

// ByCreated orders the results by the created field.
func ByCreated(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreated, opts...).ToFunc()
}

// ByUpdated orders the results by the updated field.
func ByUpdated(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdated, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByIxFacilitiesCount orders the results by ix_facilities count.
func ByIxFacilitiesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newIxFacilitiesStep(), opts...)
	}
}

// ByIxFacilities orders the results by ix_facilities terms.
func ByIxFacilities(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newIxFacilitiesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByIxLansCount orders the results by ix_lans count.
func ByIxLansCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newIxLansStep(), opts...)
	}
}

// ByIxLans orders the results by ix_lans terms.
func ByIxLans(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newIxLansStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByOrganizationField orders the results by organization field.
func ByOrganizationField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newOrganizationStep(), sql.OrderByField(field, opts...))
	}
}
func newIxFacilitiesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(IxFacilitiesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, IxFacilitiesTable, IxFacilitiesColumn),
	)
}
func newIxLansStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(IxLansInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, IxLansTable, IxLansColumn),
	)
}
func newOrganizationStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(OrganizationInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, OrganizationTable, OrganizationColumn),
	)
}
