// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/dotwaffle/peeringdb-plus/ent/campus"
	"github.com/dotwaffle/peeringdb-plus/ent/carrierfacility"
	"github.com/dotwaffle/peeringdb-plus/ent/facility"
	"github.com/dotwaffle/peeringdb-plus/ent/ixfacility"
	"github.com/dotwaffle/peeringdb-plus/ent/networkfacility"
	"github.com/dotwaffle/peeringdb-plus/ent/organization"
	"github.com/dotwaffle/peeringdb-plus/ent/predicate"
)

// FacilityQuery is the builder for querying Facility entities.
type FacilityQuery struct {
	config
	ctx                        *QueryContext
	order                      []facility.OrderOption
	inters                     []Interceptor
	predicates                 []predicate.Facility
	withCampus                 *CampusQuery
	withCarrierFacilities      *CarrierFacilityQuery
	withIxFacilities           *IxFacilityQuery
	withNetworkFacilities      *NetworkFacilityQuery
	withOrganization           *OrganizationQuery
	modifiers                  []func(*sql.Selector)
	loadTotal                  []func(context.Context, []*Facility) error
	withNamedCarrierFacilities map[string]*CarrierFacilityQuery
	withNamedIxFacilities      map[string]*IxFacilityQuery
	withNamedNetworkFacilities map[string]*NetworkFacilityQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the FacilityQuery builder.
func (_q *FacilityQuery) Where(ps ...predicate.Facility) *FacilityQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *FacilityQuery) Limit(limit int) *FacilityQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *FacilityQuery) Offset(offset int) *FacilityQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *FacilityQuery) Unique(unique bool) *FacilityQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *FacilityQuery) Order(o ...facility.OrderOption) *FacilityQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryCampus chains the current query on the "campus" edge.
func (_q *FacilityQuery) QueryCampus() *CampusQuery {
	query := (&CampusClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(facility.Table, facility.FieldID, selector),
			sqlgraph.To(campus.Table, campus.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, facility.CampusTable, facility.CampusColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryCarrierFacilities chains the current query on the "carrier_facilities" edge.
func (_q *FacilityQuery) QueryCarrierFacilities() *CarrierFacilityQuery {
	query := (&CarrierFacilityClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(facility.Table, facility.FieldID, selector),
			sqlgraph.To(carrierfacility.Table, carrierfacility.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, facility.CarrierFacilitiesTable, facility.CarrierFacilitiesColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryIxFacilities chains the current query on the "ix_facilities" edge.
func (_q *FacilityQuery) QueryIxFacilities() *IxFacilityQuery {
	query := (&IxFacilityClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(facility.Table, facility.FieldID, selector),
			sqlgraph.To(ixfacility.Table, ixfacility.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, facility.IxFacilitiesTable, facility.IxFacilitiesColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryNetworkFacilities chains the current query on the "network_facilities" edge.
func (_q *FacilityQuery) QueryNetworkFacilities() *NetworkFacilityQuery {
	query := (&NetworkFacilityClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(facility.Table, facility.FieldID, selector),
			sqlgraph.To(networkfacility.Table, networkfacility.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, facility.NetworkFacilitiesTable, facility.NetworkFacilitiesColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryOrganization chains the current query on the "organization" edge.
func (_q *FacilityQuery) QueryOrganization() *OrganizationQuery {
	query := (&OrganizationClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(facility.Table, facility.FieldID, selector),
			sqlgraph.To(organization.Table, organization.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, facility.OrganizationTable, facility.OrganizationColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Facility entity from the query.
// Returns a *NotFoundError when no Facility was found.
func (_q *FacilityQuery) First(ctx context.Context) (*Facility, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{facility.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *FacilityQuery) FirstX(ctx context.Context) *Facility {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Facility ID from the query.
// Returns a *NotFoundError when no Facility ID was found.
func (_q *FacilityQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{facility.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *FacilityQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Facility entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Facility entity is found.
// Returns a *NotFoundError when no Facility entities are found.
func (_q *FacilityQuery) Only(ctx context.Context) (*Facility, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{facility.Label}
	default:
		return nil, &NotSingularError{facility.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *FacilityQuery) OnlyX(ctx context.Context) *Facility {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Facility ID in the query.
// Returns a *NotSingularError when more than one Facility ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *FacilityQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{facility.Label}
	default:
		err = &NotSingularError{facility.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *FacilityQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Facilities.
func (_q *FacilityQuery) All(ctx context.Context) ([]*Facility, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Facility, *FacilityQuery]()
	return withInterceptors[[]*Facility](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *FacilityQuery) AllX(ctx context.Context) []*Facility {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Facility IDs.
func (_q *FacilityQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(facility.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *FacilityQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *FacilityQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*FacilityQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *FacilityQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *FacilityQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *FacilityQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the FacilityQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *FacilityQuery) Clone() *FacilityQuery {
	if _q == nil {
		return nil
	}
	return &FacilityQuery{
		config:                _q.config,
		ctx:                   _q.ctx.Clone(),
		order:                 append([]facility.OrderOption{}, _q.order...),
		inters:                append([]Interceptor{}, _q.inters...),
		predicates:            append([]predicate.Facility{}, _q.predicates...),
		withCampus:            _q.withCampus.Clone(),
		withCarrierFacilities: _q.withCarrierFacilities.Clone(),
		withIxFacilities:      _q.withIxFacilities.Clone(),
		withNetworkFacilities: _q.withNetworkFacilities.Clone(),
		withOrganization:      _q.withOrganization.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithCampus tells the query-builder to eager-load the nodes that are connected to
// the "campus" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *FacilityQuery) WithCampus(opts ...func(*CampusQuery)) *FacilityQuery {
	query := (&CampusClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withCampus = query
	return _q
}

// WithCarrierFacilities tells the query-builder to eager-load the nodes that are connected to
// the "carrier_facilities" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *FacilityQuery) WithCarrierFacilities(opts ...func(*CarrierFacilityQuery)) *FacilityQuery {
	query := (&CarrierFacilityClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withCarrierFacilities = query
	return _q
}

// WithIxFacilities tells the query-builder to eager-load the nodes that are connected to
// the "ix_facilities" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *FacilityQuery) WithIxFacilities(opts ...func(*IxFacilityQuery)) *FacilityQuery {
	query := (&IxFacilityClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withIxFacilities = query
	return _q
}

// WithNetworkFacilities tells the query-builder to eager-load the nodes that are connected to
// the "network_facilities" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *FacilityQuery) WithNetworkFacilities(opts ...func(*NetworkFacilityQuery)) *FacilityQuery {
	query := (&NetworkFacilityClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withNetworkFacilities = query
	return _q
}

// WithOrganization tells the query-builder to eager-load the nodes that are connected to
// the "organization" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *FacilityQuery) WithOrganization(opts ...func(*OrganizationQuery)) *FacilityQuery {
	query := (&OrganizationClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withOrganization = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		NameFold string `json:"name_fold"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Facility.Query().
//		GroupBy(facility.FieldNameFold).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *FacilityQuery) GroupBy(field string, fields ...string) *FacilityGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &FacilityGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = facility.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		NameFold string `json:"name_fold"`
//	}
//
//	client.Facility.Query().
//		Select(facility.FieldNameFold).
//		Scan(ctx, &v)
func (_q *FacilityQuery) Select(fields ...string) *FacilitySelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &FacilitySelect{FacilityQuery: _q}
	sbuild.label = facility.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a FacilitySelect configured with the given aggregations.
func (_q *FacilityQuery) Aggregate(fns ...AggregateFunc) *FacilitySelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *FacilityQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !facility.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *FacilityQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Facility, error) {
	var (
		nodes       = []*Facility{}
		_spec       = _q.querySpec()
		loadedTypes = [5]bool{
			_q.withCampus != nil,
			_q.withCarrierFacilities != nil,
			_q.withIxFacilities != nil,
			_q.withNetworkFacilities != nil,
			_q.withOrganization != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Facility).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Facility{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withCampus; query != nil {
		if err := _q.loadCampus(ctx, query, nodes, nil,
			func(n *Facility, e *Campus) { n.Edges.Campus = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withCarrierFacilities; query != nil {
		if err := _q.loadCarrierFacilities(ctx, query, nodes,
			func(n *Facility) { n.Edges.CarrierFacilities = []*CarrierFacility{} },
			func(n *Facility, e *CarrierFacility) {
				n.Edges.CarrierFacilities = append(n.Edges.CarrierFacilities, e)
			}); err != nil {
			return nil, err
		}
	}
	if query := _q.withIxFacilities; query != nil {
		if err := _q.loadIxFacilities(ctx, query, nodes,
			func(n *Facility) { n.Edges.IxFacilities = []*IxFacility{} },
			func(n *Facility, e *IxFacility) { n.Edges.IxFacilities = append(n.Edges.IxFacilities, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withNetworkFacilities; query != nil {
		if err := _q.loadNetworkFacilities(ctx, query, nodes,
			func(n *Facility) { n.Edges.NetworkFacilities = []*NetworkFacility{} },
			func(n *Facility, e *NetworkFacility) {
				n.Edges.NetworkFacilities = append(n.Edges.NetworkFacilities, e)
			}); err != nil {
			return nil, err
		}
	}
	if query := _q.withOrganization; query != nil {
		if err := _q.loadOrganization(ctx, query, nodes, nil,
			func(n *Facility, e *Organization) { n.Edges.Organization = e }); err != nil {
			return nil, err
		}
	}
	for name, query := range _q.withNamedCarrierFacilities {
		if err := _q.loadCarrierFacilities(ctx, query, nodes,
			func(n *Facility) { n.appendNamedCarrierFacilities(name) },
			func(n *Facility, e *CarrierFacility) { n.appendNamedCarrierFacilities(name, e) }); err != nil {
			return nil, err
		}
	}
	for name, query := range _q.withNamedIxFacilities {
		if err := _q.loadIxFacilities(ctx, query, nodes,
			func(n *Facility) { n.appendNamedIxFacilities(name) },
			func(n *Facility, e *IxFacility) { n.appendNamedIxFacilities(name, e) }); err != nil {
			return nil, err
		}
	}
	for name, query := range _q.withNamedNetworkFacilities {
		if err := _q.loadNetworkFacilities(ctx, query, nodes,
			func(n *Facility) { n.appendNamedNetworkFacilities(name) },
			func(n *Facility, e *NetworkFacility) { n.appendNamedNetworkFacilities(name, e) }); err != nil {
			return nil, err
		}
	}
	for i := range _q.loadTotal {
		if err := _q.loadTotal[i](ctx, nodes); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *FacilityQuery) loadCampus(ctx context.Context, query *CampusQuery, nodes []*Facility, init func(*Facility), assign func(*Facility, *Campus)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*Facility)
	for i := range nodes {
		if nodes[i].CampusID == nil {
			continue
		}
		fk := *nodes[i].CampusID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(campus.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "campus_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *FacilityQuery) loadCarrierFacilities(ctx context.Context, query *CarrierFacilityQuery, nodes []*Facility, init func(*Facility), assign func(*Facility, *CarrierFacility)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Facility)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(carrierfacility.FieldFacID)
	}
	query.Where(predicate.CarrierFacility(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(facility.CarrierFacilitiesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.FacID
		if fk == nil {
			return fmt.Errorf(`foreign-key "fac_id" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "fac_id" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *FacilityQuery) loadIxFacilities(ctx context.Context, query *IxFacilityQuery, nodes []*Facility, init func(*Facility), assign func(*Facility, *IxFacility)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Facility)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(ixfacility.FieldFacID)
	}
	query.Where(predicate.IxFacility(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(facility.IxFacilitiesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.FacID
		if fk == nil {
			return fmt.Errorf(`foreign-key "fac_id" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "fac_id" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *FacilityQuery) loadNetworkFacilities(ctx context.Context, query *NetworkFacilityQuery, nodes []*Facility, init func(*Facility), assign func(*Facility, *NetworkFacility)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Facility)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(networkfacility.FieldFacID)
	}
	query.Where(predicate.NetworkFacility(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(facility.NetworkFacilitiesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.FacID
		if fk == nil {
			return fmt.Errorf(`foreign-key "fac_id" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "fac_id" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *FacilityQuery) loadOrganization(ctx context.Context, query *OrganizationQuery, nodes []*Facility, init func(*Facility), assign func(*Facility, *Organization)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*Facility)
	for i := range nodes {
		if nodes[i].OrgID == nil {
			continue
		}
		fk := *nodes[i].OrgID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(organization.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "org_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *FacilityQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *FacilityQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(facility.Table, facility.Columns, sqlgraph.NewFieldSpec(facility.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, facility.FieldID)
		for i := range fields {
			if fields[i] != facility.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withCampus != nil {
			_spec.Node.AddColumnOnce(facility.FieldCampusID)
		}
		if _q.withOrganization != nil {
			_spec.Node.AddColumnOnce(facility.FieldOrgID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *FacilityQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(facility.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = facility.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// WithNamedCarrierFacilities tells the query-builder to eager-load the nodes that are connected to the "carrier_facilities"
// edge with the given name. The optional arguments are used to configure the query builder of the edge.
func (_q *FacilityQuery) WithNamedCarrierFacilities(name string, opts ...func(*CarrierFacilityQuery)) *FacilityQuery {
	query := (&CarrierFacilityClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	if _q.withNamedCarrierFacilities == nil {
		_q.withNamedCarrierFacilities = make(map[string]*CarrierFacilityQuery)
	}
	_q.withNamedCarrierFacilities[name] = query
	return _q
}

// WithNamedIxFacilities tells the query-builder to eager-load the nodes that are connected to the "ix_facilities"
// edge with the given name. The optional arguments are used to configure the query builder of the edge.
func (_q *FacilityQuery) WithNamedIxFacilities(name string, opts ...func(*IxFacilityQuery)) *FacilityQuery {
	query := (&IxFacilityClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	if _q.withNamedIxFacilities == nil {
		_q.withNamedIxFacilities = make(map[string]*IxFacilityQuery)
	}
	_q.withNamedIxFacilities[name] = query
	return _q
}

// WithNamedNetworkFacilities tells the query-builder to eager-load the nodes that are connected to the "network_facilities"
// edge with the given name. The optional arguments are used to configure the query builder of the edge.
func (_q *FacilityQuery) WithNamedNetworkFacilities(name string, opts ...func(*NetworkFacilityQuery)) *FacilityQuery {
	query := (&NetworkFacilityClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	if _q.withNamedNetworkFacilities == nil {
		_q.withNamedNetworkFacilities = make(map[string]*NetworkFacilityQuery)
	}
	_q.withNamedNetworkFacilities[name] = query
	return _q
}

// FacilityGroupBy is the group-by builder for Facility entities.
type FacilityGroupBy struct {
	selector
	build *FacilityQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *FacilityGroupBy) Aggregate(fns ...AggregateFunc) *FacilityGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *FacilityGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*FacilityQuery, *FacilityGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *FacilityGroupBy) sqlScan(ctx context.Context, root *FacilityQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// FacilitySelect is the builder for selecting fields of Facility entities.
type FacilitySelect struct {
	*FacilityQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *FacilitySelect) Aggregate(fns ...AggregateFunc) *FacilitySelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *FacilitySelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*FacilityQuery, *FacilitySelect](ctx, _s.FacilityQuery, _s, _s.inters, v)
}

func (_s *FacilitySelect) sqlScan(ctx context.Context, root *FacilityQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
