// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/dotwaffle/peeringdb-plus/ent/internetexchange"
	"github.com/dotwaffle/peeringdb-plus/ent/ixfacility"
	"github.com/dotwaffle/peeringdb-plus/ent/ixlan"
	"github.com/dotwaffle/peeringdb-plus/ent/organization"
	"github.com/dotwaffle/peeringdb-plus/ent/predicate"
)

// InternetExchangeQuery is the builder for querying InternetExchange entities.
type InternetExchangeQuery struct {
	config
	ctx                   *QueryContext
	order                 []internetexchange.OrderOption
	inters                []Interceptor
	predicates            []predicate.InternetExchange
	withIxFacilities      *IxFacilityQuery
	withIxLans            *IxLanQuery
	withOrganization      *OrganizationQuery
	modifiers             []func(*sql.Selector)
	loadTotal             []func(context.Context, []*InternetExchange) error
	withNamedIxFacilities map[string]*IxFacilityQuery
	withNamedIxLans       map[string]*IxLanQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the InternetExchangeQuery builder.
func (_q *InternetExchangeQuery) Where(ps ...predicate.InternetExchange) *InternetExchangeQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *InternetExchangeQuery) Limit(limit int) *InternetExchangeQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *InternetExchangeQuery) Offset(offset int) *InternetExchangeQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *InternetExchangeQuery) Unique(unique bool) *InternetExchangeQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *InternetExchangeQuery) Order(o ...internetexchange.OrderOption) *InternetExchangeQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryIxFacilities chains the current query on the "ix_facilities" edge.
func (_q *InternetExchangeQuery) QueryIxFacilities() *IxFacilityQuery {
	query := (&IxFacilityClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(internetexchange.Table, internetexchange.FieldID, selector),
			sqlgraph.To(ixfacility.Table, ixfacility.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, internetexchange.IxFacilitiesTable, internetexchange.IxFacilitiesColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryIxLans chains the current query on the "ix_lans" edge.
func (_q *InternetExchangeQuery) QueryIxLans() *IxLanQuery {
	query := (&IxLanClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(internetexchange.Table, internetexchange.FieldID, selector),
			sqlgraph.To(ixlan.Table, ixlan.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, internetexchange.IxLansTable, internetexchange.IxLansColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryOrganization chains the current query on the "organization" edge.
func (_q *InternetExchangeQuery) QueryOrganization() *OrganizationQuery {
	query := (&OrganizationClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(internetexchange.Table, internetexchange.FieldID, selector),
			sqlgraph.To(organization.Table, organization.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, internetexchange.OrganizationTable, internetexchange.OrganizationColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first InternetExchange entity from the query.
// Returns a *NotFoundError when no InternetExchange was found.
func (_q *InternetExchangeQuery) First(ctx context.Context) (*InternetExchange, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{internetexchange.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *InternetExchangeQuery) FirstX(ctx context.Context) *InternetExchange {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first InternetExchange ID from the query.
// Returns a *NotFoundError when no InternetExchange ID was found.
func (_q *InternetExchangeQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{internetexchange.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *InternetExchangeQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single InternetExchange entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one InternetExchange entity is found.
// Returns a *NotFoundError when no InternetExchange entities are found.
func (_q *InternetExchangeQuery) Only(ctx context.Context) (*InternetExchange, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{internetexchange.Label}
	default:
		return nil, &NotSingularError{internetexchange.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *InternetExchangeQuery) OnlyX(ctx context.Context) *InternetExchange {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only InternetExchange ID in the query.
// Returns a *NotSingularError when more than one InternetExchange ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *InternetExchangeQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{internetexchange.Label}
	default:
		err = &NotSingularError{internetexchange.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *InternetExchangeQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of InternetExchanges.
func (_q *InternetExchangeQuery) All(ctx context.Context) ([]*InternetExchange, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*InternetExchange, *InternetExchangeQuery]()
	return withInterceptors[[]*InternetExchange](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *InternetExchangeQuery) AllX(ctx context.Context) []*InternetExchange {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of InternetExchange IDs.
func (_q *InternetExchangeQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(internetexchange.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *InternetExchangeQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *InternetExchangeQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*InternetExchangeQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *InternetExchangeQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *InternetExchangeQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *InternetExchangeQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the InternetExchangeQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *InternetExchangeQuery) Clone() *InternetExchangeQuery {
	if _q == nil {
		return nil
	}
	return &InternetExchangeQuery{
		config:           _q.config,
		ctx:              _q.ctx.Clone(),
		order:            append([]internetexchange.OrderOption{}, _q.order...),
		inters:           append([]Interceptor{}, _q.inters...),
		predicates:       append([]predicate.InternetExchange{}, _q.predicates...),
		withIxFacilities: _q.withIxFacilities.Clone(),
		withIxLans:       _q.withIxLans.Clone(),
		withOrganization: _q.withOrganization.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithIxFacilities tells the query-builder to eager-load the nodes that are connected to
// the "ix_facilities" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *InternetExchangeQuery) WithIxFacilities(opts ...func(*IxFacilityQuery)) *InternetExchangeQuery {
	query := (&IxFacilityClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withIxFacilities = query
	return _q
}

// WithIxLans tells the query-builder to eager-load the nodes that are connected to
// the "ix_lans" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *InternetExchangeQuery) WithIxLans(opts ...func(*IxLanQuery)) *InternetExchangeQuery {
	query := (&IxLanClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withIxLans = query
	return _q
}

// WithOrganization tells the query-builder to eager-load the nodes that are connected to
// the "organization" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *InternetExchangeQuery) WithOrganization(opts ...func(*OrganizationQuery)) *InternetExchangeQuery {
	query := (&OrganizationClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withOrganization = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		OrgID int `json:"org_id"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.InternetExchange.Query().
//		GroupBy(internetexchange.FieldOrgID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *InternetExchangeQuery) GroupBy(field string, fields ...string) *InternetExchangeGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &InternetExchangeGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = internetexchange.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		OrgID int `json:"org_id"`
//	}
//
//	client.InternetExchange.Query().
//		Select(internetexchange.FieldOrgID).
//		Scan(ctx, &v)
func (_q *InternetExchangeQuery) Select(fields ...string) *InternetExchangeSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &InternetExchangeSelect{InternetExchangeQuery: _q}
	sbuild.label = internetexchange.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a InternetExchangeSelect configured with the given aggregations.
func (_q *InternetExchangeQuery) Aggregate(fns ...AggregateFunc) *InternetExchangeSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *InternetExchangeQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !internetexchange.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *InternetExchangeQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*InternetExchange, error) {
	var (
		nodes       = []*InternetExchange{}
		_spec       = _q.querySpec()
		loadedTypes = [3]bool{
			_q.withIxFacilities != nil,
			_q.withIxLans != nil,
			_q.withOrganization != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*InternetExchange).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &InternetExchange{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withIxFacilities; query != nil {
		if err := _q.loadIxFacilities(ctx, query, nodes,
			func(n *InternetExchange) { n.Edges.IxFacilities = []*IxFacility{} },
			func(n *InternetExchange, e *IxFacility) { n.Edges.IxFacilities = append(n.Edges.IxFacilities, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withIxLans; query != nil {
		if err := _q.loadIxLans(ctx, query, nodes,
			func(n *InternetExchange) { n.Edges.IxLans = []*IxLan{} },
			func(n *InternetExchange, e *IxLan) { n.Edges.IxLans = append(n.Edges.IxLans, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withOrganization; query != nil {
		if err := _q.loadOrganization(ctx, query, nodes, nil,
			func(n *InternetExchange, e *Organization) { n.Edges.Organization = e }); err != nil {
			return nil, err
		}
	}
	for name, query := range _q.withNamedIxFacilities {
		if err := _q.loadIxFacilities(ctx, query, nodes,
			func(n *InternetExchange) { n.appendNamedIxFacilities(name) },
			func(n *InternetExchange, e *IxFacility) { n.appendNamedIxFacilities(name, e) }); err != nil {
			return nil, err
		}
	}
	for name, query := range _q.withNamedIxLans {
		if err := _q.loadIxLans(ctx, query, nodes,
			func(n *InternetExchange) { n.appendNamedIxLans(name) },
			func(n *InternetExchange, e *IxLan) { n.appendNamedIxLans(name, e) }); err != nil {
			return nil, err
		}
	}
	for i := range _q.loadTotal {
		if err := _q.loadTotal[i](ctx, nodes); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *InternetExchangeQuery) loadIxFacilities(ctx context.Context, query *IxFacilityQuery, nodes []*InternetExchange, init func(*InternetExchange), assign func(*InternetExchange, *IxFacility)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*InternetExchange)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(ixfacility.FieldIxID)
	}
	query.Where(predicate.IxFacility(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(internetexchange.IxFacilitiesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.IxID
		if fk == nil {
			return fmt.Errorf(`foreign-key "ix_id" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "ix_id" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *InternetExchangeQuery) loadIxLans(ctx context.Context, query *IxLanQuery, nodes []*InternetExchange, init func(*InternetExchange), assign func(*InternetExchange, *IxLan)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*InternetExchange)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(ixlan.FieldIxID)
	}
	query.Where(predicate.IxLan(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(internetexchange.IxLansColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.IxID
		if fk == nil {
			return fmt.Errorf(`foreign-key "ix_id" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "ix_id" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *InternetExchangeQuery) loadOrganization(ctx context.Context, query *OrganizationQuery, nodes []*InternetExchange, init func(*InternetExchange), assign func(*InternetExchange, *Organization)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*InternetExchange)
	for i := range nodes {
		if nodes[i].OrgID == nil {
			continue
		}
		fk := *nodes[i].OrgID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(organization.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "org_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *InternetExchangeQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *InternetExchangeQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(internetexchange.Table, internetexchange.Columns, sqlgraph.NewFieldSpec(internetexchange.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, internetexchange.FieldID)
		for i := range fields {
			if fields[i] != internetexchange.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withOrganization != nil {
			_spec.Node.AddColumnOnce(internetexchange.FieldOrgID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *InternetExchangeQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(internetexchange.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = internetexchange.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// WithNamedIxFacilities tells the query-builder to eager-load the nodes that are connected to the "ix_facilities"
// edge with the given name. The optional arguments are used to configure the query builder of the edge.
func (_q *InternetExchangeQuery) WithNamedIxFacilities(name string, opts ...func(*IxFacilityQuery)) *InternetExchangeQuery {
	query := (&IxFacilityClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	if _q.withNamedIxFacilities == nil {
		_q.withNamedIxFacilities = make(map[string]*IxFacilityQuery)
	}
	_q.withNamedIxFacilities[name] = query
	return _q
}

// WithNamedIxLans tells the query-builder to eager-load the nodes that are connected to the "ix_lans"
// edge with the given name. The optional arguments are used to configure the query builder of the edge.
func (_q *InternetExchangeQuery) WithNamedIxLans(name string, opts ...func(*IxLanQuery)) *InternetExchangeQuery {
	query := (&IxLanClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	if _q.withNamedIxLans == nil {
		_q.withNamedIxLans = make(map[string]*IxLanQuery)
	}
	_q.withNamedIxLans[name] = query
	return _q
}

// InternetExchangeGroupBy is the group-by builder for InternetExchange entities.
type InternetExchangeGroupBy struct {
	selector
	build *InternetExchangeQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *InternetExchangeGroupBy) Aggregate(fns ...AggregateFunc) *InternetExchangeGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *InternetExchangeGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*InternetExchangeQuery, *InternetExchangeGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *InternetExchangeGroupBy) sqlScan(ctx context.Context, root *InternetExchangeQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// InternetExchangeSelect is the builder for selecting fields of InternetExchange entities.
type InternetExchangeSelect struct {
	*InternetExchangeQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *InternetExchangeSelect) Aggregate(fns ...AggregateFunc) *InternetExchangeSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *InternetExchangeSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*InternetExchangeQuery, *InternetExchangeSelect](ctx, _s.InternetExchangeQuery, _s, _s.inters, v)
}

func (_s *InternetExchangeSelect) sqlScan(ctx context.Context, root *InternetExchangeQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
