// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/dotwaffle/peeringdb-plus/ent/facility"
	"github.com/dotwaffle/peeringdb-plus/ent/internetexchange"
	"github.com/dotwaffle/peeringdb-plus/ent/ixfacility"
	"github.com/dotwaffle/peeringdb-plus/ent/predicate"
)

// IxFacilityUpdate is the builder for updating IxFacility entities.
type IxFacilityUpdate struct {
	config
	hooks    []Hook
	mutation *IxFacilityMutation
}

// Where appends a list predicates to the IxFacilityUpdate builder.
func (_u *IxFacilityUpdate) Where(ps ...predicate.IxFacility) *IxFacilityUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetIxID sets the "ix_id" field.
func (_u *IxFacilityUpdate) SetIxID(v int) *IxFacilityUpdate {
	_u.mutation.SetIxID(v)
	return _u
}

// SetNillableIxID sets the "ix_id" field if the given value is not nil.
func (_u *IxFacilityUpdate) SetNillableIxID(v *int) *IxFacilityUpdate {
	if v != nil {
		_u.SetIxID(*v)
	}
	return _u
}

// ClearIxID clears the value of the "ix_id" field.
func (_u *IxFacilityUpdate) ClearIxID() *IxFacilityUpdate {
	_u.mutation.ClearIxID()
	return _u
}

// SetFacID sets the "fac_id" field.
func (_u *IxFacilityUpdate) SetFacID(v int) *IxFacilityUpdate {
	_u.mutation.SetFacID(v)
	return _u
}

// SetNillableFacID sets the "fac_id" field if the given value is not nil.
func (_u *IxFacilityUpdate) SetNillableFacID(v *int) *IxFacilityUpdate {
	if v != nil {
		_u.SetFacID(*v)
	}
	return _u
}

// ClearFacID clears the value of the "fac_id" field.
func (_u *IxFacilityUpdate) ClearFacID() *IxFacilityUpdate {
	_u.mutation.ClearFacID()
	return _u
}

// SetName sets the "name" field.
func (_u *IxFacilityUpdate) SetName(v string) *IxFacilityUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *IxFacilityUpdate) SetNillableName(v *string) *IxFacilityUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// ClearName clears the value of the "name" field.
func (_u *IxFacilityUpdate) ClearName() *IxFacilityUpdate {
	_u.mutation.ClearName()
	return _u
}

// SetCity sets the "city" field.
func (_u *IxFacilityUpdate) SetCity(v string) *IxFacilityUpdate {
	_u.mutation.SetCity(v)
	return _u
}

// SetNillableCity sets the "city" field if the given value is not nil.
func (_u *IxFacilityUpdate) SetNillableCity(v *string) *IxFacilityUpdate {
	if v != nil {
		_u.SetCity(*v)
	}
	return _u
}

// ClearCity clears the value of the "city" field.
func (_u *IxFacilityUpdate) ClearCity() *IxFacilityUpdate {
	_u.mutation.ClearCity()
	return _u
}

// SetCountry sets the "country" field.
func (_u *IxFacilityUpdate) SetCountry(v string) *IxFacilityUpdate {
	_u.mutation.SetCountry(v)
	return _u
}

// SetNillableCountry sets the "country" field if the given value is not nil.
func (_u *IxFacilityUpdate) SetNillableCountry(v *string) *IxFacilityUpdate {
	if v != nil {
		_u.SetCountry(*v)
	}
	return _u
}

// ClearCountry clears the value of the "country" field.
func (_u *IxFacilityUpdate) ClearCountry() *IxFacilityUpdate {
	_u.mutation.ClearCountry()
	return _u
}

// SetUpdated sets the "updated" field.
func (_u *IxFacilityUpdate) SetUpdated(v time.Time) *IxFacilityUpdate {
	_u.mutation.SetUpdated(v)
	return _u
}

// SetNillableUpdated sets the "updated" field if the given value is not nil.
func (_u *IxFacilityUpdate) SetNillableUpdated(v *time.Time) *IxFacilityUpdate {
	if v != nil {
		_u.SetUpdated(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *IxFacilityUpdate) SetStatus(v string) *IxFacilityUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *IxFacilityUpdate) SetNillableStatus(v *string) *IxFacilityUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetInternetExchangeID sets the "internet_exchange" edge to the InternetExchange entity by ID.
func (_u *IxFacilityUpdate) SetInternetExchangeID(id int) *IxFacilityUpdate {
	_u.mutation.SetInternetExchangeID(id)
	return _u
}

// SetNillableInternetExchangeID sets the "internet_exchange" edge to the InternetExchange entity by ID if the given value is not nil.
func (_u *IxFacilityUpdate) SetNillableInternetExchangeID(id *int) *IxFacilityUpdate {
	if id != nil {
		_u = _u.SetInternetExchangeID(*id)
	}
	return _u
}

// SetInternetExchange sets the "internet_exchange" edge to the InternetExchange entity.
func (_u *IxFacilityUpdate) SetInternetExchange(v *InternetExchange) *IxFacilityUpdate {
	return _u.SetInternetExchangeID(v.ID)
}

// SetFacilityID sets the "facility" edge to the Facility entity by ID.
func (_u *IxFacilityUpdate) SetFacilityID(id int) *IxFacilityUpdate {
	_u.mutation.SetFacilityID(id)
	return _u
}

// SetNillableFacilityID sets the "facility" edge to the Facility entity by ID if the given value is not nil.
func (_u *IxFacilityUpdate) SetNillableFacilityID(id *int) *IxFacilityUpdate {
	if id != nil {
		_u = _u.SetFacilityID(*id)
	}
	return _u
}

// SetFacility sets the "facility" edge to the Facility entity.
func (_u *IxFacilityUpdate) SetFacility(v *Facility) *IxFacilityUpdate {
	return _u.SetFacilityID(v.ID)
}

// Mutation returns the IxFacilityMutation object of the builder.
func (_u *IxFacilityUpdate) Mutation() *IxFacilityMutation {
	return _u.mutation
}

// ClearInternetExchange clears the "internet_exchange" edge to the InternetExchange entity.
func (_u *IxFacilityUpdate) ClearInternetExchange() *IxFacilityUpdate {
	_u.mutation.ClearInternetExchange()
	return _u
}

// ClearFacility clears the "facility" edge to the Facility entity.
func (_u *IxFacilityUpdate) ClearFacility() *IxFacilityUpdate {
	_u.mutation.ClearFacility()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *IxFacilityUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *IxFacilityUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *IxFacilityUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *IxFacilityUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *IxFacilityUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := ixfacility.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "IxFacility.status": %w`, err)}
		}
	}
	return nil
}

func (_u *IxFacilityUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(ixfacility.Table, ixfacility.Columns, sqlgraph.NewFieldSpec(ixfacility.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(ixfacility.FieldName, field.TypeString, value)
	}
	if _u.mutation.NameCleared() {
		_spec.ClearField(ixfacility.FieldName, field.TypeString)
	}
	if value, ok := _u.mutation.City(); ok {
		_spec.SetField(ixfacility.FieldCity, field.TypeString, value)
	}
	if _u.mutation.CityCleared() {
		_spec.ClearField(ixfacility.FieldCity, field.TypeString)
	}
	if value, ok := _u.mutation.Country(); ok {
		_spec.SetField(ixfacility.FieldCountry, field.TypeString, value)
	}
	if _u.mutation.CountryCleared() {
		_spec.ClearField(ixfacility.FieldCountry, field.TypeString)
	}
	if value, ok := _u.mutation.Updated(); ok {
		_spec.SetField(ixfacility.FieldUpdated, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(ixfacility.FieldStatus, field.TypeString, value)
	}
	if _u.mutation.InternetExchangeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ixfacility.InternetExchangeTable,
			Columns: []string{ixfacility.InternetExchangeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(internetexchange.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.InternetExchangeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ixfacility.InternetExchangeTable,
			Columns: []string{ixfacility.InternetExchangeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(internetexchange.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.FacilityCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ixfacility.FacilityTable,
			Columns: []string{ixfacility.FacilityColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(facility.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FacilityIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ixfacility.FacilityTable,
			Columns: []string{ixfacility.FacilityColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(facility.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ixfacility.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// IxFacilityUpdateOne is the builder for updating a single IxFacility entity.
type IxFacilityUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *IxFacilityMutation
}

// SetIxID sets the "ix_id" field.
func (_u *IxFacilityUpdateOne) SetIxID(v int) *IxFacilityUpdateOne {
	_u.mutation.SetIxID(v)
	return _u
}

// SetNillableIxID sets the "ix_id" field if the given value is not nil.
func (_u *IxFacilityUpdateOne) SetNillableIxID(v *int) *IxFacilityUpdateOne {
	if v != nil {
		_u.SetIxID(*v)
	}
	return _u
}

// ClearIxID clears the value of the "ix_id" field.
func (_u *IxFacilityUpdateOne) ClearIxID() *IxFacilityUpdateOne {
	_u.mutation.ClearIxID()
	return _u
}

// SetFacID sets the "fac_id" field.
func (_u *IxFacilityUpdateOne) SetFacID(v int) *IxFacilityUpdateOne {
	_u.mutation.SetFacID(v)
	return _u
}

// SetNillableFacID sets the "fac_id" field if the given value is not nil.
func (_u *IxFacilityUpdateOne) SetNillableFacID(v *int) *IxFacilityUpdateOne {
	if v != nil {
		_u.SetFacID(*v)
	}
	return _u
}

// ClearFacID clears the value of the "fac_id" field.
func (_u *IxFacilityUpdateOne) ClearFacID() *IxFacilityUpdateOne {
	_u.mutation.ClearFacID()
	return _u
}

// SetName sets the "name" field.
func (_u *IxFacilityUpdateOne) SetName(v string) *IxFacilityUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *IxFacilityUpdateOne) SetNillableName(v *string) *IxFacilityUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// ClearName clears the value of the "name" field.
func (_u *IxFacilityUpdateOne) ClearName() *IxFacilityUpdateOne {
	_u.mutation.ClearName()
	return _u
}

// SetCity sets the "city" field.
func (_u *IxFacilityUpdateOne) SetCity(v string) *IxFacilityUpdateOne {
	_u.mutation.SetCity(v)
	return _u
}

// SetNillableCity sets the "city" field if the given value is not nil.
func (_u *IxFacilityUpdateOne) SetNillableCity(v *string) *IxFacilityUpdateOne {
	if v != nil {
		_u.SetCity(*v)
	}
	return _u
}

// ClearCity clears the value of the "city" field.
func (_u *IxFacilityUpdateOne) ClearCity() *IxFacilityUpdateOne {
	_u.mutation.ClearCity()
	return _u
}

// SetCountry sets the "country" field.
func (_u *IxFacilityUpdateOne) SetCountry(v string) *IxFacilityUpdateOne {
	_u.mutation.SetCountry(v)
	return _u
}

// SetNillableCountry sets the "country" field if the given value is not nil.
func (_u *IxFacilityUpdateOne) SetNillableCountry(v *string) *IxFacilityUpdateOne {
	if v != nil {
		_u.SetCountry(*v)
	}
	return _u
}

// ClearCountry clears the value of the "country" field.
func (_u *IxFacilityUpdateOne) ClearCountry() *IxFacilityUpdateOne {
	_u.mutation.ClearCountry()
	return _u
}

// SetUpdated sets the "updated" field.
func (_u *IxFacilityUpdateOne) SetUpdated(v time.Time) *IxFacilityUpdateOne {
	_u.mutation.SetUpdated(v)
	return _u
}

// SetNillableUpdated sets the "updated" field if the given value is not nil.
func (_u *IxFacilityUpdateOne) SetNillableUpdated(v *time.Time) *IxFacilityUpdateOne {
	if v != nil {
		_u.SetUpdated(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *IxFacilityUpdateOne) SetStatus(v string) *IxFacilityUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *IxFacilityUpdateOne) SetNillableStatus(v *string) *IxFacilityUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetInternetExchangeID sets the "internet_exchange" edge to the InternetExchange entity by ID.
func (_u *IxFacilityUpdateOne) SetInternetExchangeID(id int) *IxFacilityUpdateOne {
	_u.mutation.SetInternetExchangeID(id)
	return _u
}

// SetNillableInternetExchangeID sets the "internet_exchange" edge to the InternetExchange entity by ID if the given value is not nil.
func (_u *IxFacilityUpdateOne) SetNillableInternetExchangeID(id *int) *IxFacilityUpdateOne {
	if id != nil {
		_u = _u.SetInternetExchangeID(*id)
	}
	return _u
}

// SetInternetExchange sets the "internet_exchange" edge to the InternetExchange entity.
func (_u *IxFacilityUpdateOne) SetInternetExchange(v *InternetExchange) *IxFacilityUpdateOne {
	return _u.SetInternetExchangeID(v.ID)
}

// SetFacilityID sets the "facility" edge to the Facility entity by ID.
func (_u *IxFacilityUpdateOne) SetFacilityID(id int) *IxFacilityUpdateOne {
	_u.mutation.SetFacilityID(id)
	return _u
}

// SetNillableFacilityID sets the "facility" edge to the Facility entity by ID if the given value is not nil.
func (_u *IxFacilityUpdateOne) SetNillableFacilityID(id *int) *IxFacilityUpdateOne {
	if id != nil {
		_u = _u.SetFacilityID(*id)
	}
	return _u
}

// SetFacility sets the "facility" edge to the Facility entity.
func (_u *IxFacilityUpdateOne) SetFacility(v *Facility) *IxFacilityUpdateOne {
	return _u.SetFacilityID(v.ID)
}

// Mutation returns the IxFacilityMutation object of the builder.
func (_u *IxFacilityUpdateOne) Mutation() *IxFacilityMutation {
	return _u.mutation
}

// ClearInternetExchange clears the "internet_exchange" edge to the InternetExchange entity.
func (_u *IxFacilityUpdateOne) ClearInternetExchange() *IxFacilityUpdateOne {
	_u.mutation.ClearInternetExchange()
	return _u
}

// ClearFacility clears the "facility" edge to the Facility entity.
func (_u *IxFacilityUpdateOne) ClearFacility() *IxFacilityUpdateOne {
	_u.mutation.ClearFacility()
	return _u
}

// Where appends a list predicates to the IxFacilityUpdate builder.
func (_u *IxFacilityUpdateOne) Where(ps ...predicate.IxFacility) *IxFacilityUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *IxFacilityUpdateOne) Select(field string, fields ...string) *IxFacilityUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated IxFacility entity.
func (_u *IxFacilityUpdateOne) Save(ctx context.Context) (*IxFacility, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *IxFacilityUpdateOne) SaveX(ctx context.Context) *IxFacility {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *IxFacilityUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *IxFacilityUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *IxFacilityUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := ixfacility.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "IxFacility.status": %w`, err)}
		}
	}
	return nil
}

func (_u *IxFacilityUpdateOne) sqlSave(ctx context.Context) (_node *IxFacility, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(ixfacility.Table, ixfacility.Columns, sqlgraph.NewFieldSpec(ixfacility.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "IxFacility.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, ixfacility.FieldID)
		for _, f := range fields {
			if !ixfacility.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != ixfacility.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(ixfacility.FieldName, field.TypeString, value)
	}
	if _u.mutation.NameCleared() {
		_spec.ClearField(ixfacility.FieldName, field.TypeString)
	}
	if value, ok := _u.mutation.City(); ok {
		_spec.SetField(ixfacility.FieldCity, field.TypeString, value)
	}
	if _u.mutation.CityCleared() {
		_spec.ClearField(ixfacility.FieldCity, field.TypeString)
	}
	if value, ok := _u.mutation.Country(); ok {
		_spec.SetField(ixfacility.FieldCountry, field.TypeString, value)
	}
	if _u.mutation.CountryCleared() {
		_spec.ClearField(ixfacility.FieldCountry, field.TypeString)
	}
	if value, ok := _u.mutation.Updated(); ok {
		_spec.SetField(ixfacility.FieldUpdated, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(ixfacility.FieldStatus, field.TypeString, value)
	}
	if _u.mutation.InternetExchangeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ixfacility.InternetExchangeTable,
			Columns: []string{ixfacility.InternetExchangeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(internetexchange.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.InternetExchangeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ixfacility.InternetExchangeTable,
			Columns: []string{ixfacility.InternetExchangeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(internetexchange.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.FacilityCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ixfacility.FacilityTable,
			Columns: []string{ixfacility.FacilityColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(facility.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FacilityIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ixfacility.FacilityTable,
			Columns: []string{ixfacility.FacilityColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(facility.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &IxFacility{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ixfacility.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
