// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/dotwaffle/peeringdb-plus/ent/facility"
	"github.com/dotwaffle/peeringdb-plus/ent/internetexchange"
	"github.com/dotwaffle/peeringdb-plus/ent/ixfacility"
)

// IxFacilityCreate is the builder for creating a IxFacility entity.
type IxFacilityCreate struct {
	config
	mutation *IxFacilityMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetFacID sets the "fac_id" field.
func (_c *IxFacilityCreate) SetFacID(v int) *IxFacilityCreate {
	_c.mutation.SetFacID(v)
	return _c
}

// SetNillableFacID sets the "fac_id" field if the given value is not nil.
func (_c *IxFacilityCreate) SetNillableFacID(v *int) *IxFacilityCreate {
	if v != nil {
		_c.SetFacID(*v)
	}
	return _c
}

// SetIxID sets the "ix_id" field.
func (_c *IxFacilityCreate) SetIxID(v int) *IxFacilityCreate {
	_c.mutation.SetIxID(v)
	return _c
}

// SetNillableIxID sets the "ix_id" field if the given value is not nil.
func (_c *IxFacilityCreate) SetNillableIxID(v *int) *IxFacilityCreate {
	if v != nil {
		_c.SetIxID(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *IxFacilityCreate) SetName(v string) *IxFacilityCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_c *IxFacilityCreate) SetNillableName(v *string) *IxFacilityCreate {
	if v != nil {
		_c.SetName(*v)
	}
	return _c
}

// SetCity sets the "city" field.
func (_c *IxFacilityCreate) SetCity(v string) *IxFacilityCreate {
	_c.mutation.SetCity(v)
	return _c
}

// SetNillableCity sets the "city" field if the given value is not nil.
func (_c *IxFacilityCreate) SetNillableCity(v *string) *IxFacilityCreate {
	if v != nil {
		_c.SetCity(*v)
	}
	return _c
}

// SetCountry sets the "country" field.
func (_c *IxFacilityCreate) SetCountry(v string) *IxFacilityCreate {
	_c.mutation.SetCountry(v)
	return _c
}

// SetNillableCountry sets the "country" field if the given value is not nil.
func (_c *IxFacilityCreate) SetNillableCountry(v *string) *IxFacilityCreate {
	if v != nil {
		_c.SetCountry(*v)
	}
	return _c
}

// SetCreated sets the "created" field.
func (_c *IxFacilityCreate) SetCreated(v time.Time) *IxFacilityCreate {
	_c.mutation.SetCreated(v)
	return _c
}

// SetUpdated sets the "updated" field.
func (_c *IxFacilityCreate) SetUpdated(v time.Time) *IxFacilityCreate {
	_c.mutation.SetUpdated(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *IxFacilityCreate) SetStatus(v string) *IxFacilityCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *IxFacilityCreate) SetNillableStatus(v *string) *IxFacilityCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *IxFacilityCreate) SetID(v int) *IxFacilityCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetFacilityID sets the "facility" edge to the Facility entity by ID.
func (_c *IxFacilityCreate) SetFacilityID(id int) *IxFacilityCreate {
	_c.mutation.SetFacilityID(id)
	return _c
}

// SetNillableFacilityID sets the "facility" edge to the Facility entity by ID if the given value is not nil.
func (_c *IxFacilityCreate) SetNillableFacilityID(id *int) *IxFacilityCreate {
	if id != nil {
		_c = _c.SetFacilityID(*id)
	}
	return _c
}

// SetFacility sets the "facility" edge to the Facility entity.
func (_c *IxFacilityCreate) SetFacility(v *Facility) *IxFacilityCreate {
	return _c.SetFacilityID(v.ID)
}

// SetInternetExchangeID sets the "internet_exchange" edge to the InternetExchange entity by ID.
func (_c *IxFacilityCreate) SetInternetExchangeID(id int) *IxFacilityCreate {
	_c.mutation.SetInternetExchangeID(id)
	return _c
}

// SetNillableInternetExchangeID sets the "internet_exchange" edge to the InternetExchange entity by ID if the given value is not nil.
func (_c *IxFacilityCreate) SetNillableInternetExchangeID(id *int) *IxFacilityCreate {
	if id != nil {
		_c = _c.SetInternetExchangeID(*id)
	}
	return _c
}

// SetInternetExchange sets the "internet_exchange" edge to the InternetExchange entity.
func (_c *IxFacilityCreate) SetInternetExchange(v *InternetExchange) *IxFacilityCreate {
	return _c.SetInternetExchangeID(v.ID)
}

// Mutation returns the IxFacilityMutation object of the builder.
func (_c *IxFacilityCreate) Mutation() *IxFacilityMutation {
	return _c.mutation
}

// Save creates the IxFacility in the database.
func (_c *IxFacilityCreate) Save(ctx context.Context) (*IxFacility, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *IxFacilityCreate) SaveX(ctx context.Context) *IxFacility {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *IxFacilityCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *IxFacilityCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *IxFacilityCreate) defaults() error {
	if _, ok := _c.mutation.Name(); !ok {
		v := ixfacility.DefaultName
		_c.mutation.SetName(v)
	}
	if _, ok := _c.mutation.City(); !ok {
		v := ixfacility.DefaultCity
		_c.mutation.SetCity(v)
	}
	if _, ok := _c.mutation.Country(); !ok {
		v := ixfacility.DefaultCountry
		_c.mutation.SetCountry(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := ixfacility.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *IxFacilityCreate) check() error {
	if _, ok := _c.mutation.Created(); !ok {
		return &ValidationError{Name: "created", err: errors.New(`ent: missing required field "IxFacility.created"`)}
	}
	if _, ok := _c.mutation.Updated(); !ok {
		return &ValidationError{Name: "updated", err: errors.New(`ent: missing required field "IxFacility.updated"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "IxFacility.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := ixfacility.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "IxFacility.status": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := ixfacility.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "IxFacility.id": %w`, err)}
		}
	}
	return nil
}

func (_c *IxFacilityCreate) sqlSave(ctx context.Context) (*IxFacility, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *IxFacilityCreate) createSpec() (*IxFacility, *sqlgraph.CreateSpec) {
	var (
		_node = &IxFacility{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(ixfacility.Table, sqlgraph.NewFieldSpec(ixfacility.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(ixfacility.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.City(); ok {
		_spec.SetField(ixfacility.FieldCity, field.TypeString, value)
		_node.City = value
	}
	if value, ok := _c.mutation.Country(); ok {
		_spec.SetField(ixfacility.FieldCountry, field.TypeString, value)
		_node.Country = value
	}
	if value, ok := _c.mutation.Created(); ok {
		_spec.SetField(ixfacility.FieldCreated, field.TypeTime, value)
		_node.Created = value
	}
	if value, ok := _c.mutation.Updated(); ok {
		_spec.SetField(ixfacility.FieldUpdated, field.TypeTime, value)
		_node.Updated = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(ixfacility.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if nodes := _c.mutation.FacilityIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ixfacility.FacilityTable,
			Columns: []string{ixfacility.FacilityColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(facility.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.FacID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.InternetExchangeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ixfacility.InternetExchangeTable,
			Columns: []string{ixfacility.InternetExchangeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(internetexchange.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.IxID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.IxFacility.Create().
//		SetFacID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.IxFacilityUpsert) {
//			SetFacID(v+v).
//		}).
//		Exec(ctx)
func (_c *IxFacilityCreate) OnConflict(opts ...sql.ConflictOption) *IxFacilityUpsertOne {
	_c.conflict = opts
	return &IxFacilityUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.IxFacility.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *IxFacilityCreate) OnConflictColumns(columns ...string) *IxFacilityUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &IxFacilityUpsertOne{
		create: _c,
	}
}

type (
	// IxFacilityUpsertOne is the builder for "upsert"-ing
	//  one IxFacility node.
	IxFacilityUpsertOne struct {
		create *IxFacilityCreate
	}

	// IxFacilityUpsert is the "OnConflict" setter.
	IxFacilityUpsert struct {
		*sql.UpdateSet
	}
)

// SetFacID sets the "fac_id" field.
func (u *IxFacilityUpsert) SetFacID(v int) *IxFacilityUpsert {
	u.Set(ixfacility.FieldFacID, v)
	return u
}

// UpdateFacID sets the "fac_id" field to the value that was provided on create.
func (u *IxFacilityUpsert) UpdateFacID() *IxFacilityUpsert {
	u.SetExcluded(ixfacility.FieldFacID)
	return u
}

// ClearFacID clears the value of the "fac_id" field.
func (u *IxFacilityUpsert) ClearFacID() *IxFacilityUpsert {
	u.SetNull(ixfacility.FieldFacID)
	return u
}

// SetIxID sets the "ix_id" field.
func (u *IxFacilityUpsert) SetIxID(v int) *IxFacilityUpsert {
	u.Set(ixfacility.FieldIxID, v)
	return u
}

// UpdateIxID sets the "ix_id" field to the value that was provided on create.
func (u *IxFacilityUpsert) UpdateIxID() *IxFacilityUpsert {
	u.SetExcluded(ixfacility.FieldIxID)
	return u
}

// ClearIxID clears the value of the "ix_id" field.
func (u *IxFacilityUpsert) ClearIxID() *IxFacilityUpsert {
	u.SetNull(ixfacility.FieldIxID)
	return u
}

// SetName sets the "name" field.
func (u *IxFacilityUpsert) SetName(v string) *IxFacilityUpsert {
	u.Set(ixfacility.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *IxFacilityUpsert) UpdateName() *IxFacilityUpsert {
	u.SetExcluded(ixfacility.FieldName)
	return u
}

// ClearName clears the value of the "name" field.
func (u *IxFacilityUpsert) ClearName() *IxFacilityUpsert {
	u.SetNull(ixfacility.FieldName)
	return u
}

// SetCity sets the "city" field.
func (u *IxFacilityUpsert) SetCity(v string) *IxFacilityUpsert {
	u.Set(ixfacility.FieldCity, v)
	return u
}

// UpdateCity sets the "city" field to the value that was provided on create.
func (u *IxFacilityUpsert) UpdateCity() *IxFacilityUpsert {
	u.SetExcluded(ixfacility.FieldCity)
	return u
}

// ClearCity clears the value of the "city" field.
func (u *IxFacilityUpsert) ClearCity() *IxFacilityUpsert {
	u.SetNull(ixfacility.FieldCity)
	return u
}

// SetCountry sets the "country" field.
func (u *IxFacilityUpsert) SetCountry(v string) *IxFacilityUpsert {
	u.Set(ixfacility.FieldCountry, v)
	return u
}

// UpdateCountry sets the "country" field to the value that was provided on create.
func (u *IxFacilityUpsert) UpdateCountry() *IxFacilityUpsert {
	u.SetExcluded(ixfacility.FieldCountry)
	return u
}

// ClearCountry clears the value of the "country" field.
func (u *IxFacilityUpsert) ClearCountry() *IxFacilityUpsert {
	u.SetNull(ixfacility.FieldCountry)
	return u
}

// SetUpdated sets the "updated" field.
func (u *IxFacilityUpsert) SetUpdated(v time.Time) *IxFacilityUpsert {
	u.Set(ixfacility.FieldUpdated, v)
	return u
}

// UpdateUpdated sets the "updated" field to the value that was provided on create.
func (u *IxFacilityUpsert) UpdateUpdated() *IxFacilityUpsert {
	u.SetExcluded(ixfacility.FieldUpdated)
	return u
}

// SetStatus sets the "status" field.
func (u *IxFacilityUpsert) SetStatus(v string) *IxFacilityUpsert {
	u.Set(ixfacility.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *IxFacilityUpsert) UpdateStatus() *IxFacilityUpsert {
	u.SetExcluded(ixfacility.FieldStatus)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.IxFacility.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(ixfacility.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *IxFacilityUpsertOne) UpdateNewValues() *IxFacilityUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(ixfacility.FieldID)
		}
		if _, exists := u.create.mutation.Created(); exists {
			s.SetIgnore(ixfacility.FieldCreated)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.IxFacility.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *IxFacilityUpsertOne) Ignore() *IxFacilityUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *IxFacilityUpsertOne) DoNothing() *IxFacilityUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the IxFacilityCreate.OnConflict
// documentation for more info.
func (u *IxFacilityUpsertOne) Update(set func(*IxFacilityUpsert)) *IxFacilityUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&IxFacilityUpsert{UpdateSet: update})
	}))
	return u
}

// SetFacID sets the "fac_id" field.
func (u *IxFacilityUpsertOne) SetFacID(v int) *IxFacilityUpsertOne {
	return u.Update(func(s *IxFacilityUpsert) {
		s.SetFacID(v)
	})
}

// UpdateFacID sets the "fac_id" field to the value that was provided on create.
func (u *IxFacilityUpsertOne) UpdateFacID() *IxFacilityUpsertOne {
	return u.Update(func(s *IxFacilityUpsert) {
		s.UpdateFacID()
	})
}

// ClearFacID clears the value of the "fac_id" field.
func (u *IxFacilityUpsertOne) ClearFacID() *IxFacilityUpsertOne {
	return u.Update(func(s *IxFacilityUpsert) {
		s.ClearFacID()
	})
}

// SetIxID sets the "ix_id" field.
func (u *IxFacilityUpsertOne) SetIxID(v int) *IxFacilityUpsertOne {
	return u.Update(func(s *IxFacilityUpsert) {
		s.SetIxID(v)
	})
}

// UpdateIxID sets the "ix_id" field to the value that was provided on create.
func (u *IxFacilityUpsertOne) UpdateIxID() *IxFacilityUpsertOne {
	return u.Update(func(s *IxFacilityUpsert) {
		s.UpdateIxID()
	})
}

// ClearIxID clears the value of the "ix_id" field.
func (u *IxFacilityUpsertOne) ClearIxID() *IxFacilityUpsertOne {
	return u.Update(func(s *IxFacilityUpsert) {
		s.ClearIxID()
	})
}

// SetName sets the "name" field.
func (u *IxFacilityUpsertOne) SetName(v string) *IxFacilityUpsertOne {
	return u.Update(func(s *IxFacilityUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *IxFacilityUpsertOne) UpdateName() *IxFacilityUpsertOne {
	return u.Update(func(s *IxFacilityUpsert) {
		s.UpdateName()
	})
}

// ClearName clears the value of the "name" field.
func (u *IxFacilityUpsertOne) ClearName() *IxFacilityUpsertOne {
	return u.Update(func(s *IxFacilityUpsert) {
		s.ClearName()
	})
}

// SetCity sets the "city" field.
func (u *IxFacilityUpsertOne) SetCity(v string) *IxFacilityUpsertOne {
	return u.Update(func(s *IxFacilityUpsert) {
		s.SetCity(v)
	})
}

// UpdateCity sets the "city" field to the value that was provided on create.
func (u *IxFacilityUpsertOne) UpdateCity() *IxFacilityUpsertOne {
	return u.Update(func(s *IxFacilityUpsert) {
		s.UpdateCity()
	})
}

// ClearCity clears the value of the "city" field.
func (u *IxFacilityUpsertOne) ClearCity() *IxFacilityUpsertOne {
	return u.Update(func(s *IxFacilityUpsert) {
		s.ClearCity()
	})
}

// SetCountry sets the "country" field.
func (u *IxFacilityUpsertOne) SetCountry(v string) *IxFacilityUpsertOne {
	return u.Update(func(s *IxFacilityUpsert) {
		s.SetCountry(v)
	})
}

// UpdateCountry sets the "country" field to the value that was provided on create.
func (u *IxFacilityUpsertOne) UpdateCountry() *IxFacilityUpsertOne {
	return u.Update(func(s *IxFacilityUpsert) {
		s.UpdateCountry()
	})
}

// ClearCountry clears the value of the "country" field.
func (u *IxFacilityUpsertOne) ClearCountry() *IxFacilityUpsertOne {
	return u.Update(func(s *IxFacilityUpsert) {
		s.ClearCountry()
	})
}

// SetUpdated sets the "updated" field.
func (u *IxFacilityUpsertOne) SetUpdated(v time.Time) *IxFacilityUpsertOne {
	return u.Update(func(s *IxFacilityUpsert) {
		s.SetUpdated(v)
	})
}

// UpdateUpdated sets the "updated" field to the value that was provided on create.
func (u *IxFacilityUpsertOne) UpdateUpdated() *IxFacilityUpsertOne {
	return u.Update(func(s *IxFacilityUpsert) {
		s.UpdateUpdated()
	})
}

// SetStatus sets the "status" field.
func (u *IxFacilityUpsertOne) SetStatus(v string) *IxFacilityUpsertOne {
	return u.Update(func(s *IxFacilityUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *IxFacilityUpsertOne) UpdateStatus() *IxFacilityUpsertOne {
	return u.Update(func(s *IxFacilityUpsert) {
		s.UpdateStatus()
	})
}

// Exec executes the query.
func (u *IxFacilityUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for IxFacilityCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *IxFacilityUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *IxFacilityUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *IxFacilityUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// IxFacilityCreateBulk is the builder for creating many IxFacility entities in bulk.
type IxFacilityCreateBulk struct {
	config
	err      error
	builders []*IxFacilityCreate
	conflict []sql.ConflictOption
}

// Save creates the IxFacility entities in the database.
func (_c *IxFacilityCreateBulk) Save(ctx context.Context) ([]*IxFacility, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*IxFacility, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*IxFacilityMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *IxFacilityCreateBulk) SaveX(ctx context.Context) []*IxFacility {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *IxFacilityCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *IxFacilityCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.IxFacility.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.IxFacilityUpsert) {
//			SetFacID(v+v).
//		}).
//		Exec(ctx)
func (_c *IxFacilityCreateBulk) OnConflict(opts ...sql.ConflictOption) *IxFacilityUpsertBulk {
	_c.conflict = opts
	return &IxFacilityUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.IxFacility.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *IxFacilityCreateBulk) OnConflictColumns(columns ...string) *IxFacilityUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &IxFacilityUpsertBulk{
		create: _c,
	}
}

// IxFacilityUpsertBulk is the builder for "upsert"-ing
// a bulk of IxFacility nodes.
type IxFacilityUpsertBulk struct {
	create *IxFacilityCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.IxFacility.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(ixfacility.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *IxFacilityUpsertBulk) UpdateNewValues() *IxFacilityUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(ixfacility.FieldID)
			}
			if _, exists := b.mutation.Created(); exists {
				s.SetIgnore(ixfacility.FieldCreated)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.IxFacility.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *IxFacilityUpsertBulk) Ignore() *IxFacilityUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *IxFacilityUpsertBulk) DoNothing() *IxFacilityUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the IxFacilityCreateBulk.OnConflict
// documentation for more info.
func (u *IxFacilityUpsertBulk) Update(set func(*IxFacilityUpsert)) *IxFacilityUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&IxFacilityUpsert{UpdateSet: update})
	}))
	return u
}

// SetFacID sets the "fac_id" field.
func (u *IxFacilityUpsertBulk) SetFacID(v int) *IxFacilityUpsertBulk {
	return u.Update(func(s *IxFacilityUpsert) {
		s.SetFacID(v)
	})
}

// UpdateFacID sets the "fac_id" field to the value that was provided on create.
func (u *IxFacilityUpsertBulk) UpdateFacID() *IxFacilityUpsertBulk {
	return u.Update(func(s *IxFacilityUpsert) {
		s.UpdateFacID()
	})
}

// ClearFacID clears the value of the "fac_id" field.
func (u *IxFacilityUpsertBulk) ClearFacID() *IxFacilityUpsertBulk {
	return u.Update(func(s *IxFacilityUpsert) {
		s.ClearFacID()
	})
}

// SetIxID sets the "ix_id" field.
func (u *IxFacilityUpsertBulk) SetIxID(v int) *IxFacilityUpsertBulk {
	return u.Update(func(s *IxFacilityUpsert) {
		s.SetIxID(v)
	})
}

// UpdateIxID sets the "ix_id" field to the value that was provided on create.
func (u *IxFacilityUpsertBulk) UpdateIxID() *IxFacilityUpsertBulk {
	return u.Update(func(s *IxFacilityUpsert) {
		s.UpdateIxID()
	})
}

// ClearIxID clears the value of the "ix_id" field.
func (u *IxFacilityUpsertBulk) ClearIxID() *IxFacilityUpsertBulk {
	return u.Update(func(s *IxFacilityUpsert) {
		s.ClearIxID()
	})
}

// SetName sets the "name" field.
func (u *IxFacilityUpsertBulk) SetName(v string) *IxFacilityUpsertBulk {
	return u.Update(func(s *IxFacilityUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *IxFacilityUpsertBulk) UpdateName() *IxFacilityUpsertBulk {
	return u.Update(func(s *IxFacilityUpsert) {
		s.UpdateName()
	})
}

// ClearName clears the value of the "name" field.
func (u *IxFacilityUpsertBulk) ClearName() *IxFacilityUpsertBulk {
	return u.Update(func(s *IxFacilityUpsert) {
		s.ClearName()
	})
}

// SetCity sets the "city" field.
func (u *IxFacilityUpsertBulk) SetCity(v string) *IxFacilityUpsertBulk {
	return u.Update(func(s *IxFacilityUpsert) {
		s.SetCity(v)
	})
}

// UpdateCity sets the "city" field to the value that was provided on create.
func (u *IxFacilityUpsertBulk) UpdateCity() *IxFacilityUpsertBulk {
	return u.Update(func(s *IxFacilityUpsert) {
		s.UpdateCity()
	})
}

// ClearCity clears the value of the "city" field.
func (u *IxFacilityUpsertBulk) ClearCity() *IxFacilityUpsertBulk {
	return u.Update(func(s *IxFacilityUpsert) {
		s.ClearCity()
	})
}

// SetCountry sets the "country" field.
func (u *IxFacilityUpsertBulk) SetCountry(v string) *IxFacilityUpsertBulk {
	return u.Update(func(s *IxFacilityUpsert) {
		s.SetCountry(v)
	})
}

// UpdateCountry sets the "country" field to the value that was provided on create.
func (u *IxFacilityUpsertBulk) UpdateCountry() *IxFacilityUpsertBulk {
	return u.Update(func(s *IxFacilityUpsert) {
		s.UpdateCountry()
	})
}

// ClearCountry clears the value of the "country" field.
func (u *IxFacilityUpsertBulk) ClearCountry() *IxFacilityUpsertBulk {
	return u.Update(func(s *IxFacilityUpsert) {
		s.ClearCountry()
	})
}

// SetUpdated sets the "updated" field.
func (u *IxFacilityUpsertBulk) SetUpdated(v time.Time) *IxFacilityUpsertBulk {
	return u.Update(func(s *IxFacilityUpsert) {
		s.SetUpdated(v)
	})
}

// UpdateUpdated sets the "updated" field to the value that was provided on create.
func (u *IxFacilityUpsertBulk) UpdateUpdated() *IxFacilityUpsertBulk {
	return u.Update(func(s *IxFacilityUpsert) {
		s.UpdateUpdated()
	})
}

// SetStatus sets the "status" field.
func (u *IxFacilityUpsertBulk) SetStatus(v string) *IxFacilityUpsertBulk {
	return u.Update(func(s *IxFacilityUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *IxFacilityUpsertBulk) UpdateStatus() *IxFacilityUpsertBulk {
	return u.Update(func(s *IxFacilityUpsert) {
		s.UpdateStatus()
	})
}

// Exec executes the query.
func (u *IxFacilityUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the IxFacilityCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for IxFacilityCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *IxFacilityUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
