// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/dotwaffle/peeringdb-plus/ent/ixlan"
	"github.com/dotwaffle/peeringdb-plus/ent/network"
	"github.com/dotwaffle/peeringdb-plus/ent/networkixlan"
)

// NetworkIxLanCreate is the builder for creating a NetworkIxLan entity.
type NetworkIxLanCreate struct {
	config
	mutation *NetworkIxLanMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetIxSideID sets the "ix_side_id" field.
func (_c *NetworkIxLanCreate) SetIxSideID(v int) *NetworkIxLanCreate {
	_c.mutation.SetIxSideID(v)
	return _c
}

// SetNillableIxSideID sets the "ix_side_id" field if the given value is not nil.
func (_c *NetworkIxLanCreate) SetNillableIxSideID(v *int) *NetworkIxLanCreate {
	if v != nil {
		_c.SetIxSideID(*v)
	}
	return _c
}

// SetIxlanID sets the "ixlan_id" field.
func (_c *NetworkIxLanCreate) SetIxlanID(v int) *NetworkIxLanCreate {
	_c.mutation.SetIxlanID(v)
	return _c
}

// SetNillableIxlanID sets the "ixlan_id" field if the given value is not nil.
func (_c *NetworkIxLanCreate) SetNillableIxlanID(v *int) *NetworkIxLanCreate {
	if v != nil {
		_c.SetIxlanID(*v)
	}
	return _c
}

// SetNetID sets the "net_id" field.
func (_c *NetworkIxLanCreate) SetNetID(v int) *NetworkIxLanCreate {
	_c.mutation.SetNetID(v)
	return _c
}

// SetNillableNetID sets the "net_id" field if the given value is not nil.
func (_c *NetworkIxLanCreate) SetNillableNetID(v *int) *NetworkIxLanCreate {
	if v != nil {
		_c.SetNetID(*v)
	}
	return _c
}

// SetNetSideID sets the "net_side_id" field.
func (_c *NetworkIxLanCreate) SetNetSideID(v int) *NetworkIxLanCreate {
	_c.mutation.SetNetSideID(v)
	return _c
}

// SetNillableNetSideID sets the "net_side_id" field if the given value is not nil.
func (_c *NetworkIxLanCreate) SetNillableNetSideID(v *int) *NetworkIxLanCreate {
	if v != nil {
		_c.SetNetSideID(*v)
	}
	return _c
}

// SetAsn sets the "asn" field.
func (_c *NetworkIxLanCreate) SetAsn(v int) *NetworkIxLanCreate {
	_c.mutation.SetAsn(v)
	return _c
}

// SetBfdSupport sets the "bfd_support" field.
func (_c *NetworkIxLanCreate) SetBfdSupport(v bool) *NetworkIxLanCreate {
	_c.mutation.SetBfdSupport(v)
	return _c
}

// SetNillableBfdSupport sets the "bfd_support" field if the given value is not nil.
func (_c *NetworkIxLanCreate) SetNillableBfdSupport(v *bool) *NetworkIxLanCreate {
	if v != nil {
		_c.SetBfdSupport(*v)
	}
	return _c
}

// SetIpaddr4 sets the "ipaddr4" field.
func (_c *NetworkIxLanCreate) SetIpaddr4(v string) *NetworkIxLanCreate {
	_c.mutation.SetIpaddr4(v)
	return _c
}

// SetNillableIpaddr4 sets the "ipaddr4" field if the given value is not nil.
func (_c *NetworkIxLanCreate) SetNillableIpaddr4(v *string) *NetworkIxLanCreate {
	if v != nil {
		_c.SetIpaddr4(*v)
	}
	return _c
}

// SetIpaddr6 sets the "ipaddr6" field.
func (_c *NetworkIxLanCreate) SetIpaddr6(v string) *NetworkIxLanCreate {
	_c.mutation.SetIpaddr6(v)
	return _c
}

// SetNillableIpaddr6 sets the "ipaddr6" field if the given value is not nil.
func (_c *NetworkIxLanCreate) SetNillableIpaddr6(v *string) *NetworkIxLanCreate {
	if v != nil {
		_c.SetIpaddr6(*v)
	}
	return _c
}

// SetIsRsPeer sets the "is_rs_peer" field.
func (_c *NetworkIxLanCreate) SetIsRsPeer(v bool) *NetworkIxLanCreate {
	_c.mutation.SetIsRsPeer(v)
	return _c
}

// SetNillableIsRsPeer sets the "is_rs_peer" field if the given value is not nil.
func (_c *NetworkIxLanCreate) SetNillableIsRsPeer(v *bool) *NetworkIxLanCreate {
	if v != nil {
		_c.SetIsRsPeer(*v)
	}
	return _c
}

// SetNotes sets the "notes" field.
func (_c *NetworkIxLanCreate) SetNotes(v string) *NetworkIxLanCreate {
	_c.mutation.SetNotes(v)
	return _c
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_c *NetworkIxLanCreate) SetNillableNotes(v *string) *NetworkIxLanCreate {
	if v != nil {
		_c.SetNotes(*v)
	}
	return _c
}

// SetOperational sets the "operational" field.
func (_c *NetworkIxLanCreate) SetOperational(v bool) *NetworkIxLanCreate {
	_c.mutation.SetOperational(v)
	return _c
}

// SetNillableOperational sets the "operational" field if the given value is not nil.
func (_c *NetworkIxLanCreate) SetNillableOperational(v *bool) *NetworkIxLanCreate {
	if v != nil {
		_c.SetOperational(*v)
	}
	return _c
}

// SetSpeed sets the "speed" field.
func (_c *NetworkIxLanCreate) SetSpeed(v int) *NetworkIxLanCreate {
	_c.mutation.SetSpeed(v)
	return _c
}

// SetIxID sets the "ix_id" field.
func (_c *NetworkIxLanCreate) SetIxID(v int) *NetworkIxLanCreate {
	_c.mutation.SetIxID(v)
	return _c
}

// SetNillableIxID sets the "ix_id" field if the given value is not nil.
func (_c *NetworkIxLanCreate) SetNillableIxID(v *int) *NetworkIxLanCreate {
	if v != nil {
		_c.SetIxID(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *NetworkIxLanCreate) SetName(v string) *NetworkIxLanCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_c *NetworkIxLanCreate) SetNillableName(v *string) *NetworkIxLanCreate {
	if v != nil {
		_c.SetName(*v)
	}
	return _c
}

// SetCreated sets the "created" field.
func (_c *NetworkIxLanCreate) SetCreated(v time.Time) *NetworkIxLanCreate {
	_c.mutation.SetCreated(v)
	return _c
}

// SetUpdated sets the "updated" field.
func (_c *NetworkIxLanCreate) SetUpdated(v time.Time) *NetworkIxLanCreate {
	_c.mutation.SetUpdated(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *NetworkIxLanCreate) SetStatus(v string) *NetworkIxLanCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *NetworkIxLanCreate) SetNillableStatus(v *string) *NetworkIxLanCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *NetworkIxLanCreate) SetID(v int) *NetworkIxLanCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetIxLanID sets the "ix_lan" edge to the IxLan entity by ID.
func (_c *NetworkIxLanCreate) SetIxLanID(id int) *NetworkIxLanCreate {
	_c.mutation.SetIxLanID(id)
	return _c
}

// SetNillableIxLanID sets the "ix_lan" edge to the IxLan entity by ID if the given value is not nil.
func (_c *NetworkIxLanCreate) SetNillableIxLanID(id *int) *NetworkIxLanCreate {
	if id != nil {
		_c = _c.SetIxLanID(*id)
	}
	return _c
}

// SetIxLan sets the "ix_lan" edge to the IxLan entity.
func (_c *NetworkIxLanCreate) SetIxLan(v *IxLan) *NetworkIxLanCreate {
	return _c.SetIxLanID(v.ID)
}

// SetNetworkID sets the "network" edge to the Network entity by ID.
func (_c *NetworkIxLanCreate) SetNetworkID(id int) *NetworkIxLanCreate {
	_c.mutation.SetNetworkID(id)
	return _c
}

// SetNillableNetworkID sets the "network" edge to the Network entity by ID if the given value is not nil.
func (_c *NetworkIxLanCreate) SetNillableNetworkID(id *int) *NetworkIxLanCreate {
	if id != nil {
		_c = _c.SetNetworkID(*id)
	}
	return _c
}

// SetNetwork sets the "network" edge to the Network entity.
func (_c *NetworkIxLanCreate) SetNetwork(v *Network) *NetworkIxLanCreate {
	return _c.SetNetworkID(v.ID)
}

// Mutation returns the NetworkIxLanMutation object of the builder.
func (_c *NetworkIxLanCreate) Mutation() *NetworkIxLanMutation {
	return _c.mutation
}

// Save creates the NetworkIxLan in the database.
func (_c *NetworkIxLanCreate) Save(ctx context.Context) (*NetworkIxLan, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *NetworkIxLanCreate) SaveX(ctx context.Context) *NetworkIxLan {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NetworkIxLanCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NetworkIxLanCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *NetworkIxLanCreate) defaults() error {
	if _, ok := _c.mutation.BfdSupport(); !ok {
		v := networkixlan.DefaultBfdSupport
		_c.mutation.SetBfdSupport(v)
	}
	if _, ok := _c.mutation.IsRsPeer(); !ok {
		v := networkixlan.DefaultIsRsPeer
		_c.mutation.SetIsRsPeer(v)
	}
	if _, ok := _c.mutation.Notes(); !ok {
		v := networkixlan.DefaultNotes
		_c.mutation.SetNotes(v)
	}
	if _, ok := _c.mutation.Operational(); !ok {
		v := networkixlan.DefaultOperational
		_c.mutation.SetOperational(v)
	}
	if _, ok := _c.mutation.Name(); !ok {
		v := networkixlan.DefaultName
		_c.mutation.SetName(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := networkixlan.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *NetworkIxLanCreate) check() error {
	if _, ok := _c.mutation.Asn(); !ok {
		return &ValidationError{Name: "asn", err: errors.New(`ent: missing required field "NetworkIxLan.asn"`)}
	}
	if v, ok := _c.mutation.Asn(); ok {
		if err := networkixlan.AsnValidator(v); err != nil {
			return &ValidationError{Name: "asn", err: fmt.Errorf(`ent: validator failed for field "NetworkIxLan.asn": %w`, err)}
		}
	}
	if _, ok := _c.mutation.BfdSupport(); !ok {
		return &ValidationError{Name: "bfd_support", err: errors.New(`ent: missing required field "NetworkIxLan.bfd_support"`)}
	}
	if _, ok := _c.mutation.IsRsPeer(); !ok {
		return &ValidationError{Name: "is_rs_peer", err: errors.New(`ent: missing required field "NetworkIxLan.is_rs_peer"`)}
	}
	if _, ok := _c.mutation.Operational(); !ok {
		return &ValidationError{Name: "operational", err: errors.New(`ent: missing required field "NetworkIxLan.operational"`)}
	}
	if _, ok := _c.mutation.Speed(); !ok {
		return &ValidationError{Name: "speed", err: errors.New(`ent: missing required field "NetworkIxLan.speed"`)}
	}
	if _, ok := _c.mutation.Created(); !ok {
		return &ValidationError{Name: "created", err: errors.New(`ent: missing required field "NetworkIxLan.created"`)}
	}
	if _, ok := _c.mutation.Updated(); !ok {
		return &ValidationError{Name: "updated", err: errors.New(`ent: missing required field "NetworkIxLan.updated"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "NetworkIxLan.status"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := networkixlan.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "NetworkIxLan.id": %w`, err)}
		}
	}
	return nil
}

func (_c *NetworkIxLanCreate) sqlSave(ctx context.Context) (*NetworkIxLan, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *NetworkIxLanCreate) createSpec() (*NetworkIxLan, *sqlgraph.CreateSpec) {
	var (
		_node = &NetworkIxLan{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(networkixlan.Table, sqlgraph.NewFieldSpec(networkixlan.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.IxSideID(); ok {
		_spec.SetField(networkixlan.FieldIxSideID, field.TypeInt, value)
		_node.IxSideID = &value
	}
	if value, ok := _c.mutation.NetSideID(); ok {
		_spec.SetField(networkixlan.FieldNetSideID, field.TypeInt, value)
		_node.NetSideID = &value
	}
	if value, ok := _c.mutation.Asn(); ok {
		_spec.SetField(networkixlan.FieldAsn, field.TypeInt, value)
		_node.Asn = value
	}
	if value, ok := _c.mutation.BfdSupport(); ok {
		_spec.SetField(networkixlan.FieldBfdSupport, field.TypeBool, value)
		_node.BfdSupport = value
	}
	if value, ok := _c.mutation.Ipaddr4(); ok {
		_spec.SetField(networkixlan.FieldIpaddr4, field.TypeString, value)
		_node.Ipaddr4 = &value
	}
	if value, ok := _c.mutation.Ipaddr6(); ok {
		_spec.SetField(networkixlan.FieldIpaddr6, field.TypeString, value)
		_node.Ipaddr6 = &value
	}
	if value, ok := _c.mutation.IsRsPeer(); ok {
		_spec.SetField(networkixlan.FieldIsRsPeer, field.TypeBool, value)
		_node.IsRsPeer = value
	}
	if value, ok := _c.mutation.Notes(); ok {
		_spec.SetField(networkixlan.FieldNotes, field.TypeString, value)
		_node.Notes = value
	}
	if value, ok := _c.mutation.Operational(); ok {
		_spec.SetField(networkixlan.FieldOperational, field.TypeBool, value)
		_node.Operational = value
	}
	if value, ok := _c.mutation.Speed(); ok {
		_spec.SetField(networkixlan.FieldSpeed, field.TypeInt, value)
		_node.Speed = value
	}
	if value, ok := _c.mutation.IxID(); ok {
		_spec.SetField(networkixlan.FieldIxID, field.TypeInt, value)
		_node.IxID = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(networkixlan.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Created(); ok {
		_spec.SetField(networkixlan.FieldCreated, field.TypeTime, value)
		_node.Created = value
	}
	if value, ok := _c.mutation.Updated(); ok {
		_spec.SetField(networkixlan.FieldUpdated, field.TypeTime, value)
		_node.Updated = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(networkixlan.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if nodes := _c.mutation.IxLanIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   networkixlan.IxLanTable,
			Columns: []string{networkixlan.IxLanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ixlan.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.IxlanID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.NetworkIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   networkixlan.NetworkTable,
			Columns: []string{networkixlan.NetworkColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(network.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.NetID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.NetworkIxLan.Create().
//		SetIxSideID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.NetworkIxLanUpsert) {
//			SetIxSideID(v+v).
//		}).
//		Exec(ctx)
func (_c *NetworkIxLanCreate) OnConflict(opts ...sql.ConflictOption) *NetworkIxLanUpsertOne {
	_c.conflict = opts
	return &NetworkIxLanUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.NetworkIxLan.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *NetworkIxLanCreate) OnConflictColumns(columns ...string) *NetworkIxLanUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &NetworkIxLanUpsertOne{
		create: _c,
	}
}

type (
	// NetworkIxLanUpsertOne is the builder for "upsert"-ing
	//  one NetworkIxLan node.
	NetworkIxLanUpsertOne struct {
		create *NetworkIxLanCreate
	}

	// NetworkIxLanUpsert is the "OnConflict" setter.
	NetworkIxLanUpsert struct {
		*sql.UpdateSet
	}
)

// SetIxSideID sets the "ix_side_id" field.
func (u *NetworkIxLanUpsert) SetIxSideID(v int) *NetworkIxLanUpsert {
	u.Set(networkixlan.FieldIxSideID, v)
	return u
}

// UpdateIxSideID sets the "ix_side_id" field to the value that was provided on create.
func (u *NetworkIxLanUpsert) UpdateIxSideID() *NetworkIxLanUpsert {
	u.SetExcluded(networkixlan.FieldIxSideID)
	return u
}

// AddIxSideID adds v to the "ix_side_id" field.
func (u *NetworkIxLanUpsert) AddIxSideID(v int) *NetworkIxLanUpsert {
	u.Add(networkixlan.FieldIxSideID, v)
	return u
}

// ClearIxSideID clears the value of the "ix_side_id" field.
func (u *NetworkIxLanUpsert) ClearIxSideID() *NetworkIxLanUpsert {
	u.SetNull(networkixlan.FieldIxSideID)
	return u
}

// SetIxlanID sets the "ixlan_id" field.
func (u *NetworkIxLanUpsert) SetIxlanID(v int) *NetworkIxLanUpsert {
	u.Set(networkixlan.FieldIxlanID, v)
	return u
}

// UpdateIxlanID sets the "ixlan_id" field to the value that was provided on create.
func (u *NetworkIxLanUpsert) UpdateIxlanID() *NetworkIxLanUpsert {
	u.SetExcluded(networkixlan.FieldIxlanID)
	return u
}

// ClearIxlanID clears the value of the "ixlan_id" field.
func (u *NetworkIxLanUpsert) ClearIxlanID() *NetworkIxLanUpsert {
	u.SetNull(networkixlan.FieldIxlanID)
	return u
}

// SetNetID sets the "net_id" field.
func (u *NetworkIxLanUpsert) SetNetID(v int) *NetworkIxLanUpsert {
	u.Set(networkixlan.FieldNetID, v)
	return u
}

// UpdateNetID sets the "net_id" field to the value that was provided on create.
func (u *NetworkIxLanUpsert) UpdateNetID() *NetworkIxLanUpsert {
	u.SetExcluded(networkixlan.FieldNetID)
	return u
}

// ClearNetID clears the value of the "net_id" field.
func (u *NetworkIxLanUpsert) ClearNetID() *NetworkIxLanUpsert {
	u.SetNull(networkixlan.FieldNetID)
	return u
}

// SetNetSideID sets the "net_side_id" field.
func (u *NetworkIxLanUpsert) SetNetSideID(v int) *NetworkIxLanUpsert {
	u.Set(networkixlan.FieldNetSideID, v)
	return u
}

// UpdateNetSideID sets the "net_side_id" field to the value that was provided on create.
func (u *NetworkIxLanUpsert) UpdateNetSideID() *NetworkIxLanUpsert {
	u.SetExcluded(networkixlan.FieldNetSideID)
	return u
}

// AddNetSideID adds v to the "net_side_id" field.
func (u *NetworkIxLanUpsert) AddNetSideID(v int) *NetworkIxLanUpsert {
	u.Add(networkixlan.FieldNetSideID, v)
	return u
}

// ClearNetSideID clears the value of the "net_side_id" field.
func (u *NetworkIxLanUpsert) ClearNetSideID() *NetworkIxLanUpsert {
	u.SetNull(networkixlan.FieldNetSideID)
	return u
}

// SetAsn sets the "asn" field.
func (u *NetworkIxLanUpsert) SetAsn(v int) *NetworkIxLanUpsert {
	u.Set(networkixlan.FieldAsn, v)
	return u
}

// UpdateAsn sets the "asn" field to the value that was provided on create.
func (u *NetworkIxLanUpsert) UpdateAsn() *NetworkIxLanUpsert {
	u.SetExcluded(networkixlan.FieldAsn)
	return u
}

// AddAsn adds v to the "asn" field.
func (u *NetworkIxLanUpsert) AddAsn(v int) *NetworkIxLanUpsert {
	u.Add(networkixlan.FieldAsn, v)
	return u
}

// SetBfdSupport sets the "bfd_support" field.
func (u *NetworkIxLanUpsert) SetBfdSupport(v bool) *NetworkIxLanUpsert {
	u.Set(networkixlan.FieldBfdSupport, v)
	return u
}

// UpdateBfdSupport sets the "bfd_support" field to the value that was provided on create.
func (u *NetworkIxLanUpsert) UpdateBfdSupport() *NetworkIxLanUpsert {
	u.SetExcluded(networkixlan.FieldBfdSupport)
	return u
}

// SetIpaddr4 sets the "ipaddr4" field.
func (u *NetworkIxLanUpsert) SetIpaddr4(v string) *NetworkIxLanUpsert {
	u.Set(networkixlan.FieldIpaddr4, v)
	return u
}

// UpdateIpaddr4 sets the "ipaddr4" field to the value that was provided on create.
func (u *NetworkIxLanUpsert) UpdateIpaddr4() *NetworkIxLanUpsert {
	u.SetExcluded(networkixlan.FieldIpaddr4)
	return u
}

// ClearIpaddr4 clears the value of the "ipaddr4" field.
func (u *NetworkIxLanUpsert) ClearIpaddr4() *NetworkIxLanUpsert {
	u.SetNull(networkixlan.FieldIpaddr4)
	return u
}

// SetIpaddr6 sets the "ipaddr6" field.
func (u *NetworkIxLanUpsert) SetIpaddr6(v string) *NetworkIxLanUpsert {
	u.Set(networkixlan.FieldIpaddr6, v)
	return u
}

// UpdateIpaddr6 sets the "ipaddr6" field to the value that was provided on create.
func (u *NetworkIxLanUpsert) UpdateIpaddr6() *NetworkIxLanUpsert {
	u.SetExcluded(networkixlan.FieldIpaddr6)
	return u
}

// ClearIpaddr6 clears the value of the "ipaddr6" field.
func (u *NetworkIxLanUpsert) ClearIpaddr6() *NetworkIxLanUpsert {
	u.SetNull(networkixlan.FieldIpaddr6)
	return u
}

// SetIsRsPeer sets the "is_rs_peer" field.
func (u *NetworkIxLanUpsert) SetIsRsPeer(v bool) *NetworkIxLanUpsert {
	u.Set(networkixlan.FieldIsRsPeer, v)
	return u
}

// UpdateIsRsPeer sets the "is_rs_peer" field to the value that was provided on create.
func (u *NetworkIxLanUpsert) UpdateIsRsPeer() *NetworkIxLanUpsert {
	u.SetExcluded(networkixlan.FieldIsRsPeer)
	return u
}

// SetNotes sets the "notes" field.
func (u *NetworkIxLanUpsert) SetNotes(v string) *NetworkIxLanUpsert {
	u.Set(networkixlan.FieldNotes, v)
	return u
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *NetworkIxLanUpsert) UpdateNotes() *NetworkIxLanUpsert {
	u.SetExcluded(networkixlan.FieldNotes)
	return u
}

// ClearNotes clears the value of the "notes" field.
func (u *NetworkIxLanUpsert) ClearNotes() *NetworkIxLanUpsert {
	u.SetNull(networkixlan.FieldNotes)
	return u
}

// SetOperational sets the "operational" field.
func (u *NetworkIxLanUpsert) SetOperational(v bool) *NetworkIxLanUpsert {
	u.Set(networkixlan.FieldOperational, v)
	return u
}

// UpdateOperational sets the "operational" field to the value that was provided on create.
func (u *NetworkIxLanUpsert) UpdateOperational() *NetworkIxLanUpsert {
	u.SetExcluded(networkixlan.FieldOperational)
	return u
}

// SetSpeed sets the "speed" field.
func (u *NetworkIxLanUpsert) SetSpeed(v int) *NetworkIxLanUpsert {
	u.Set(networkixlan.FieldSpeed, v)
	return u
}

// UpdateSpeed sets the "speed" field to the value that was provided on create.
func (u *NetworkIxLanUpsert) UpdateSpeed() *NetworkIxLanUpsert {
	u.SetExcluded(networkixlan.FieldSpeed)
	return u
}

// AddSpeed adds v to the "speed" field.
func (u *NetworkIxLanUpsert) AddSpeed(v int) *NetworkIxLanUpsert {
	u.Add(networkixlan.FieldSpeed, v)
	return u
}

// SetIxID sets the "ix_id" field.
func (u *NetworkIxLanUpsert) SetIxID(v int) *NetworkIxLanUpsert {
	u.Set(networkixlan.FieldIxID, v)
	return u
}

// UpdateIxID sets the "ix_id" field to the value that was provided on create.
func (u *NetworkIxLanUpsert) UpdateIxID() *NetworkIxLanUpsert {
	u.SetExcluded(networkixlan.FieldIxID)
	return u
}

// AddIxID adds v to the "ix_id" field.
func (u *NetworkIxLanUpsert) AddIxID(v int) *NetworkIxLanUpsert {
	u.Add(networkixlan.FieldIxID, v)
	return u
}

// ClearIxID clears the value of the "ix_id" field.
func (u *NetworkIxLanUpsert) ClearIxID() *NetworkIxLanUpsert {
	u.SetNull(networkixlan.FieldIxID)
	return u
}

// SetName sets the "name" field.
func (u *NetworkIxLanUpsert) SetName(v string) *NetworkIxLanUpsert {
	u.Set(networkixlan.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *NetworkIxLanUpsert) UpdateName() *NetworkIxLanUpsert {
	u.SetExcluded(networkixlan.FieldName)
	return u
}

// ClearName clears the value of the "name" field.
func (u *NetworkIxLanUpsert) ClearName() *NetworkIxLanUpsert {
	u.SetNull(networkixlan.FieldName)
	return u
}

// SetUpdated sets the "updated" field.
func (u *NetworkIxLanUpsert) SetUpdated(v time.Time) *NetworkIxLanUpsert {
	u.Set(networkixlan.FieldUpdated, v)
	return u
}

// UpdateUpdated sets the "updated" field to the value that was provided on create.
func (u *NetworkIxLanUpsert) UpdateUpdated() *NetworkIxLanUpsert {
	u.SetExcluded(networkixlan.FieldUpdated)
	return u
}

// SetStatus sets the "status" field.
func (u *NetworkIxLanUpsert) SetStatus(v string) *NetworkIxLanUpsert {
	u.Set(networkixlan.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *NetworkIxLanUpsert) UpdateStatus() *NetworkIxLanUpsert {
	u.SetExcluded(networkixlan.FieldStatus)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.NetworkIxLan.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(networkixlan.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *NetworkIxLanUpsertOne) UpdateNewValues() *NetworkIxLanUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(networkixlan.FieldID)
		}
		if _, exists := u.create.mutation.Created(); exists {
			s.SetIgnore(networkixlan.FieldCreated)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.NetworkIxLan.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *NetworkIxLanUpsertOne) Ignore() *NetworkIxLanUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *NetworkIxLanUpsertOne) DoNothing() *NetworkIxLanUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the NetworkIxLanCreate.OnConflict
// documentation for more info.
func (u *NetworkIxLanUpsertOne) Update(set func(*NetworkIxLanUpsert)) *NetworkIxLanUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&NetworkIxLanUpsert{UpdateSet: update})
	}))
	return u
}

// SetIxSideID sets the "ix_side_id" field.
func (u *NetworkIxLanUpsertOne) SetIxSideID(v int) *NetworkIxLanUpsertOne {
	return u.Update(func(s *NetworkIxLanUpsert) {
		s.SetIxSideID(v)
	})
}

// AddIxSideID adds v to the "ix_side_id" field.
func (u *NetworkIxLanUpsertOne) AddIxSideID(v int) *NetworkIxLanUpsertOne {
	return u.Update(func(s *NetworkIxLanUpsert) {
		s.AddIxSideID(v)
	})
}

// UpdateIxSideID sets the "ix_side_id" field to the value that was provided on create.
func (u *NetworkIxLanUpsertOne) UpdateIxSideID() *NetworkIxLanUpsertOne {
	return u.Update(func(s *NetworkIxLanUpsert) {
		s.UpdateIxSideID()
	})
}

// ClearIxSideID clears the value of the "ix_side_id" field.
func (u *NetworkIxLanUpsertOne) ClearIxSideID() *NetworkIxLanUpsertOne {
	return u.Update(func(s *NetworkIxLanUpsert) {
		s.ClearIxSideID()
	})
}

// SetIxlanID sets the "ixlan_id" field.
func (u *NetworkIxLanUpsertOne) SetIxlanID(v int) *NetworkIxLanUpsertOne {
	return u.Update(func(s *NetworkIxLanUpsert) {
		s.SetIxlanID(v)
	})
}

// UpdateIxlanID sets the "ixlan_id" field to the value that was provided on create.
func (u *NetworkIxLanUpsertOne) UpdateIxlanID() *NetworkIxLanUpsertOne {
	return u.Update(func(s *NetworkIxLanUpsert) {
		s.UpdateIxlanID()
	})
}

// ClearIxlanID clears the value of the "ixlan_id" field.
func (u *NetworkIxLanUpsertOne) ClearIxlanID() *NetworkIxLanUpsertOne {
	return u.Update(func(s *NetworkIxLanUpsert) {
		s.ClearIxlanID()
	})
}

// SetNetID sets the "net_id" field.
func (u *NetworkIxLanUpsertOne) SetNetID(v int) *NetworkIxLanUpsertOne {
	return u.Update(func(s *NetworkIxLanUpsert) {
		s.SetNetID(v)
	})
}

// UpdateNetID sets the "net_id" field to the value that was provided on create.
func (u *NetworkIxLanUpsertOne) UpdateNetID() *NetworkIxLanUpsertOne {
	return u.Update(func(s *NetworkIxLanUpsert) {
		s.UpdateNetID()
	})
}

// ClearNetID clears the value of the "net_id" field.
func (u *NetworkIxLanUpsertOne) ClearNetID() *NetworkIxLanUpsertOne {
	return u.Update(func(s *NetworkIxLanUpsert) {
		s.ClearNetID()
	})
}

// SetNetSideID sets the "net_side_id" field.
func (u *NetworkIxLanUpsertOne) SetNetSideID(v int) *NetworkIxLanUpsertOne {
	return u.Update(func(s *NetworkIxLanUpsert) {
		s.SetNetSideID(v)
	})
}

// AddNetSideID adds v to the "net_side_id" field.
func (u *NetworkIxLanUpsertOne) AddNetSideID(v int) *NetworkIxLanUpsertOne {
	return u.Update(func(s *NetworkIxLanUpsert) {
		s.AddNetSideID(v)
	})
}

// UpdateNetSideID sets the "net_side_id" field to the value that was provided on create.
func (u *NetworkIxLanUpsertOne) UpdateNetSideID() *NetworkIxLanUpsertOne {
	return u.Update(func(s *NetworkIxLanUpsert) {
		s.UpdateNetSideID()
	})
}

// ClearNetSideID clears the value of the "net_side_id" field.
func (u *NetworkIxLanUpsertOne) ClearNetSideID() *NetworkIxLanUpsertOne {
	return u.Update(func(s *NetworkIxLanUpsert) {
		s.ClearNetSideID()
	})
}

// SetAsn sets the "asn" field.
func (u *NetworkIxLanUpsertOne) SetAsn(v int) *NetworkIxLanUpsertOne {
	return u.Update(func(s *NetworkIxLanUpsert) {
		s.SetAsn(v)
	})
}

// AddAsn adds v to the "asn" field.
func (u *NetworkIxLanUpsertOne) AddAsn(v int) *NetworkIxLanUpsertOne {
	return u.Update(func(s *NetworkIxLanUpsert) {
		s.AddAsn(v)
	})
}

// UpdateAsn sets the "asn" field to the value that was provided on create.
func (u *NetworkIxLanUpsertOne) UpdateAsn() *NetworkIxLanUpsertOne {
	return u.Update(func(s *NetworkIxLanUpsert) {
		s.UpdateAsn()
	})
}

// SetBfdSupport sets the "bfd_support" field.
func (u *NetworkIxLanUpsertOne) SetBfdSupport(v bool) *NetworkIxLanUpsertOne {
	return u.Update(func(s *NetworkIxLanUpsert) {
		s.SetBfdSupport(v)
	})
}

// UpdateBfdSupport sets the "bfd_support" field to the value that was provided on create.
func (u *NetworkIxLanUpsertOne) UpdateBfdSupport() *NetworkIxLanUpsertOne {
	return u.Update(func(s *NetworkIxLanUpsert) {
		s.UpdateBfdSupport()
	})
}

// SetIpaddr4 sets the "ipaddr4" field.
func (u *NetworkIxLanUpsertOne) SetIpaddr4(v string) *NetworkIxLanUpsertOne {
	return u.Update(func(s *NetworkIxLanUpsert) {
		s.SetIpaddr4(v)
	})
}

// UpdateIpaddr4 sets the "ipaddr4" field to the value that was provided on create.
func (u *NetworkIxLanUpsertOne) UpdateIpaddr4() *NetworkIxLanUpsertOne {
	return u.Update(func(s *NetworkIxLanUpsert) {
		s.UpdateIpaddr4()
	})
}

// ClearIpaddr4 clears the value of the "ipaddr4" field.
func (u *NetworkIxLanUpsertOne) ClearIpaddr4() *NetworkIxLanUpsertOne {
	return u.Update(func(s *NetworkIxLanUpsert) {
		s.ClearIpaddr4()
	})
}

// SetIpaddr6 sets the "ipaddr6" field.
func (u *NetworkIxLanUpsertOne) SetIpaddr6(v string) *NetworkIxLanUpsertOne {
	return u.Update(func(s *NetworkIxLanUpsert) {
		s.SetIpaddr6(v)
	})
}

// UpdateIpaddr6 sets the "ipaddr6" field to the value that was provided on create.
func (u *NetworkIxLanUpsertOne) UpdateIpaddr6() *NetworkIxLanUpsertOne {
	return u.Update(func(s *NetworkIxLanUpsert) {
		s.UpdateIpaddr6()
	})
}

// ClearIpaddr6 clears the value of the "ipaddr6" field.
func (u *NetworkIxLanUpsertOne) ClearIpaddr6() *NetworkIxLanUpsertOne {
	return u.Update(func(s *NetworkIxLanUpsert) {
		s.ClearIpaddr6()
	})
}

// SetIsRsPeer sets the "is_rs_peer" field.
func (u *NetworkIxLanUpsertOne) SetIsRsPeer(v bool) *NetworkIxLanUpsertOne {
	return u.Update(func(s *NetworkIxLanUpsert) {
		s.SetIsRsPeer(v)
	})
}

// UpdateIsRsPeer sets the "is_rs_peer" field to the value that was provided on create.
func (u *NetworkIxLanUpsertOne) UpdateIsRsPeer() *NetworkIxLanUpsertOne {
	return u.Update(func(s *NetworkIxLanUpsert) {
		s.UpdateIsRsPeer()
	})
}

// SetNotes sets the "notes" field.
func (u *NetworkIxLanUpsertOne) SetNotes(v string) *NetworkIxLanUpsertOne {
	return u.Update(func(s *NetworkIxLanUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *NetworkIxLanUpsertOne) UpdateNotes() *NetworkIxLanUpsertOne {
	return u.Update(func(s *NetworkIxLanUpsert) {
		s.UpdateNotes()
	})
}

// ClearNotes clears the value of the "notes" field.
func (u *NetworkIxLanUpsertOne) ClearNotes() *NetworkIxLanUpsertOne {
	return u.Update(func(s *NetworkIxLanUpsert) {
		s.ClearNotes()
	})
}

// SetOperational sets the "operational" field.
func (u *NetworkIxLanUpsertOne) SetOperational(v bool) *NetworkIxLanUpsertOne {
	return u.Update(func(s *NetworkIxLanUpsert) {
		s.SetOperational(v)
	})
}

// UpdateOperational sets the "operational" field to the value that was provided on create.
func (u *NetworkIxLanUpsertOne) UpdateOperational() *NetworkIxLanUpsertOne {
	return u.Update(func(s *NetworkIxLanUpsert) {
		s.UpdateOperational()
	})
}

// SetSpeed sets the "speed" field.
func (u *NetworkIxLanUpsertOne) SetSpeed(v int) *NetworkIxLanUpsertOne {
	return u.Update(func(s *NetworkIxLanUpsert) {
		s.SetSpeed(v)
	})
}

// AddSpeed adds v to the "speed" field.
func (u *NetworkIxLanUpsertOne) AddSpeed(v int) *NetworkIxLanUpsertOne {
	return u.Update(func(s *NetworkIxLanUpsert) {
		s.AddSpeed(v)
	})
}

// UpdateSpeed sets the "speed" field to the value that was provided on create.
func (u *NetworkIxLanUpsertOne) UpdateSpeed() *NetworkIxLanUpsertOne {
	return u.Update(func(s *NetworkIxLanUpsert) {
		s.UpdateSpeed()
	})
}

// SetIxID sets the "ix_id" field.
func (u *NetworkIxLanUpsertOne) SetIxID(v int) *NetworkIxLanUpsertOne {
	return u.Update(func(s *NetworkIxLanUpsert) {
		s.SetIxID(v)
	})
}

// AddIxID adds v to the "ix_id" field.
func (u *NetworkIxLanUpsertOne) AddIxID(v int) *NetworkIxLanUpsertOne {
	return u.Update(func(s *NetworkIxLanUpsert) {
		s.AddIxID(v)
	})
}

// UpdateIxID sets the "ix_id" field to the value that was provided on create.
func (u *NetworkIxLanUpsertOne) UpdateIxID() *NetworkIxLanUpsertOne {
	return u.Update(func(s *NetworkIxLanUpsert) {
		s.UpdateIxID()
	})
}

// ClearIxID clears the value of the "ix_id" field.
func (u *NetworkIxLanUpsertOne) ClearIxID() *NetworkIxLanUpsertOne {
	return u.Update(func(s *NetworkIxLanUpsert) {
		s.ClearIxID()
	})
}

// SetName sets the "name" field.
func (u *NetworkIxLanUpsertOne) SetName(v string) *NetworkIxLanUpsertOne {
	return u.Update(func(s *NetworkIxLanUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *NetworkIxLanUpsertOne) UpdateName() *NetworkIxLanUpsertOne {
	return u.Update(func(s *NetworkIxLanUpsert) {
		s.UpdateName()
	})
}

// ClearName clears the value of the "name" field.
func (u *NetworkIxLanUpsertOne) ClearName() *NetworkIxLanUpsertOne {
	return u.Update(func(s *NetworkIxLanUpsert) {
		s.ClearName()
	})
}

// SetUpdated sets the "updated" field.
func (u *NetworkIxLanUpsertOne) SetUpdated(v time.Time) *NetworkIxLanUpsertOne {
	return u.Update(func(s *NetworkIxLanUpsert) {
		s.SetUpdated(v)
	})
}

// UpdateUpdated sets the "updated" field to the value that was provided on create.
func (u *NetworkIxLanUpsertOne) UpdateUpdated() *NetworkIxLanUpsertOne {
	return u.Update(func(s *NetworkIxLanUpsert) {
		s.UpdateUpdated()
	})
}

// SetStatus sets the "status" field.
func (u *NetworkIxLanUpsertOne) SetStatus(v string) *NetworkIxLanUpsertOne {
	return u.Update(func(s *NetworkIxLanUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *NetworkIxLanUpsertOne) UpdateStatus() *NetworkIxLanUpsertOne {
	return u.Update(func(s *NetworkIxLanUpsert) {
		s.UpdateStatus()
	})
}

// Exec executes the query.
func (u *NetworkIxLanUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for NetworkIxLanCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *NetworkIxLanUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *NetworkIxLanUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *NetworkIxLanUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// NetworkIxLanCreateBulk is the builder for creating many NetworkIxLan entities in bulk.
type NetworkIxLanCreateBulk struct {
	config
	err      error
	builders []*NetworkIxLanCreate
	conflict []sql.ConflictOption
}

// Save creates the NetworkIxLan entities in the database.
func (_c *NetworkIxLanCreateBulk) Save(ctx context.Context) ([]*NetworkIxLan, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*NetworkIxLan, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*NetworkIxLanMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *NetworkIxLanCreateBulk) SaveX(ctx context.Context) []*NetworkIxLan {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NetworkIxLanCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NetworkIxLanCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.NetworkIxLan.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.NetworkIxLanUpsert) {
//			SetIxSideID(v+v).
//		}).
//		Exec(ctx)
func (_c *NetworkIxLanCreateBulk) OnConflict(opts ...sql.ConflictOption) *NetworkIxLanUpsertBulk {
	_c.conflict = opts
	return &NetworkIxLanUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.NetworkIxLan.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *NetworkIxLanCreateBulk) OnConflictColumns(columns ...string) *NetworkIxLanUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &NetworkIxLanUpsertBulk{
		create: _c,
	}
}

// NetworkIxLanUpsertBulk is the builder for "upsert"-ing
// a bulk of NetworkIxLan nodes.
type NetworkIxLanUpsertBulk struct {
	create *NetworkIxLanCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.NetworkIxLan.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(networkixlan.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *NetworkIxLanUpsertBulk) UpdateNewValues() *NetworkIxLanUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(networkixlan.FieldID)
			}
			if _, exists := b.mutation.Created(); exists {
				s.SetIgnore(networkixlan.FieldCreated)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.NetworkIxLan.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *NetworkIxLanUpsertBulk) Ignore() *NetworkIxLanUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *NetworkIxLanUpsertBulk) DoNothing() *NetworkIxLanUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the NetworkIxLanCreateBulk.OnConflict
// documentation for more info.
func (u *NetworkIxLanUpsertBulk) Update(set func(*NetworkIxLanUpsert)) *NetworkIxLanUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&NetworkIxLanUpsert{UpdateSet: update})
	}))
	return u
}

// SetIxSideID sets the "ix_side_id" field.
func (u *NetworkIxLanUpsertBulk) SetIxSideID(v int) *NetworkIxLanUpsertBulk {
	return u.Update(func(s *NetworkIxLanUpsert) {
		s.SetIxSideID(v)
	})
}

// AddIxSideID adds v to the "ix_side_id" field.
func (u *NetworkIxLanUpsertBulk) AddIxSideID(v int) *NetworkIxLanUpsertBulk {
	return u.Update(func(s *NetworkIxLanUpsert) {
		s.AddIxSideID(v)
	})
}

// UpdateIxSideID sets the "ix_side_id" field to the value that was provided on create.
func (u *NetworkIxLanUpsertBulk) UpdateIxSideID() *NetworkIxLanUpsertBulk {
	return u.Update(func(s *NetworkIxLanUpsert) {
		s.UpdateIxSideID()
	})
}

// ClearIxSideID clears the value of the "ix_side_id" field.
func (u *NetworkIxLanUpsertBulk) ClearIxSideID() *NetworkIxLanUpsertBulk {
	return u.Update(func(s *NetworkIxLanUpsert) {
		s.ClearIxSideID()
	})
}

// SetIxlanID sets the "ixlan_id" field.
func (u *NetworkIxLanUpsertBulk) SetIxlanID(v int) *NetworkIxLanUpsertBulk {
	return u.Update(func(s *NetworkIxLanUpsert) {
		s.SetIxlanID(v)
	})
}

// UpdateIxlanID sets the "ixlan_id" field to the value that was provided on create.
func (u *NetworkIxLanUpsertBulk) UpdateIxlanID() *NetworkIxLanUpsertBulk {
	return u.Update(func(s *NetworkIxLanUpsert) {
		s.UpdateIxlanID()
	})
}

// ClearIxlanID clears the value of the "ixlan_id" field.
func (u *NetworkIxLanUpsertBulk) ClearIxlanID() *NetworkIxLanUpsertBulk {
	return u.Update(func(s *NetworkIxLanUpsert) {
		s.ClearIxlanID()
	})
}

// SetNetID sets the "net_id" field.
func (u *NetworkIxLanUpsertBulk) SetNetID(v int) *NetworkIxLanUpsertBulk {
	return u.Update(func(s *NetworkIxLanUpsert) {
		s.SetNetID(v)
	})
}

// UpdateNetID sets the "net_id" field to the value that was provided on create.
func (u *NetworkIxLanUpsertBulk) UpdateNetID() *NetworkIxLanUpsertBulk {
	return u.Update(func(s *NetworkIxLanUpsert) {
		s.UpdateNetID()
	})
}

// ClearNetID clears the value of the "net_id" field.
func (u *NetworkIxLanUpsertBulk) ClearNetID() *NetworkIxLanUpsertBulk {
	return u.Update(func(s *NetworkIxLanUpsert) {
		s.ClearNetID()
	})
}

// SetNetSideID sets the "net_side_id" field.
func (u *NetworkIxLanUpsertBulk) SetNetSideID(v int) *NetworkIxLanUpsertBulk {
	return u.Update(func(s *NetworkIxLanUpsert) {
		s.SetNetSideID(v)
	})
}

// AddNetSideID adds v to the "net_side_id" field.
func (u *NetworkIxLanUpsertBulk) AddNetSideID(v int) *NetworkIxLanUpsertBulk {
	return u.Update(func(s *NetworkIxLanUpsert) {
		s.AddNetSideID(v)
	})
}

// UpdateNetSideID sets the "net_side_id" field to the value that was provided on create.
func (u *NetworkIxLanUpsertBulk) UpdateNetSideID() *NetworkIxLanUpsertBulk {
	return u.Update(func(s *NetworkIxLanUpsert) {
		s.UpdateNetSideID()
	})
}

// ClearNetSideID clears the value of the "net_side_id" field.
func (u *NetworkIxLanUpsertBulk) ClearNetSideID() *NetworkIxLanUpsertBulk {
	return u.Update(func(s *NetworkIxLanUpsert) {
		s.ClearNetSideID()
	})
}

// SetAsn sets the "asn" field.
func (u *NetworkIxLanUpsertBulk) SetAsn(v int) *NetworkIxLanUpsertBulk {
	return u.Update(func(s *NetworkIxLanUpsert) {
		s.SetAsn(v)
	})
}

// AddAsn adds v to the "asn" field.
func (u *NetworkIxLanUpsertBulk) AddAsn(v int) *NetworkIxLanUpsertBulk {
	return u.Update(func(s *NetworkIxLanUpsert) {
		s.AddAsn(v)
	})
}

// UpdateAsn sets the "asn" field to the value that was provided on create.
func (u *NetworkIxLanUpsertBulk) UpdateAsn() *NetworkIxLanUpsertBulk {
	return u.Update(func(s *NetworkIxLanUpsert) {
		s.UpdateAsn()
	})
}

// SetBfdSupport sets the "bfd_support" field.
func (u *NetworkIxLanUpsertBulk) SetBfdSupport(v bool) *NetworkIxLanUpsertBulk {
	return u.Update(func(s *NetworkIxLanUpsert) {
		s.SetBfdSupport(v)
	})
}

// UpdateBfdSupport sets the "bfd_support" field to the value that was provided on create.
func (u *NetworkIxLanUpsertBulk) UpdateBfdSupport() *NetworkIxLanUpsertBulk {
	return u.Update(func(s *NetworkIxLanUpsert) {
		s.UpdateBfdSupport()
	})
}

// SetIpaddr4 sets the "ipaddr4" field.
func (u *NetworkIxLanUpsertBulk) SetIpaddr4(v string) *NetworkIxLanUpsertBulk {
	return u.Update(func(s *NetworkIxLanUpsert) {
		s.SetIpaddr4(v)
	})
}

// UpdateIpaddr4 sets the "ipaddr4" field to the value that was provided on create.
func (u *NetworkIxLanUpsertBulk) UpdateIpaddr4() *NetworkIxLanUpsertBulk {
	return u.Update(func(s *NetworkIxLanUpsert) {
		s.UpdateIpaddr4()
	})
}

// ClearIpaddr4 clears the value of the "ipaddr4" field.
func (u *NetworkIxLanUpsertBulk) ClearIpaddr4() *NetworkIxLanUpsertBulk {
	return u.Update(func(s *NetworkIxLanUpsert) {
		s.ClearIpaddr4()
	})
}

// SetIpaddr6 sets the "ipaddr6" field.
func (u *NetworkIxLanUpsertBulk) SetIpaddr6(v string) *NetworkIxLanUpsertBulk {
	return u.Update(func(s *NetworkIxLanUpsert) {
		s.SetIpaddr6(v)
	})
}

// UpdateIpaddr6 sets the "ipaddr6" field to the value that was provided on create.
func (u *NetworkIxLanUpsertBulk) UpdateIpaddr6() *NetworkIxLanUpsertBulk {
	return u.Update(func(s *NetworkIxLanUpsert) {
		s.UpdateIpaddr6()
	})
}

// ClearIpaddr6 clears the value of the "ipaddr6" field.
func (u *NetworkIxLanUpsertBulk) ClearIpaddr6() *NetworkIxLanUpsertBulk {
	return u.Update(func(s *NetworkIxLanUpsert) {
		s.ClearIpaddr6()
	})
}

// SetIsRsPeer sets the "is_rs_peer" field.
func (u *NetworkIxLanUpsertBulk) SetIsRsPeer(v bool) *NetworkIxLanUpsertBulk {
	return u.Update(func(s *NetworkIxLanUpsert) {
		s.SetIsRsPeer(v)
	})
}

// UpdateIsRsPeer sets the "is_rs_peer" field to the value that was provided on create.
func (u *NetworkIxLanUpsertBulk) UpdateIsRsPeer() *NetworkIxLanUpsertBulk {
	return u.Update(func(s *NetworkIxLanUpsert) {
		s.UpdateIsRsPeer()
	})
}

// SetNotes sets the "notes" field.
func (u *NetworkIxLanUpsertBulk) SetNotes(v string) *NetworkIxLanUpsertBulk {
	return u.Update(func(s *NetworkIxLanUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *NetworkIxLanUpsertBulk) UpdateNotes() *NetworkIxLanUpsertBulk {
	return u.Update(func(s *NetworkIxLanUpsert) {
		s.UpdateNotes()
	})
}

// ClearNotes clears the value of the "notes" field.
func (u *NetworkIxLanUpsertBulk) ClearNotes() *NetworkIxLanUpsertBulk {
	return u.Update(func(s *NetworkIxLanUpsert) {
		s.ClearNotes()
	})
}

// SetOperational sets the "operational" field.
func (u *NetworkIxLanUpsertBulk) SetOperational(v bool) *NetworkIxLanUpsertBulk {
	return u.Update(func(s *NetworkIxLanUpsert) {
		s.SetOperational(v)
	})
}

// UpdateOperational sets the "operational" field to the value that was provided on create.
func (u *NetworkIxLanUpsertBulk) UpdateOperational() *NetworkIxLanUpsertBulk {
	return u.Update(func(s *NetworkIxLanUpsert) {
		s.UpdateOperational()
	})
}

// SetSpeed sets the "speed" field.
func (u *NetworkIxLanUpsertBulk) SetSpeed(v int) *NetworkIxLanUpsertBulk {
	return u.Update(func(s *NetworkIxLanUpsert) {
		s.SetSpeed(v)
	})
}

// AddSpeed adds v to the "speed" field.
func (u *NetworkIxLanUpsertBulk) AddSpeed(v int) *NetworkIxLanUpsertBulk {
	return u.Update(func(s *NetworkIxLanUpsert) {
		s.AddSpeed(v)
	})
}

// UpdateSpeed sets the "speed" field to the value that was provided on create.
func (u *NetworkIxLanUpsertBulk) UpdateSpeed() *NetworkIxLanUpsertBulk {
	return u.Update(func(s *NetworkIxLanUpsert) {
		s.UpdateSpeed()
	})
}

// SetIxID sets the "ix_id" field.
func (u *NetworkIxLanUpsertBulk) SetIxID(v int) *NetworkIxLanUpsertBulk {
	return u.Update(func(s *NetworkIxLanUpsert) {
		s.SetIxID(v)
	})
}

// AddIxID adds v to the "ix_id" field.
func (u *NetworkIxLanUpsertBulk) AddIxID(v int) *NetworkIxLanUpsertBulk {
	return u.Update(func(s *NetworkIxLanUpsert) {
		s.AddIxID(v)
	})
}

// UpdateIxID sets the "ix_id" field to the value that was provided on create.
func (u *NetworkIxLanUpsertBulk) UpdateIxID() *NetworkIxLanUpsertBulk {
	return u.Update(func(s *NetworkIxLanUpsert) {
		s.UpdateIxID()
	})
}

// ClearIxID clears the value of the "ix_id" field.
func (u *NetworkIxLanUpsertBulk) ClearIxID() *NetworkIxLanUpsertBulk {
	return u.Update(func(s *NetworkIxLanUpsert) {
		s.ClearIxID()
	})
}

// SetName sets the "name" field.
func (u *NetworkIxLanUpsertBulk) SetName(v string) *NetworkIxLanUpsertBulk {
	return u.Update(func(s *NetworkIxLanUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *NetworkIxLanUpsertBulk) UpdateName() *NetworkIxLanUpsertBulk {
	return u.Update(func(s *NetworkIxLanUpsert) {
		s.UpdateName()
	})
}

// ClearName clears the value of the "name" field.
func (u *NetworkIxLanUpsertBulk) ClearName() *NetworkIxLanUpsertBulk {
	return u.Update(func(s *NetworkIxLanUpsert) {
		s.ClearName()
	})
}

// SetUpdated sets the "updated" field.
func (u *NetworkIxLanUpsertBulk) SetUpdated(v time.Time) *NetworkIxLanUpsertBulk {
	return u.Update(func(s *NetworkIxLanUpsert) {
		s.SetUpdated(v)
	})
}

// UpdateUpdated sets the "updated" field to the value that was provided on create.
func (u *NetworkIxLanUpsertBulk) UpdateUpdated() *NetworkIxLanUpsertBulk {
	return u.Update(func(s *NetworkIxLanUpsert) {
		s.UpdateUpdated()
	})
}

// SetStatus sets the "status" field.
func (u *NetworkIxLanUpsertBulk) SetStatus(v string) *NetworkIxLanUpsertBulk {
	return u.Update(func(s *NetworkIxLanUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *NetworkIxLanUpsertBulk) UpdateStatus() *NetworkIxLanUpsertBulk {
	return u.Update(func(s *NetworkIxLanUpsert) {
		s.UpdateStatus()
	})
}

// Exec executes the query.
func (u *NetworkIxLanUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the NetworkIxLanCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for NetworkIxLanCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *NetworkIxLanUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
