// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/dotwaffle/peeringdb-plus/ent/ixlan"
	"github.com/dotwaffle/peeringdb-plus/ent/network"
	"github.com/dotwaffle/peeringdb-plus/ent/networkixlan"
	"github.com/dotwaffle/peeringdb-plus/ent/predicate"
)

// NetworkIxLanUpdate is the builder for updating NetworkIxLan entities.
type NetworkIxLanUpdate struct {
	config
	hooks    []Hook
	mutation *NetworkIxLanMutation
}

// Where appends a list predicates to the NetworkIxLanUpdate builder.
func (_u *NetworkIxLanUpdate) Where(ps ...predicate.NetworkIxLan) *NetworkIxLanUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetIxSideID sets the "ix_side_id" field.
func (_u *NetworkIxLanUpdate) SetIxSideID(v int) *NetworkIxLanUpdate {
	_u.mutation.ResetIxSideID()
	_u.mutation.SetIxSideID(v)
	return _u
}

// SetNillableIxSideID sets the "ix_side_id" field if the given value is not nil.
func (_u *NetworkIxLanUpdate) SetNillableIxSideID(v *int) *NetworkIxLanUpdate {
	if v != nil {
		_u.SetIxSideID(*v)
	}
	return _u
}

// AddIxSideID adds value to the "ix_side_id" field.
func (_u *NetworkIxLanUpdate) AddIxSideID(v int) *NetworkIxLanUpdate {
	_u.mutation.AddIxSideID(v)
	return _u
}

// ClearIxSideID clears the value of the "ix_side_id" field.
func (_u *NetworkIxLanUpdate) ClearIxSideID() *NetworkIxLanUpdate {
	_u.mutation.ClearIxSideID()
	return _u
}

// SetIxlanID sets the "ixlan_id" field.
func (_u *NetworkIxLanUpdate) SetIxlanID(v int) *NetworkIxLanUpdate {
	_u.mutation.SetIxlanID(v)
	return _u
}

// SetNillableIxlanID sets the "ixlan_id" field if the given value is not nil.
func (_u *NetworkIxLanUpdate) SetNillableIxlanID(v *int) *NetworkIxLanUpdate {
	if v != nil {
		_u.SetIxlanID(*v)
	}
	return _u
}

// ClearIxlanID clears the value of the "ixlan_id" field.
func (_u *NetworkIxLanUpdate) ClearIxlanID() *NetworkIxLanUpdate {
	_u.mutation.ClearIxlanID()
	return _u
}

// SetNetID sets the "net_id" field.
func (_u *NetworkIxLanUpdate) SetNetID(v int) *NetworkIxLanUpdate {
	_u.mutation.SetNetID(v)
	return _u
}

// SetNillableNetID sets the "net_id" field if the given value is not nil.
func (_u *NetworkIxLanUpdate) SetNillableNetID(v *int) *NetworkIxLanUpdate {
	if v != nil {
		_u.SetNetID(*v)
	}
	return _u
}

// ClearNetID clears the value of the "net_id" field.
func (_u *NetworkIxLanUpdate) ClearNetID() *NetworkIxLanUpdate {
	_u.mutation.ClearNetID()
	return _u
}

// SetNetSideID sets the "net_side_id" field.
func (_u *NetworkIxLanUpdate) SetNetSideID(v int) *NetworkIxLanUpdate {
	_u.mutation.ResetNetSideID()
	_u.mutation.SetNetSideID(v)
	return _u
}

// SetNillableNetSideID sets the "net_side_id" field if the given value is not nil.
func (_u *NetworkIxLanUpdate) SetNillableNetSideID(v *int) *NetworkIxLanUpdate {
	if v != nil {
		_u.SetNetSideID(*v)
	}
	return _u
}

// AddNetSideID adds value to the "net_side_id" field.
func (_u *NetworkIxLanUpdate) AddNetSideID(v int) *NetworkIxLanUpdate {
	_u.mutation.AddNetSideID(v)
	return _u
}

// ClearNetSideID clears the value of the "net_side_id" field.
func (_u *NetworkIxLanUpdate) ClearNetSideID() *NetworkIxLanUpdate {
	_u.mutation.ClearNetSideID()
	return _u
}

// SetAsn sets the "asn" field.
func (_u *NetworkIxLanUpdate) SetAsn(v int) *NetworkIxLanUpdate {
	_u.mutation.ResetAsn()
	_u.mutation.SetAsn(v)
	return _u
}

// SetNillableAsn sets the "asn" field if the given value is not nil.
func (_u *NetworkIxLanUpdate) SetNillableAsn(v *int) *NetworkIxLanUpdate {
	if v != nil {
		_u.SetAsn(*v)
	}
	return _u
}

// AddAsn adds value to the "asn" field.
func (_u *NetworkIxLanUpdate) AddAsn(v int) *NetworkIxLanUpdate {
	_u.mutation.AddAsn(v)
	return _u
}

// SetBfdSupport sets the "bfd_support" field.
func (_u *NetworkIxLanUpdate) SetBfdSupport(v bool) *NetworkIxLanUpdate {
	_u.mutation.SetBfdSupport(v)
	return _u
}

// SetNillableBfdSupport sets the "bfd_support" field if the given value is not nil.
func (_u *NetworkIxLanUpdate) SetNillableBfdSupport(v *bool) *NetworkIxLanUpdate {
	if v != nil {
		_u.SetBfdSupport(*v)
	}
	return _u
}

// SetIpaddr4 sets the "ipaddr4" field.
func (_u *NetworkIxLanUpdate) SetIpaddr4(v string) *NetworkIxLanUpdate {
	_u.mutation.SetIpaddr4(v)
	return _u
}

// SetNillableIpaddr4 sets the "ipaddr4" field if the given value is not nil.
func (_u *NetworkIxLanUpdate) SetNillableIpaddr4(v *string) *NetworkIxLanUpdate {
	if v != nil {
		_u.SetIpaddr4(*v)
	}
	return _u
}

// ClearIpaddr4 clears the value of the "ipaddr4" field.
func (_u *NetworkIxLanUpdate) ClearIpaddr4() *NetworkIxLanUpdate {
	_u.mutation.ClearIpaddr4()
	return _u
}

// SetIpaddr6 sets the "ipaddr6" field.
func (_u *NetworkIxLanUpdate) SetIpaddr6(v string) *NetworkIxLanUpdate {
	_u.mutation.SetIpaddr6(v)
	return _u
}

// SetNillableIpaddr6 sets the "ipaddr6" field if the given value is not nil.
func (_u *NetworkIxLanUpdate) SetNillableIpaddr6(v *string) *NetworkIxLanUpdate {
	if v != nil {
		_u.SetIpaddr6(*v)
	}
	return _u
}

// ClearIpaddr6 clears the value of the "ipaddr6" field.
func (_u *NetworkIxLanUpdate) ClearIpaddr6() *NetworkIxLanUpdate {
	_u.mutation.ClearIpaddr6()
	return _u
}

// SetIsRsPeer sets the "is_rs_peer" field.
func (_u *NetworkIxLanUpdate) SetIsRsPeer(v bool) *NetworkIxLanUpdate {
	_u.mutation.SetIsRsPeer(v)
	return _u
}

// SetNillableIsRsPeer sets the "is_rs_peer" field if the given value is not nil.
func (_u *NetworkIxLanUpdate) SetNillableIsRsPeer(v *bool) *NetworkIxLanUpdate {
	if v != nil {
		_u.SetIsRsPeer(*v)
	}
	return _u
}

// SetNotes sets the "notes" field.
func (_u *NetworkIxLanUpdate) SetNotes(v string) *NetworkIxLanUpdate {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *NetworkIxLanUpdate) SetNillableNotes(v *string) *NetworkIxLanUpdate {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *NetworkIxLanUpdate) ClearNotes() *NetworkIxLanUpdate {
	_u.mutation.ClearNotes()
	return _u
}

// SetOperational sets the "operational" field.
func (_u *NetworkIxLanUpdate) SetOperational(v bool) *NetworkIxLanUpdate {
	_u.mutation.SetOperational(v)
	return _u
}

// SetNillableOperational sets the "operational" field if the given value is not nil.
func (_u *NetworkIxLanUpdate) SetNillableOperational(v *bool) *NetworkIxLanUpdate {
	if v != nil {
		_u.SetOperational(*v)
	}
	return _u
}

// SetSpeed sets the "speed" field.
func (_u *NetworkIxLanUpdate) SetSpeed(v int) *NetworkIxLanUpdate {
	_u.mutation.ResetSpeed()
	_u.mutation.SetSpeed(v)
	return _u
}

// SetNillableSpeed sets the "speed" field if the given value is not nil.
func (_u *NetworkIxLanUpdate) SetNillableSpeed(v *int) *NetworkIxLanUpdate {
	if v != nil {
		_u.SetSpeed(*v)
	}
	return _u
}

// AddSpeed adds value to the "speed" field.
func (_u *NetworkIxLanUpdate) AddSpeed(v int) *NetworkIxLanUpdate {
	_u.mutation.AddSpeed(v)
	return _u
}

// SetIxID sets the "ix_id" field.
func (_u *NetworkIxLanUpdate) SetIxID(v int) *NetworkIxLanUpdate {
	_u.mutation.ResetIxID()
	_u.mutation.SetIxID(v)
	return _u
}

// SetNillableIxID sets the "ix_id" field if the given value is not nil.
func (_u *NetworkIxLanUpdate) SetNillableIxID(v *int) *NetworkIxLanUpdate {
	if v != nil {
		_u.SetIxID(*v)
	}
	return _u
}

// AddIxID adds value to the "ix_id" field.
func (_u *NetworkIxLanUpdate) AddIxID(v int) *NetworkIxLanUpdate {
	_u.mutation.AddIxID(v)
	return _u
}

// ClearIxID clears the value of the "ix_id" field.
func (_u *NetworkIxLanUpdate) ClearIxID() *NetworkIxLanUpdate {
	_u.mutation.ClearIxID()
	return _u
}

// SetName sets the "name" field.
func (_u *NetworkIxLanUpdate) SetName(v string) *NetworkIxLanUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *NetworkIxLanUpdate) SetNillableName(v *string) *NetworkIxLanUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// ClearName clears the value of the "name" field.
func (_u *NetworkIxLanUpdate) ClearName() *NetworkIxLanUpdate {
	_u.mutation.ClearName()
	return _u
}

// SetUpdated sets the "updated" field.
func (_u *NetworkIxLanUpdate) SetUpdated(v time.Time) *NetworkIxLanUpdate {
	_u.mutation.SetUpdated(v)
	return _u
}

// SetNillableUpdated sets the "updated" field if the given value is not nil.
func (_u *NetworkIxLanUpdate) SetNillableUpdated(v *time.Time) *NetworkIxLanUpdate {
	if v != nil {
		_u.SetUpdated(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *NetworkIxLanUpdate) SetStatus(v string) *NetworkIxLanUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *NetworkIxLanUpdate) SetNillableStatus(v *string) *NetworkIxLanUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetIxLanID sets the "ix_lan" edge to the IxLan entity by ID.
func (_u *NetworkIxLanUpdate) SetIxLanID(id int) *NetworkIxLanUpdate {
	_u.mutation.SetIxLanID(id)
	return _u
}

// SetNillableIxLanID sets the "ix_lan" edge to the IxLan entity by ID if the given value is not nil.
func (_u *NetworkIxLanUpdate) SetNillableIxLanID(id *int) *NetworkIxLanUpdate {
	if id != nil {
		_u = _u.SetIxLanID(*id)
	}
	return _u
}

// SetIxLan sets the "ix_lan" edge to the IxLan entity.
func (_u *NetworkIxLanUpdate) SetIxLan(v *IxLan) *NetworkIxLanUpdate {
	return _u.SetIxLanID(v.ID)
}

// SetNetworkID sets the "network" edge to the Network entity by ID.
func (_u *NetworkIxLanUpdate) SetNetworkID(id int) *NetworkIxLanUpdate {
	_u.mutation.SetNetworkID(id)
	return _u
}

// SetNillableNetworkID sets the "network" edge to the Network entity by ID if the given value is not nil.
func (_u *NetworkIxLanUpdate) SetNillableNetworkID(id *int) *NetworkIxLanUpdate {
	if id != nil {
		_u = _u.SetNetworkID(*id)
	}
	return _u
}

// SetNetwork sets the "network" edge to the Network entity.
func (_u *NetworkIxLanUpdate) SetNetwork(v *Network) *NetworkIxLanUpdate {
	return _u.SetNetworkID(v.ID)
}

// Mutation returns the NetworkIxLanMutation object of the builder.
func (_u *NetworkIxLanUpdate) Mutation() *NetworkIxLanMutation {
	return _u.mutation
}

// ClearIxLan clears the "ix_lan" edge to the IxLan entity.
func (_u *NetworkIxLanUpdate) ClearIxLan() *NetworkIxLanUpdate {
	_u.mutation.ClearIxLan()
	return _u
}

// ClearNetwork clears the "network" edge to the Network entity.
func (_u *NetworkIxLanUpdate) ClearNetwork() *NetworkIxLanUpdate {
	_u.mutation.ClearNetwork()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *NetworkIxLanUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NetworkIxLanUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *NetworkIxLanUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NetworkIxLanUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *NetworkIxLanUpdate) check() error {
	if v, ok := _u.mutation.Asn(); ok {
		if err := networkixlan.AsnValidator(v); err != nil {
			return &ValidationError{Name: "asn", err: fmt.Errorf(`ent: validator failed for field "NetworkIxLan.asn": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Notes(); ok {
		if err := networkixlan.NotesValidator(v); err != nil {
			return &ValidationError{Name: "notes", err: fmt.Errorf(`ent: validator failed for field "NetworkIxLan.notes": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := networkixlan.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "NetworkIxLan.status": %w`, err)}
		}
	}
	return nil
}

func (_u *NetworkIxLanUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(networkixlan.Table, networkixlan.Columns, sqlgraph.NewFieldSpec(networkixlan.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.IxSideID(); ok {
		_spec.SetField(networkixlan.FieldIxSideID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedIxSideID(); ok {
		_spec.AddField(networkixlan.FieldIxSideID, field.TypeInt, value)
	}
	if _u.mutation.IxSideIDCleared() {
		_spec.ClearField(networkixlan.FieldIxSideID, field.TypeInt)
	}
	if value, ok := _u.mutation.NetSideID(); ok {
		_spec.SetField(networkixlan.FieldNetSideID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedNetSideID(); ok {
		_spec.AddField(networkixlan.FieldNetSideID, field.TypeInt, value)
	}
	if _u.mutation.NetSideIDCleared() {
		_spec.ClearField(networkixlan.FieldNetSideID, field.TypeInt)
	}
	if value, ok := _u.mutation.Asn(); ok {
		_spec.SetField(networkixlan.FieldAsn, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAsn(); ok {
		_spec.AddField(networkixlan.FieldAsn, field.TypeInt, value)
	}
	if value, ok := _u.mutation.BfdSupport(); ok {
		_spec.SetField(networkixlan.FieldBfdSupport, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Ipaddr4(); ok {
		_spec.SetField(networkixlan.FieldIpaddr4, field.TypeString, value)
	}
	if _u.mutation.Ipaddr4Cleared() {
		_spec.ClearField(networkixlan.FieldIpaddr4, field.TypeString)
	}
	if value, ok := _u.mutation.Ipaddr6(); ok {
		_spec.SetField(networkixlan.FieldIpaddr6, field.TypeString, value)
	}
	if _u.mutation.Ipaddr6Cleared() {
		_spec.ClearField(networkixlan.FieldIpaddr6, field.TypeString)
	}
	if value, ok := _u.mutation.IsRsPeer(); ok {
		_spec.SetField(networkixlan.FieldIsRsPeer, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(networkixlan.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(networkixlan.FieldNotes, field.TypeString)
	}
	if value, ok := _u.mutation.Operational(); ok {
		_spec.SetField(networkixlan.FieldOperational, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Speed(); ok {
		_spec.SetField(networkixlan.FieldSpeed, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSpeed(); ok {
		_spec.AddField(networkixlan.FieldSpeed, field.TypeInt, value)
	}
	if value, ok := _u.mutation.IxID(); ok {
		_spec.SetField(networkixlan.FieldIxID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedIxID(); ok {
		_spec.AddField(networkixlan.FieldIxID, field.TypeInt, value)
	}
	if _u.mutation.IxIDCleared() {
		_spec.ClearField(networkixlan.FieldIxID, field.TypeInt)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(networkixlan.FieldName, field.TypeString, value)
	}
	if _u.mutation.NameCleared() {
		_spec.ClearField(networkixlan.FieldName, field.TypeString)
	}
	if value, ok := _u.mutation.Updated(); ok {
		_spec.SetField(networkixlan.FieldUpdated, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(networkixlan.FieldStatus, field.TypeString, value)
	}
	if _u.mutation.IxLanCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   networkixlan.IxLanTable,
			Columns: []string{networkixlan.IxLanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ixlan.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.IxLanIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   networkixlan.IxLanTable,
			Columns: []string{networkixlan.IxLanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ixlan.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.NetworkCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   networkixlan.NetworkTable,
			Columns: []string{networkixlan.NetworkColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(network.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.NetworkIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   networkixlan.NetworkTable,
			Columns: []string{networkixlan.NetworkColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(network.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{networkixlan.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// NetworkIxLanUpdateOne is the builder for updating a single NetworkIxLan entity.
type NetworkIxLanUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *NetworkIxLanMutation
}

// SetIxSideID sets the "ix_side_id" field.
func (_u *NetworkIxLanUpdateOne) SetIxSideID(v int) *NetworkIxLanUpdateOne {
	_u.mutation.ResetIxSideID()
	_u.mutation.SetIxSideID(v)
	return _u
}

// SetNillableIxSideID sets the "ix_side_id" field if the given value is not nil.
func (_u *NetworkIxLanUpdateOne) SetNillableIxSideID(v *int) *NetworkIxLanUpdateOne {
	if v != nil {
		_u.SetIxSideID(*v)
	}
	return _u
}

// AddIxSideID adds value to the "ix_side_id" field.
func (_u *NetworkIxLanUpdateOne) AddIxSideID(v int) *NetworkIxLanUpdateOne {
	_u.mutation.AddIxSideID(v)
	return _u
}

// ClearIxSideID clears the value of the "ix_side_id" field.
func (_u *NetworkIxLanUpdateOne) ClearIxSideID() *NetworkIxLanUpdateOne {
	_u.mutation.ClearIxSideID()
	return _u
}

// SetIxlanID sets the "ixlan_id" field.
func (_u *NetworkIxLanUpdateOne) SetIxlanID(v int) *NetworkIxLanUpdateOne {
	_u.mutation.SetIxlanID(v)
	return _u
}

// SetNillableIxlanID sets the "ixlan_id" field if the given value is not nil.
func (_u *NetworkIxLanUpdateOne) SetNillableIxlanID(v *int) *NetworkIxLanUpdateOne {
	if v != nil {
		_u.SetIxlanID(*v)
	}
	return _u
}

// ClearIxlanID clears the value of the "ixlan_id" field.
func (_u *NetworkIxLanUpdateOne) ClearIxlanID() *NetworkIxLanUpdateOne {
	_u.mutation.ClearIxlanID()
	return _u
}

// SetNetID sets the "net_id" field.
func (_u *NetworkIxLanUpdateOne) SetNetID(v int) *NetworkIxLanUpdateOne {
	_u.mutation.SetNetID(v)
	return _u
}

// SetNillableNetID sets the "net_id" field if the given value is not nil.
func (_u *NetworkIxLanUpdateOne) SetNillableNetID(v *int) *NetworkIxLanUpdateOne {
	if v != nil {
		_u.SetNetID(*v)
	}
	return _u
}

// ClearNetID clears the value of the "net_id" field.
func (_u *NetworkIxLanUpdateOne) ClearNetID() *NetworkIxLanUpdateOne {
	_u.mutation.ClearNetID()
	return _u
}

// SetNetSideID sets the "net_side_id" field.
func (_u *NetworkIxLanUpdateOne) SetNetSideID(v int) *NetworkIxLanUpdateOne {
	_u.mutation.ResetNetSideID()
	_u.mutation.SetNetSideID(v)
	return _u
}

// SetNillableNetSideID sets the "net_side_id" field if the given value is not nil.
func (_u *NetworkIxLanUpdateOne) SetNillableNetSideID(v *int) *NetworkIxLanUpdateOne {
	if v != nil {
		_u.SetNetSideID(*v)
	}
	return _u
}

// AddNetSideID adds value to the "net_side_id" field.
func (_u *NetworkIxLanUpdateOne) AddNetSideID(v int) *NetworkIxLanUpdateOne {
	_u.mutation.AddNetSideID(v)
	return _u
}

// ClearNetSideID clears the value of the "net_side_id" field.
func (_u *NetworkIxLanUpdateOne) ClearNetSideID() *NetworkIxLanUpdateOne {
	_u.mutation.ClearNetSideID()
	return _u
}

// SetAsn sets the "asn" field.
func (_u *NetworkIxLanUpdateOne) SetAsn(v int) *NetworkIxLanUpdateOne {
	_u.mutation.ResetAsn()
	_u.mutation.SetAsn(v)
	return _u
}

// SetNillableAsn sets the "asn" field if the given value is not nil.
func (_u *NetworkIxLanUpdateOne) SetNillableAsn(v *int) *NetworkIxLanUpdateOne {
	if v != nil {
		_u.SetAsn(*v)
	}
	return _u
}

// AddAsn adds value to the "asn" field.
func (_u *NetworkIxLanUpdateOne) AddAsn(v int) *NetworkIxLanUpdateOne {
	_u.mutation.AddAsn(v)
	return _u
}

// SetBfdSupport sets the "bfd_support" field.
func (_u *NetworkIxLanUpdateOne) SetBfdSupport(v bool) *NetworkIxLanUpdateOne {
	_u.mutation.SetBfdSupport(v)
	return _u
}

// SetNillableBfdSupport sets the "bfd_support" field if the given value is not nil.
func (_u *NetworkIxLanUpdateOne) SetNillableBfdSupport(v *bool) *NetworkIxLanUpdateOne {
	if v != nil {
		_u.SetBfdSupport(*v)
	}
	return _u
}

// SetIpaddr4 sets the "ipaddr4" field.
func (_u *NetworkIxLanUpdateOne) SetIpaddr4(v string) *NetworkIxLanUpdateOne {
	_u.mutation.SetIpaddr4(v)
	return _u
}

// SetNillableIpaddr4 sets the "ipaddr4" field if the given value is not nil.
func (_u *NetworkIxLanUpdateOne) SetNillableIpaddr4(v *string) *NetworkIxLanUpdateOne {
	if v != nil {
		_u.SetIpaddr4(*v)
	}
	return _u
}

// ClearIpaddr4 clears the value of the "ipaddr4" field.
func (_u *NetworkIxLanUpdateOne) ClearIpaddr4() *NetworkIxLanUpdateOne {
	_u.mutation.ClearIpaddr4()
	return _u
}

// SetIpaddr6 sets the "ipaddr6" field.
func (_u *NetworkIxLanUpdateOne) SetIpaddr6(v string) *NetworkIxLanUpdateOne {
	_u.mutation.SetIpaddr6(v)
	return _u
}

// SetNillableIpaddr6 sets the "ipaddr6" field if the given value is not nil.
func (_u *NetworkIxLanUpdateOne) SetNillableIpaddr6(v *string) *NetworkIxLanUpdateOne {
	if v != nil {
		_u.SetIpaddr6(*v)
	}
	return _u
}

// ClearIpaddr6 clears the value of the "ipaddr6" field.
func (_u *NetworkIxLanUpdateOne) ClearIpaddr6() *NetworkIxLanUpdateOne {
	_u.mutation.ClearIpaddr6()
	return _u
}

// SetIsRsPeer sets the "is_rs_peer" field.
func (_u *NetworkIxLanUpdateOne) SetIsRsPeer(v bool) *NetworkIxLanUpdateOne {
	_u.mutation.SetIsRsPeer(v)
	return _u
}

// SetNillableIsRsPeer sets the "is_rs_peer" field if the given value is not nil.
func (_u *NetworkIxLanUpdateOne) SetNillableIsRsPeer(v *bool) *NetworkIxLanUpdateOne {
	if v != nil {
		_u.SetIsRsPeer(*v)
	}
	return _u
}

// SetNotes sets the "notes" field.
func (_u *NetworkIxLanUpdateOne) SetNotes(v string) *NetworkIxLanUpdateOne {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *NetworkIxLanUpdateOne) SetNillableNotes(v *string) *NetworkIxLanUpdateOne {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *NetworkIxLanUpdateOne) ClearNotes() *NetworkIxLanUpdateOne {
	_u.mutation.ClearNotes()
	return _u
}

// SetOperational sets the "operational" field.
func (_u *NetworkIxLanUpdateOne) SetOperational(v bool) *NetworkIxLanUpdateOne {
	_u.mutation.SetOperational(v)
	return _u
}

// SetNillableOperational sets the "operational" field if the given value is not nil.
func (_u *NetworkIxLanUpdateOne) SetNillableOperational(v *bool) *NetworkIxLanUpdateOne {
	if v != nil {
		_u.SetOperational(*v)
	}
	return _u
}

// SetSpeed sets the "speed" field.
func (_u *NetworkIxLanUpdateOne) SetSpeed(v int) *NetworkIxLanUpdateOne {
	_u.mutation.ResetSpeed()
	_u.mutation.SetSpeed(v)
	return _u
}

// SetNillableSpeed sets the "speed" field if the given value is not nil.
func (_u *NetworkIxLanUpdateOne) SetNillableSpeed(v *int) *NetworkIxLanUpdateOne {
	if v != nil {
		_u.SetSpeed(*v)
	}
	return _u
}

// AddSpeed adds value to the "speed" field.
func (_u *NetworkIxLanUpdateOne) AddSpeed(v int) *NetworkIxLanUpdateOne {
	_u.mutation.AddSpeed(v)
	return _u
}

// SetIxID sets the "ix_id" field.
func (_u *NetworkIxLanUpdateOne) SetIxID(v int) *NetworkIxLanUpdateOne {
	_u.mutation.ResetIxID()
	_u.mutation.SetIxID(v)
	return _u
}

// SetNillableIxID sets the "ix_id" field if the given value is not nil.
func (_u *NetworkIxLanUpdateOne) SetNillableIxID(v *int) *NetworkIxLanUpdateOne {
	if v != nil {
		_u.SetIxID(*v)
	}
	return _u
}

// AddIxID adds value to the "ix_id" field.
func (_u *NetworkIxLanUpdateOne) AddIxID(v int) *NetworkIxLanUpdateOne {
	_u.mutation.AddIxID(v)
	return _u
}

// ClearIxID clears the value of the "ix_id" field.
func (_u *NetworkIxLanUpdateOne) ClearIxID() *NetworkIxLanUpdateOne {
	_u.mutation.ClearIxID()
	return _u
}

// SetName sets the "name" field.
func (_u *NetworkIxLanUpdateOne) SetName(v string) *NetworkIxLanUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *NetworkIxLanUpdateOne) SetNillableName(v *string) *NetworkIxLanUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// ClearName clears the value of the "name" field.
func (_u *NetworkIxLanUpdateOne) ClearName() *NetworkIxLanUpdateOne {
	_u.mutation.ClearName()
	return _u
}

// SetUpdated sets the "updated" field.
func (_u *NetworkIxLanUpdateOne) SetUpdated(v time.Time) *NetworkIxLanUpdateOne {
	_u.mutation.SetUpdated(v)
	return _u
}

// SetNillableUpdated sets the "updated" field if the given value is not nil.
func (_u *NetworkIxLanUpdateOne) SetNillableUpdated(v *time.Time) *NetworkIxLanUpdateOne {
	if v != nil {
		_u.SetUpdated(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *NetworkIxLanUpdateOne) SetStatus(v string) *NetworkIxLanUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *NetworkIxLanUpdateOne) SetNillableStatus(v *string) *NetworkIxLanUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetIxLanID sets the "ix_lan" edge to the IxLan entity by ID.
func (_u *NetworkIxLanUpdateOne) SetIxLanID(id int) *NetworkIxLanUpdateOne {
	_u.mutation.SetIxLanID(id)
	return _u
}

// SetNillableIxLanID sets the "ix_lan" edge to the IxLan entity by ID if the given value is not nil.
func (_u *NetworkIxLanUpdateOne) SetNillableIxLanID(id *int) *NetworkIxLanUpdateOne {
	if id != nil {
		_u = _u.SetIxLanID(*id)
	}
	return _u
}

// SetIxLan sets the "ix_lan" edge to the IxLan entity.
func (_u *NetworkIxLanUpdateOne) SetIxLan(v *IxLan) *NetworkIxLanUpdateOne {
	return _u.SetIxLanID(v.ID)
}

// SetNetworkID sets the "network" edge to the Network entity by ID.
func (_u *NetworkIxLanUpdateOne) SetNetworkID(id int) *NetworkIxLanUpdateOne {
	_u.mutation.SetNetworkID(id)
	return _u
}

// SetNillableNetworkID sets the "network" edge to the Network entity by ID if the given value is not nil.
func (_u *NetworkIxLanUpdateOne) SetNillableNetworkID(id *int) *NetworkIxLanUpdateOne {
	if id != nil {
		_u = _u.SetNetworkID(*id)
	}
	return _u
}

// SetNetwork sets the "network" edge to the Network entity.
func (_u *NetworkIxLanUpdateOne) SetNetwork(v *Network) *NetworkIxLanUpdateOne {
	return _u.SetNetworkID(v.ID)
}

// Mutation returns the NetworkIxLanMutation object of the builder.
func (_u *NetworkIxLanUpdateOne) Mutation() *NetworkIxLanMutation {
	return _u.mutation
}

// ClearIxLan clears the "ix_lan" edge to the IxLan entity.
func (_u *NetworkIxLanUpdateOne) ClearIxLan() *NetworkIxLanUpdateOne {
	_u.mutation.ClearIxLan()
	return _u
}

// ClearNetwork clears the "network" edge to the Network entity.
func (_u *NetworkIxLanUpdateOne) ClearNetwork() *NetworkIxLanUpdateOne {
	_u.mutation.ClearNetwork()
	return _u
}

// Where appends a list predicates to the NetworkIxLanUpdate builder.
func (_u *NetworkIxLanUpdateOne) Where(ps ...predicate.NetworkIxLan) *NetworkIxLanUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *NetworkIxLanUpdateOne) Select(field string, fields ...string) *NetworkIxLanUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated NetworkIxLan entity.
func (_u *NetworkIxLanUpdateOne) Save(ctx context.Context) (*NetworkIxLan, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NetworkIxLanUpdateOne) SaveX(ctx context.Context) *NetworkIxLan {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *NetworkIxLanUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NetworkIxLanUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *NetworkIxLanUpdateOne) check() error {
	if v, ok := _u.mutation.Asn(); ok {
		if err := networkixlan.AsnValidator(v); err != nil {
			return &ValidationError{Name: "asn", err: fmt.Errorf(`ent: validator failed for field "NetworkIxLan.asn": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Notes(); ok {
		if err := networkixlan.NotesValidator(v); err != nil {
			return &ValidationError{Name: "notes", err: fmt.Errorf(`ent: validator failed for field "NetworkIxLan.notes": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := networkixlan.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "NetworkIxLan.status": %w`, err)}
		}
	}
	return nil
}

func (_u *NetworkIxLanUpdateOne) sqlSave(ctx context.Context) (_node *NetworkIxLan, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(networkixlan.Table, networkixlan.Columns, sqlgraph.NewFieldSpec(networkixlan.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "NetworkIxLan.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, networkixlan.FieldID)
		for _, f := range fields {
			if !networkixlan.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != networkixlan.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.IxSideID(); ok {
		_spec.SetField(networkixlan.FieldIxSideID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedIxSideID(); ok {
		_spec.AddField(networkixlan.FieldIxSideID, field.TypeInt, value)
	}
	if _u.mutation.IxSideIDCleared() {
		_spec.ClearField(networkixlan.FieldIxSideID, field.TypeInt)
	}
	if value, ok := _u.mutation.NetSideID(); ok {
		_spec.SetField(networkixlan.FieldNetSideID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedNetSideID(); ok {
		_spec.AddField(networkixlan.FieldNetSideID, field.TypeInt, value)
	}
	if _u.mutation.NetSideIDCleared() {
		_spec.ClearField(networkixlan.FieldNetSideID, field.TypeInt)
	}
	if value, ok := _u.mutation.Asn(); ok {
		_spec.SetField(networkixlan.FieldAsn, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAsn(); ok {
		_spec.AddField(networkixlan.FieldAsn, field.TypeInt, value)
	}
	if value, ok := _u.mutation.BfdSupport(); ok {
		_spec.SetField(networkixlan.FieldBfdSupport, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Ipaddr4(); ok {
		_spec.SetField(networkixlan.FieldIpaddr4, field.TypeString, value)
	}
	if _u.mutation.Ipaddr4Cleared() {
		_spec.ClearField(networkixlan.FieldIpaddr4, field.TypeString)
	}
	if value, ok := _u.mutation.Ipaddr6(); ok {
		_spec.SetField(networkixlan.FieldIpaddr6, field.TypeString, value)
	}
	if _u.mutation.Ipaddr6Cleared() {
		_spec.ClearField(networkixlan.FieldIpaddr6, field.TypeString)
	}
	if value, ok := _u.mutation.IsRsPeer(); ok {
		_spec.SetField(networkixlan.FieldIsRsPeer, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(networkixlan.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(networkixlan.FieldNotes, field.TypeString)
	}
	if value, ok := _u.mutation.Operational(); ok {
		_spec.SetField(networkixlan.FieldOperational, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Speed(); ok {
		_spec.SetField(networkixlan.FieldSpeed, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSpeed(); ok {
		_spec.AddField(networkixlan.FieldSpeed, field.TypeInt, value)
	}
	if value, ok := _u.mutation.IxID(); ok {
		_spec.SetField(networkixlan.FieldIxID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedIxID(); ok {
		_spec.AddField(networkixlan.FieldIxID, field.TypeInt, value)
	}
	if _u.mutation.IxIDCleared() {
		_spec.ClearField(networkixlan.FieldIxID, field.TypeInt)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(networkixlan.FieldName, field.TypeString, value)
	}
	if _u.mutation.NameCleared() {
		_spec.ClearField(networkixlan.FieldName, field.TypeString)
	}
	if value, ok := _u.mutation.Updated(); ok {
		_spec.SetField(networkixlan.FieldUpdated, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(networkixlan.FieldStatus, field.TypeString, value)
	}
	if _u.mutation.IxLanCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   networkixlan.IxLanTable,
			Columns: []string{networkixlan.IxLanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ixlan.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.IxLanIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   networkixlan.IxLanTable,
			Columns: []string{networkixlan.IxLanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ixlan.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.NetworkCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   networkixlan.NetworkTable,
			Columns: []string{networkixlan.NetworkColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(network.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.NetworkIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   networkixlan.NetworkTable,
			Columns: []string{networkixlan.NetworkColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(network.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &NetworkIxLan{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{networkixlan.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
