// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

// SyncingPage renders a standalone page shown by readiness middleware
// before the first sync completes. It is self-contained with its own
// DOCTYPE, head, and styling because it renders outside the normal
// handler flow at the middleware level.
func SyncingPage() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><meta http-equiv=\"refresh\" content=\"10\"><title>Syncing - PeeringDB Plus</title><link rel=\"icon\" type=\"image/svg+xml\" href=\"/static/favicon.svg\"><link rel=\"icon\" type=\"image/x-icon\" href=\"/static/favicon.ico\"><script src=\"https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4\"></script><style>\n\t\t\t\tbody { background-color: #171717; color: #f5f5f5; }\n\t\t\t\t@keyframes pulse {\n\t\t\t\t\t0%, 100% { opacity: 1; }\n\t\t\t\t\t50% { opacity: 0.4; }\n\t\t\t\t}\n\t\t\t\t.animate-pulse-slow { animation: pulse 2s ease-in-out infinite; }\n\t\t\t</style></head><body><div class=\"min-h-screen bg-neutral-900 flex items-center justify-center\"><div class=\"text-center\"><h1 class=\"text-4xl font-bold text-emerald-500 font-mono mb-6\">PeeringDB Plus</h1><p class=\"text-neutral-400 text-lg mb-8\">Syncing data...</p><div class=\"flex justify-center space-x-2\"><div class=\"w-3 h-3 bg-emerald-500 rounded-full animate-pulse-slow\"></div><div class=\"w-3 h-3 bg-emerald-500 rounded-full animate-pulse-slow\" style=\"animation-delay: 0.3s\"></div><div class=\"w-3 h-3 bg-emerald-500 rounded-full animate-pulse-slow\" style=\"animation-delay: 0.6s\"></div></div><p class=\"text-neutral-600 text-sm mt-8\">This page refreshes automatically.</p></div></div></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
